package com.linguapro.android

/** Further original units that widen everyday, academic and professional CEFR coverage. */
object CourseExpansionMastery {
    private fun ex(id: String, skill: Skill, instruction: String, prompt: String, answer: String,
                   explanation: String, options: List<String> = emptyList(), passage: String = "",
                   audio: String? = null, sample: String? = null) = LearningExercise(
        id, skill, instruction, prompt, passage, options, listOf(answer), explanation, audio, sample
    )
    private fun lesson(level: String, unit: Int, n: Int, title: String, outcome: String, vararg ex: LearningExercise) =
        LearningLesson("$level-U$unit-L$n", title, outcome, ex.toList())
    private fun unit(level: String, n: Int, title: String, summary: String, a: LearningLesson, b: LearningLesson) =
        LearningUnit("$level-U$n", title, summary, listOf(a, b))

    private val content = mapOf(
        "A1" to listOf(
            unit("A1", 10, "Health & Everyday Needs", "Name familiar body parts and explain a simple need.",
                lesson("A1", 10, 1, "How do you feel?", "Understand a basic health question and name a familiar feeling.",
                    ex("a1-feel-listen", Skill.LISTENING, "Kısa konuşmayı dinle", "How does Ben feel?", "tired", "Ben yorgun olduğunu söylüyor.", listOf("tired", "hungry", "cold"), audio = "How do you feel, Ben? I'm a little tired today."),
                    ex("a1-feel-vocab", Skill.VOCABULARY, "Uygun kelimeyi seç", "You drink water when you are…", "thirsty", "Thirsty, susamış anlamına gelir.", listOf("thirsty", "sleepy", "angry"))),
                lesson("A1", 10, 2, "At the doctor's", "Understand a simple question about a symptom.",
                    ex("a1-doctor-read", Skill.READING, "Randevu kartını oku", "When is Eva's appointment?", "Tuesday morning", "Kartta randevu salı sabahı olarak yazıyor.", listOf("Monday afternoon", "Tuesday morning", "Friday evening"), passage = "Eva Demir — appointment with Dr Lee — Tuesday, 10:30 a.m. Please arrive ten minutes early."),
                    ex("a1-doctor-speak", Skill.SPEAKING, "Basit bir belirti söyle", "Say: I have a headache.", "I have a headache", "I have + symptom, yaygın bir belirti anlatımıdır.", audio = "I have a headache.", sample = "I have a headache."))),
            unit("A1", 11, "School & Classroom", "Ask for classroom objects and follow familiar learning instructions.",
                lesson("A1", 11, 1, "What is in your bag?", "Name familiar classroom items and understand a short list.",
                    ex("a1-classroom-read", Skill.READING, "Listeyi oku", "Which item does Mina need?", "a ruler", "Listede Mina'nın cetvele ihtiyacı olduğu belirtiliyor.", listOf("a ruler", "a notebook", "a pencil case"), passage = "For art class, please bring coloured pencils, a ruler and paper. Mina has paper and pencils, but she needs a ruler."),
                    ex("a1-classroom-vocab", Skill.VOCABULARY, "Doğru kelimeyi seç", "You write notes in a…", "notebook", "Notebook, not almak için kullanılan defterdir.", listOf("notebook", "window", "eraser"))),
                lesson("A1", 11, 2, "Classroom instructions", "Understand and give a short classroom instruction.",
                    ex("a1-class-listen", Skill.LISTENING, "Öğretmenin talimatını dinle", "What should the students open?", "their books", "Öğretmen kitaplarını açmalarını söylüyor.", listOf("their books", "the windows", "their bags"), audio = "Please open your books to page twelve."),
                    ex("a1-class-grammar", Skill.GRAMMAR, "Emir cümlesini tamamla", "___ your name at the top of the page.", "Write", "Emir cümlesi fiilin yalın hâliyle başlar.", listOf("Write", "Writes", "Writing")))),
            unit("A1", 12, "Celebrations & Invitations", "Invite someone to a simple event and understand a basic reply.",
                lesson("A1", 12, 1, "A birthday invitation", "Understand the day and place of a simple invitation.",
                    ex("a1-party-read", Skill.READING, "Daveti oku", "Where is the party?", "at Deniz's house", "Davette kutlamanın Deniz'in evinde olduğu yazıyor.", listOf("at the café", "at Deniz's house", "at the park"), passage = "Hi! It's my birthday on Saturday. Please come to my house at three o'clock. We can have cake in the garden! — Deniz"),
                    ex("a1-party-grammar", Skill.GRAMMAR, "Doğru edatı seç", "My birthday is ___ Saturday.", "on", "Günlerden önce on kullanılır.", listOf("on", "at", "in"))),
                lesson("A1", 12, 2, "Would you like to come?", "Accept a simple invitation politely.",
                    ex("a1-invite-listen", Skill.LISTENING, "Davet yanıtını dinle", "Can Ece come to dinner?", "yes, at seven", "Ece akşam yedide gelebileceğini söylüyor.", listOf("yes, at seven", "no, on Sunday", "yes, at nine"), audio = "Would you like to have dinner with us? Yes, thank you. I can be there at seven."),
                    ex("a1-invite-write", Skill.WRITING, "Kısa bir kabul yanıtı yaz", "Accept an invitation to a picnic.", "Yes, thank you. I'd love to come.", "Kibarca evet de ve davet için teşekkür et.", sample = "Yes, thank you. I'd love to come to the picnic.")))
        ),
        "A2" to listOf(
            unit("A2", 8, "Holiday Stories & Memories", "Describe a holiday experience and compare places visited.",
                lesson("A2", 8, 1, "A day by the sea", "Understand a short holiday story and identify its sequence.",
                    ex("a2-holiday-read", Skill.READING, "Gezi günlüğünü oku", "Why did they go back to the hotel?", "it started to rain", "Metinde yağmur başlayınca otele döndükleri anlatılıyor.", listOf("they were hungry", "it started to rain", "the museum closed"), passage = "We walked along the beach in the morning. After lunch, it started to rain, so we returned to the hotel and played cards."),
                    ex("a2-holiday-grammar", Skill.GRAMMAR, "Neden-sonuç ilişkisini kuran bağlacı seç", "It started to rain, ___ we went inside.", "so", "So, önceki olayın sonucunu bağlar.", listOf("so", "but", "because of"))),
                lesson("A2", 8, 2, "Plan a day trip", "Compare transport and choose a practical option.",
                    ex("a2-trip-listen", Skill.LISTENING, "İki seçeneği dinle", "Why do they choose the bus?", "it is cheaper", "Konuşmacı otobüsün daha ucuz olduğunu söylüyor.", listOf("it is faster", "it is cheaper", "it leaves later"), audio = "The train is faster, but the bus is cheaper. Let's take the bus and leave at eight."),
                    ex("a2-trip-speak", Skill.SPEAKING, "Bir gezi tercihi öner", "Say: Let's take the bus because it's cheaper.", "Let's take the bus because it's cheaper", "Let's + fiil, birlikte öneri sunar.", audio = "Let's take the bus because it's cheaper.", sample = "Let's take the bus because it's cheaper."))),
            unit("A2", 9, "Study Skills & Learning Plans", "Talk about current learning routines and set a simple goal.",
                lesson("A2", 9, 1, "How do you learn?", "Understand study advice and choose a practical routine.",
                    ex("a2-study-read", Skill.READING, "Öğrenme önerisini oku", "What does the writer do every day?", "reviews new words", "Yazar her gün yeni kelimeleri tekrar ediyor.", listOf("watches a film", "reviews new words", "writes a long essay"), passage = "I study for fifteen minutes after breakfast. I review new words on Monday and Wednesday, and I listen to a short podcast on Friday."),
                    ex("a2-study-vocab", Skill.VOCABULARY, "Öğrenme fiilini seç", "To look at something again to remember it, you…", "review it", "Review, yeniden gözden geçirip tekrar etmek demektir.", listOf("review it", "borrow it", "lose it"))),
                lesson("A2", 9, 2, "Set a learning goal", "Describe a near-future intention and its frequency.",
                    ex("a2-goal-grammar", Skill.GRAMMAR, "Plan cümlesini tamamla", "This month, I'm ___ practise speaking twice a week.", "going to", "Plan ve niyet için be going to yapısı kullanılır.", listOf("going to", "will to", "go")),
                    ex("a2-goal-write", Skill.WRITING, "Ölçülebilir bir öğrenme hedefi yaz", "Write how often you will practise English.", "I will practise three times a week.", "Hedefine eylem ve sıklık ekle.", sample = "I am going to practise English for fifteen minutes every day."))),
            unit("A2", 10, "Nature & Responsible Choices", "Describe a local environment and make a simple responsible suggestion.",
                lesson("A2", 10, 1, "A clean neighbourhood", "Understand a community notice and identify an action.",
                    ex("a2-nature-read", Skill.READING, "Mahalle duyurusunu oku", "What should volunteers bring?", "gloves", "Duyuru gönüllülerden eldiven getirmelerini istiyor.", listOf("gloves", "paint", "umbrellas"), passage = "Join our park clean-up this Sunday at 10 a.m. Please bring gloves and a reusable water bottle. Bags will be provided."),
                    ex("a2-nature-grammar", Skill.GRAMMAR, "Öneri cümlesini tamamla", "We ___ use reusable bags to reduce plastic.", "should", "Should, öneri ve tavsiye verir.", listOf("should", "did", "are"))),
                lesson("A2", 10, 2, "Make a greener choice", "Suggest a small action and understand a reason.",
                    ex("a2-green-listen", Skill.LISTENING, "Öneriyi dinle", "Why does Sara walk to the shop?", "it is nearby", "Dükkân yakın olduğu için yürümeyi seçiyor.", listOf("it is nearby", "she has no shoes", "the bus is free"), audio = "I walk to the shop because it's only five minutes away."),
                    ex("a2-green-write", Skill.WRITING, "Yerel çevre için bir öneri yaz", "Suggest one small way to reduce waste.", "We should reuse paper.", "Küçük, uygulanabilir bir öneri yaz.", sample = "We should reuse paper and carry a refillable bottle.")))
        ),
        "B1" to listOf(
            unit("B1", 8, "Consumer Issues & Public Services", "Explain a service problem and request a reasonable solution.",
                lesson("B1", 8, 1, "Make a complaint", "Summarize a purchase issue and state the outcome you want.",
                    ex("b1-complaint-read", Skill.READING, "Müşteri e-postasını oku", "What solution does the customer request?", "a replacement", "Müşteri arızalı ürün için yeni ürün talep ediyor.", listOf("a full refund", "a replacement", "a discount on delivery"), passage = "I ordered a desk lamp on 4 May. It arrived with a broken switch. I have attached a photo and would appreciate a replacement."),
                    ex("b1-complaint-phrase", Skill.WRITING, "Nazik bir çözüm talebi yaz", "Ask a company to replace a faulty item.", "I would appreciate a replacement.", "Sorunu kısaca açıklayıp beklediğin çözümü açıkça belirt.", sample = "The switch is faulty, so I would appreciate a replacement or a refund.")),
                lesson("B1", 8, 2, "Ask for help with a service", "Describe a practical problem and clarify a next step.",
                    ex("b1-service-listen", Skill.LISTENING, "Belediye hizmet hattını dinle", "Where should the caller report the problem?", "the online form", "Görevli sorunun çevrimiçi formdan bildirilmesini istiyor.", listOf("the online form", "the library desk", "the bus driver"), audio = "Please report the damaged streetlight using the online form. The repair team will respond within three working days."),
                    ex("b1-service-grammar", Skill.GRAMMAR, "Kibar dolaylı soruyu seç", "Could you tell me ___ the form is available?", "where", "Could you tell me where…? kibar dolaylı soru yapısıdır.", listOf("where", "where is", "where does")))),
            unit("B1", 9, "Opinions & Decision Making", "Compare reasons and explain a practical decision.",
                lesson("B1", 9, 1, "Support your opinion", "State a view and give a relevant reason and example.",
                    ex("b1-opinion-read2", Skill.READING, "Kısa görüş yazısını oku", "Why does the writer support flexible hours?", "they help staff manage responsibilities", "Yazar esnek saatlerin sorumlulukları yönetmeye yardımcı olduğunu söylüyor.", listOf("they reduce all meetings", "they help staff manage responsibilities", "they remove deadlines"), passage = "Flexible hours can help employees balance work and family responsibilities. For example, parents may start earlier so they can collect children from school."),
                    ex("b1-opinion-vocab2", Skill.VOCABULARY, "Örnek vermek için uygun ifadeyi seç", "___, some parents start work earlier to collect their children.", "For example", "For example, ardından somut bir örnek verilir.", listOf("For example", "In contrast", "As a result"))),
                lesson("B1", 9, 2, "Reach a group decision", "Suggest a compromise and confirm a shared decision.",
                    ex("b1-decision-listen", Skill.LISTENING, "Grup konuşmasını dinle", "What do they decide to do first?", "ask three teams for feedback", "Önce üç ekipten görüş almaya karar veriyorlar.", listOf("launch the plan today", "ask three teams for feedback", "cancel the project"), audio = "Before we choose a date, let's ask three teams for feedback and compare their availability."),
                    ex("b1-decision-speak", Skill.SPEAKING, "Bir uzlaşma öner", "Suggest getting feedback before choosing a date.", "Let's get feedback before we choose a date", "Let's + fiil, ortak eylem önerir.", audio = "Let's get feedback before we choose a date.", sample = "Let's collect feedback from the teams before we choose a launch date."))),
            unit("B1", 10, "Health, Habits & Wellbeing", "Describe a routine and understand suggestions for a balanced lifestyle.",
                lesson("B1", 10, 1, "A healthier routine", "Understand a short account of a habit and its effect.",
                    ex("b1-wellbeing-read", Skill.READING, "Kısa blog yazısını oku", "What change helped Tom sleep better?", "he stopped using his phone late", "Tom yatmadan önce telefonu bırakınca daha iyi uyuduğunu anlatıyor.", listOf("he drank more coffee", "he stopped using his phone late", "he worked later"), passage = "I used to check messages in bed. Since I started leaving my phone in the kitchen, I fall asleep more easily and feel less tired in the morning."),
                    ex("b1-wellbeing-grammar", Skill.GRAMMAR, "Geçmiş alışkanlık yapısını seç", "I ___ drink coffee late, but I don't now.", "used to", "Used to geçmişte düzenli olan ama artık olmayan alışkanlığı anlatır.", listOf("used to", "am used to", "use"))),
                lesson("B1", 10, 2, "Give supportive advice", "Offer a considerate suggestion and avoid sounding too forceful.",
                    ex("b1-support-listen", Skill.LISTENING, "Arkadaş tavsiyesini dinle", "What does Alex suggest?", "taking a short break", "Alex kısa bir mola vermesini öneriyor.", listOf("working all night", "taking a short break", "canceling the course"), audio = "You've been studying for hours. Why don't you take a short break and get some fresh air?"),
                    ex("b1-support-write", Skill.WRITING, "Destekleyici bir tavsiye yaz", "Suggest that a tired friend take a short break.", "You could take a short break.", "You could… yumuşak ve destekleyici tavsiye verir.", sample = "You could take a short break and come back to the task later.")))
        ),
        "B2" to listOf(
            unit("B2", 8, "Project Leadership & Delivery", "Clarify ownership, risks and milestones in a project update.",
                lesson("B2", 8, 1, "Flag a project risk", "Explain a risk, its potential effect and a mitigation.",
                    ex("b2-risk-read", Skill.READING, "Proje güncellemesini oku", "What is the main risk?", "the supplier may miss the deadline", "Güncelleme tedarikçinin teslim tarihini kaçırma olasılığını vurguluyor.", listOf("the team has no design", "the supplier may miss the deadline", "the client canceled the project"), passage = "The supplier has not confirmed dispatch. If delivery slips beyond Thursday, testing will lose two days. We have identified a local backup supplier."),
                    ex("b2-risk-grammar", Skill.GRAMMAR, "First conditional sonucunda will + yalın fiil yapısını seç", "If delivery is delayed, testing ___ two days.", "will lose", "First conditional: If + present, will + base verb.", listOf("will lose", "would lost", "loses"))),
                lesson("B2", 8, 2, "Lead a project review", "Summarize progress and agree on an accountable next action.",
                    ex("b2-review-listen", Skill.LISTENING, "Proje değerlendirmesini dinle", "Who will contact the supplier?", "Nora", "Toplantıda tedarikçiyi Nora'nın araması kararlaştırılıyor.", listOf("Nora", "the client", "the design team"), audio = "Nora will contact the supplier today. If we don't get confirmation by noon tomorrow, we'll use the local backup."),
                    ex("b2-review-write", Skill.WRITING, "Sorumlu ve zamanı belirten eylem maddesi yaz", "Record that Nora will contact the supplier today.", "Nora will contact the supplier today.", "Eylem maddesi sorumluyu ve son tarihi içerir.", sample = "Action: Nora to confirm dispatch with the supplier by noon tomorrow."))),
            unit("B2", 9, "Research & Academic Communication", "Summarize a source, qualify a claim and respond to a question.",
                lesson("B2", 9, 1, "Summarize a study", "Report method and finding while noting a limitation.",
                    ex("b2-study-read", Skill.READING, "Araştırma özetini oku", "What limits the finding?", "the participants came from one region", "Tek bölgeden katılımcı seçilmesi genellemeyi sınırlar.", listOf("the study lasted ten years", "the participants came from one region", "there were no participants"), passage = "A survey of 600 adults in one region found that 42% preferred evening classes. Because responses came from a single region, the result may not represent the wider population."),
                    ex("b2-study-vocab", Skill.VOCABULARY, "Genellenebilirliği sınırlayan ifadeyi seç", "The finding may not be ___ to the wider population.", "generalizable", "Generalizable, başka gruplara genellenebilir anlamına gelir.", listOf("generalizable", "available", "identical"))),
                lesson("B2", 9, 2, "Answer a challenge", "Respond to a critical question with evidence and a careful qualification.",
                    ex("b2-challenge-speak", Skill.SPEAKING, "Kanıtla yanıtla ve sınırı kabul et", "Say that the evidence is useful but based on one region.", "The evidence is useful but limited", "Önce katkıyı kabul et, ardından kanıtın sınırını belirt.", audio = "The evidence is useful, although it is limited to one region.", sample = "The evidence is useful, although the single-region sample limits how far we can generalize."),
                    ex("b2-challenge-grammar", Skill.GRAMMAR, "Uygun niteleyiciyi seç", "The results ___ indicate a preference, but they do not establish causation.", "may", "May, kanıtın desteklediği ama kesinleştirmediği olasılığı belirtir.", listOf("may", "must definitely", "cannot ever")))),
            unit("B2", 10, "Sustainability & Civic Action", "Evaluate a local proposal and distinguish impact claims from evidence.",
                lesson("B2", 10, 1, "Evaluate a local proposal", "Identify a proposed benefit and a condition for measuring it.",
                    ex("b2-civic-read", Skill.READING, "Belediye önerisini oku", "What outcome will the pilot track?", "daily traffic volume", "Pilotun günlük trafik hacmini ölçeceği belirtiliyor.", listOf("daily traffic volume", "school exam results", "restaurant prices"), passage = "The council will trial a car-free street on Saturdays for two months. The pilot will track pedestrian counts, local business feedback and daily traffic volume on nearby roads."),
                    ex("b2-civic-vocab", Skill.VOCABULARY, "Ölçülebilir sonucu seç", "Which is the most measurable indicator?", "pedestrian counts", "Pedestrian counts sayılabilir ve karşılaştırılabilir bir göstergedir.", listOf("pedestrian counts", "a nicer feeling", "a better atmosphere"))),
                lesson("B2", 10, 2, "Make a proportionate recommendation", "Recommend continuing, revising or ending a pilot based on evidence.",
                    ex("b2-civic-listen", Skill.LISTENING, "Değerlendirme konuşmasını dinle", "What does the speaker recommend?", "extend the pilot with changes", "Konuşmacı değişikliklerle pilotu uzatmayı öneriyor.", listOf("end it immediately", "extend the pilot with changes", "expand it everywhere now"), audio = "Pedestrian numbers rose, but nearby traffic increased. I recommend extending the pilot after adjusting the diversion route."),
                    ex("b2-civic-write", Skill.WRITING, "Kanıta dayalı kısa öneri yaz", "Recommend a revised pilot and name one measure.", "We should extend the pilot.", "Önerini gözlenen kanıt ve takip ölçütüyle temellendir.", sample = "We should extend the revised pilot for one month and continue tracking pedestrian counts and nearby traffic.")))
        ),
        "C1" to listOf(
            unit("C1", 8, "Rhetorical Style & Concision", "Adapt complex messages for audience, purpose and level of detail.",
                lesson("C1", 8, 1, "Make a dense point concise", "Condense a long explanation while retaining its central qualification.",
                    ex("c1-concise-read", Skill.READING, "Uzun açıklamayı oku", "What is the central qualification?", "the benefit depends on equitable access", "Metin yararın adil erişim koşuluna bağlı olduğunu vurguluyor.", listOf("the cost is irrelevant", "the benefit depends on equitable access", "the programme has ended"), passage = "The programme may yield substantial benefits over time; however, these benefits are unlikely to be distributed evenly unless access barriers are addressed from the outset."),
                    ex("c1-concise-vocab", Skill.VOCABULARY, "En özlü ama doğru özeti seç", "The benefits are conditional on…", "equitable access", "Özet temel koşulu korur.", listOf("equitable access", "immediate expansion", "removing evaluation"))),
                lesson("C1", 8, 2, "Adapt a message to its audience", "Reframe a technical point for a non-specialist audience.",
                    ex("c1-audience-speak", Skill.SPEAKING, "Teknik sonucu sade anlat", "Explain that the sample is too small for a firm conclusion.", "The sample is too small for a firm conclusion", "Teknik doğruluğu koruyup gereksiz jargonu azalt.", audio = "The sample is too small for us to draw a firm conclusion.", sample = "We need more participants before we can be confident in the result."),
                    ex("c1-audience-write", Skill.WRITING, "Uzman olmayan okura bir cümle yaz", "Explain why more data is needed.", "We need more data.", "Sadeleştirirken belirsizliği ve nedenini koru.", sample = "We need data from more people before we can tell whether this result applies more widely."))),
            unit("C1", 9, "Stakeholder Communication", "Anticipate stakeholder concerns and negotiate an evidence-informed response.",
                lesson("C1", 9, 1, "Address a stakeholder concern", "Acknowledge a concern and explain a safeguard.",
                    ex("c1-stakeholder-read", Skill.READING, "Paydaş notunu oku", "What safeguard is requested?", "a transparent appeal process", "Paydaş kararların gözden geçirilmesi için şeffaf itiraz süreci istiyor.", listOf("a faster launch", "a transparent appeal process", "fewer public updates"), passage = "The community group supports the proposal in principle but is concerned that automated decisions may be difficult to challenge. It requests a transparent appeal process and regular reporting."),
                    ex("c1-stakeholder-grammar", Skill.GRAMMAR, "Taviz bağlacını seç", "___ the efficiency gains, decisions must remain open to appeal.", "Notwithstanding", "Notwithstanding + noun phrase ile taviz ve karşıtlık kurulur.", listOf("Notwithstanding", "Because", "So as to"))),
                lesson("C1", 9, 2, "Negotiate a safeguard", "Propose a safeguard that addresses a concern without abandoning the objective.",
                    ex("c1-safeguard-listen", Skill.LISTENING, "Müzakere önerisini dinle", "What safeguard do both sides accept?", "a human review for disputed cases", "Taraflar itiraz edilen durumlarda insan incelemesini kabul ediyor.", listOf("removing all appeals", "a human review for disputed cases", "publishing private data"), audio = "We can retain the efficiency goal, provided that disputed cases receive a timely human review."),
                    ex("c1-safeguard-speak", Skill.SPEAKING, "Koşullu uzlaşma ifade et", "Say: We can proceed, provided disputed cases receive human review.", "We can proceed provided disputed cases receive human review", "Provided, uzlaşmayı açık bir güvence koşuluna bağlar.", audio = "We can proceed, provided that disputed cases receive a timely human review.", sample = "We can proceed, provided that disputed cases receive a timely human review."))),
            unit("C1", 10, "Uncertainty, Ethics & Argument", "Evaluate uncertainty and communicate an ethical, proportionate recommendation.",
                lesson("C1", 10, 1, "Calibrate certainty", "Distinguish a plausible interpretation from a demonstrated causal claim.",
                    ex("c1-uncertainty-read", Skill.READING, "Kanıt değerlendirmesini oku", "What alternative explanation remains?", "the improvement may reflect seasonal change", "Metin mevsimsel değişimin alternatif açıklama olabileceğini belirtiyor.", listOf("the programme was never used", "the improvement may reflect seasonal change", "the sample was infinite"), passage = "Participation and reported satisfaction rose during the pilot. Without a comparison group, the increase cannot be attributed solely to the intervention; seasonal changes may also have contributed."),
                    ex("c1-uncertainty-vocab", Skill.VOCABULARY, "Nedensellik iddiasını ölçülü ifade et", "The intervention may have ___ to the increase.", "contributed", "Contributed to, etkinin olası katkısını belirtir ama tek neden olduğunu iddia etmez.", listOf("contributed", "guaranteed", "eliminated"))),
                lesson("C1", 10, 2, "Reach an ethical recommendation", "Balance potential benefit, risk and a review condition.",
                    ex("c1-ethics-grammar", Skill.GRAMMAR, "Etik koşulu tamamla", "The system should be used only if its decisions ___ regularly reviewed.", "are", "Edilgen present simple: decisions are reviewed.", listOf("are", "is", "be")),
                    ex("c1-ethics-write", Skill.WRITING, "Yarar, risk ve güvenceyi sentezle", "Write a conditional recommendation for a high-impact tool.", "Use the tool with safeguards.", "Ölçülü öneride yarar kadar risk ve hesap verebilirlik koşulu da bulunur.", sample = "The tool could improve access, provided that decisions are independently audited and affected users have a clear route to appeal.")))
        )
    )

    fun units(level: String): List<LearningUnit> = content[level].orEmpty()
}
