package com.linguapro.android

/** Hacim genişletme içerik paketi: C2 seviyesi (12 ünite, 36 ders). Otomatik derlenmiş, elle küratörlü banka. */
object CourseVolumeC2 {
    val units: List<LearningUnit> = listOf(
        LearningUnit("C2-U1", "Idiomatic Mastery I", "Command low-frequency idioms with precision.", listOf(
            LearningLesson("C2-U1-L1", "Idiomatic Mastery I — Words", "Recognize key vocabulary for this topic.", listOf(
                LearningExercise("c2v1e1", Skill.VOCABULARY, "Doğru anlamı seç", "'throw in the towel' ne anlama gelir?", "", listOf("sonradan hayra dönüşen olay", "buzdağının görünen kısmı", "havlu atmak"), listOf("havlu atmak"), "They refused to throw in the towel despite losses. — Kayıplara rağmen havlu atmayı reddettiler.", null, null),
                LearningExercise("c2v1e2", Skill.VOCABULARY, "Doğru anlamı seç", "'a blessing in disguise' ne anlama gelir?", "", listOf("dişini sıkmak", "sonradan hayra dönüşen olay", "köprüleri atmak"), listOf("sonradan hayra dönüşen olay"), "Losing that job was a blessing in disguise. — O işi kaybetmek aslında gizli bir nimetti.", null, null),
                LearningExercise("c2v1e3", Skill.VOCABULARY, "Doğru anlamı seç", "'burn bridges' ne anlama gelir?", "", listOf("köprüleri atmak", "buzdağının görünen kısmı", "havlu atmak"), listOf("köprüleri atmak"), "Resign politely; never burn your bridges. — Nazikçe istifa et; köprüleri asla atma.", null, null))),
            LearningLesson("C2-U1-L2", "Idiomatic Mastery I — In Use", "Use the new words in real sentences and listening.", listOf(
                LearningExercise("c2v1e4", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "They refused to ___ despite losses.", "", listOf("burn bridges", "throw in the towel", "a blessing in disguise"), listOf("throw in the towel"), "Doğru cümle: They refused to throw in the towel despite losses. — Kayıplara rağmen havlu atmayı reddettiler.", null, null),
                LearningExercise("c2v1e5", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "These errors are just ___.", "", listOf("the tip of the iceberg", "bite the bullet", "throw in the towel"), listOf("the tip of the iceberg"), "Doğru cümle: These errors are just the tip of the iceberg. — Bu hatalar buzdağının yalnızca görünen kısmı.", null, null),
                LearningExercise("c2v1e6", Skill.LISTENING, "Dinle ve anlamı seç", "Cümle ne anlatıyor?", "", listOf("Kayıplara rağmen havlu atmayı reddettiler.", "Nazikçe istifa et; köprüleri asla atma.", "Dişimizi sıkıp kodu baştan yazdık."), listOf("Dişimizi sıkıp kodu baştan yazdık."), "Söylenen cümle: We bit the bullet and rewrote the code.", "We bit the bullet and rewrote the code.", null),
                LearningExercise("c2v1e10", Skill.READING, "Cümleyi oku ve doğru anlamı seç", "Okuduğun cümle ne anlatıyor?", "These errors are just the tip of the iceberg.", listOf("Bu hatalar buzdağının yalnızca görünen kısmı.", "O işi kaybetmek aslında gizli bir nimetti.", "Dişimizi sıkıp kodu baştan yazdık."), listOf("Bu hatalar buzdağının yalnızca görünen kısmı."), "Cümlenin çevirisi: Bu hatalar buzdağının yalnızca görünen kısmı.", null, null))),
            LearningLesson("C2-U1-L3", "Idiomatic Mastery I — Practice", "Apply the grammar focus, speak and write.", listOf(
                LearningExercise("c2v1e7", Skill.GRAMMAR, "Doğru seçeneği işaretle", "Little ___ how costly the delay would prove.", "", listOf("did they realize", "they realized", "they did realize"), listOf("did they realize"), "Little başta: devrik yapı zorunludur.", null, null),
                LearningExercise("c2v1e8", Skill.SPEAKING, "İfadeyi sesli söyle", "Say: Losing that job was a blessing in disguise.", "", listOf(), listOf("Losing that job was a blessing in disguise."), "Türkçesi: O işi kaybetmek aslında gizli bir nimetti.", "Losing that job was a blessing in disguise.", "Losing that job was a blessing in disguise."),
                LearningExercise("c2v1e9", Skill.WRITING, "Cümleyi İngilizce yaz", "İngilizcesi: Nazikçe istifa et; köprüleri asla atma.", "", listOf(), listOf("Resign politely; never burn your bridges."), "Örnek yanıt: Resign politely; never burn your bridges.", null, "Resign politely; never burn your bridges."))))),
        LearningUnit("C2-U2", "Idiomatic Mastery II", "Handle idioms of judgement and emotion.", listOf(
            LearningLesson("C2-U2-L1", "Idiomatic Mastery II — Words", "Recognize key vocabulary for this topic.", listOf(
                LearningExercise("c2v2e1", Skill.VOCABULARY, "Doğru anlamı seç", "'give someone the benefit of the doubt' ne anlama gelir?", "", listOf("satır aralarını okumak", "iyi niyetli olduğunu varsaymak", "kabullenmek"), listOf("iyi niyetli olduğunu varsaymak"), "I gave her the benefit of the doubt. — Aksi kanıtlanmadıkça iyi niyetli olduğunu varsaydım.", null, null),
                LearningExercise("c2v2e2", Skill.VOCABULARY, "Doğru anlamı seç", "'come to terms with' ne anlama gelir?", "", listOf("kabullenmek", "yol ayrımında", "iki ucu keskin kılıç"), listOf("kabullenmek"), "He came to terms with the diagnosis. — Teşhisi zamanla kabullendi.", null, null),
                LearningExercise("c2v2e3", Skill.VOCABULARY, "Doğru anlamı seç", "'at a crossroads' ne anlama gelir?", "", listOf("satır aralarını okumak", "iyi niyetli olduğunu varsaymak", "yol ayrımında"), listOf("yol ayrımında"), "The company stands at a crossroads. — Şirket bir yol ayrımında.", null, null))),
            LearningLesson("C2-U2-L2", "Idiomatic Mastery II — In Use", "Use the new words in real sentences and listening.", listOf(
                LearningExercise("c2v2e4", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "I gave her ___.", "", listOf("the benefit of the doubt", "come to terms with", "at a crossroads"), listOf("the benefit of the doubt"), "Doğru cümle: I gave her the benefit of the doubt. — Aksi kanıtlanmadıkça iyi niyetli olduğunu varsaydım.", null, null),
                LearningExercise("c2v2e5", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "___ of the statement.", "", listOf("a double-edged sword", "give the benefit of the doubt", "Read between the lines"), listOf("Read between the lines"), "Doğru cümle: Read between the lines of the statement. — Açıklamanın satır aralarını oku.", null, null),
                LearningExercise("c2v2e6", Skill.LISTENING, "Dinle ve anlamı seç", "Cümle ne anlatıyor?", "", listOf("Şirket bir yol ayrımında.", "Şöhret iki ucu keskin bir kılıç çıktı.", "Aksi kanıtlanmadıkça iyi niyetli olduğunu varsaydım."), listOf("Şöhret iki ucu keskin bir kılıç çıktı."), "Söylenen cümle: Fame proved a double-edged sword.", "Fame proved a double-edged sword.", null),
                LearningExercise("c2v2e10", Skill.READING, "Cümleyi oku ve doğru anlamı seç", "Okuduğun cümle ne anlatıyor?", "Read between the lines of the statement.", listOf("Teşhisi zamanla kabullendi.", "Şöhret iki ucu keskin bir kılıç çıktı.", "Açıklamanın satır aralarını oku."), listOf("Açıklamanın satır aralarını oku."), "Cümlenin çevirisi: Açıklamanın satır aralarını oku.", null, null))),
            LearningLesson("C2-U2-L3", "Idiomatic Mastery II — Practice", "Apply the grammar focus, speak and write.", listOf(
                LearningExercise("c2v2e7", Skill.GRAMMAR, "Olumsuz zarf öbeğinden sonra doğru devrik dizilişi seç", "Under no circumstances ___.", "", listOf("should the terms be disclosed", "the terms should be disclosed", "should disclosed the terms be"), listOf("should the terms be disclosed"), "Under no circumstances başta olduğunda yardımcı fiil özneden önce gelir: should + the terms + be disclosed. Edilgen fiil öbeği be disclosed sırasını korur.", null, null),
                LearningExercise("c2v2e8", Skill.SPEAKING, "İfadeyi sesli söyle", "Say: He came to terms with the diagnosis.", "", listOf(), listOf("He came to terms with the diagnosis."), "Türkçesi: Teşhisi zamanla kabullendi.", "He came to terms with the diagnosis.", "He came to terms with the diagnosis."),
                LearningExercise("c2v2e9", Skill.WRITING, "Cümleyi İngilizce yaz", "İngilizcesi: Şirket bir yol ayrımında.", "", listOf(), listOf("The company stands at a crossroads."), "Örnek yanıt: The company stands at a crossroads.", null, "The company stands at a crossroads."))))),
        LearningUnit("C2-U3", "Register & Style", "Shift seamlessly between formal and informal registers.", listOf(
            LearningLesson("C2-U3-L1", "Register & Style — Words", "Recognize key vocabulary for this topic.", listOf(
                LearningExercise("c2v3e1", Skill.VOCABULARY, "Doğru anlamı seç", "'endeavour' ne anlama gelir?", "", listOf("çaba göstermek", "derhal", "uyarınca"), listOf("çaba göstermek"), "We shall endeavour to meet your expectations. — Beklentilerinizi karşılamak için çaba göstereceğiz.", null, null),
                LearningExercise("c2v3e2", Skill.VOCABULARY, "Doğru anlamı seç", "'forthwith' ne anlama gelir?", "", listOf("bu beyanla", "gündelik dile özgü", "derhal"), listOf("derhal"), "The account was closed forthwith. — Hesap derhal kapatıldı.", null, null),
                LearningExercise("c2v3e3", Skill.VOCABULARY, "Doğru anlamı seç", "'hereby' ne anlama gelir?", "", listOf("çaba göstermek", "bu beyanla", "uyarınca"), listOf("bu beyanla"), "I hereby confirm my attendance. — Katılımımı işbu yazıyla teyit ederim.", null, null))),
            LearningLesson("C2-U3-L2", "Register & Style — In Use", "Use the new words in real sentences and listening.", listOf(
                LearningExercise("c2v3e4", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "We shall ___ to meet your expectations.", "", listOf("forthwith", "hereby", "endeavour"), listOf("endeavour"), "Doğru cümle: We shall endeavour to meet your expectations. — Beklentilerinizi karşılamak için çaba göstereceğiz.", null, null),
                LearningExercise("c2v3e5", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "___ clause five, fees apply.", "", listOf("endeavour", "Pursuant to", "colloquial"), listOf("Pursuant to"), "Doğru cümle: Pursuant to clause five, fees apply. — Beşinci madde uyarınca ücret uygulanır.", null, null),
                LearningExercise("c2v3e6", Skill.LISTENING, "Dinle ve anlamı seç", "Cümle ne anlatıyor?", "", listOf("Bu ifade bir rapor için fazla gündelik.", "Beklentilerinizi karşılamak için çaba göstereceğiz.", "Katılımımı işbu yazıyla teyit ederim."), listOf("Bu ifade bir rapor için fazla gündelik."), "Söylenen cümle: That phrase is too colloquial for a report.", "That phrase is too colloquial for a report.", null),
                LearningExercise("c2v3e10", Skill.READING, "Cümleyi oku ve doğru anlamı seç", "Okuduğun cümle ne anlatıyor?", "Pursuant to clause five, fees apply.", listOf("Bu ifade bir rapor için fazla gündelik.", "Beşinci madde uyarınca ücret uygulanır.", "Hesap derhal kapatıldı."), listOf("Beşinci madde uyarınca ücret uygulanır."), "Cümlenin çevirisi: Beşinci madde uyarınca ücret uygulanır.", null, null))),
            LearningLesson("C2-U3-L3", "Register & Style — Practice", "Apply the grammar focus, speak and write.", listOf(
                LearningExercise("c2v3e7", Skill.GRAMMAR, "Doğru seçeneği işaretle", "___ it not for the funding, the lab would close.", "", listOf("Were", "Was", "If"), listOf("Were"), "Resmî devrik koşul: Were it not for...", null, null),
                LearningExercise("c2v3e8", Skill.SPEAKING, "İfadeyi sesli söyle", "Say: The account was closed forthwith.", "", listOf(), listOf("The account was closed forthwith."), "Türkçesi: Hesap derhal kapatıldı.", "The account was closed forthwith.", "The account was closed forthwith."),
                LearningExercise("c2v3e9", Skill.WRITING, "Cümleyi İngilizce yaz", "İngilizcesi: Katılımımı işbu yazıyla teyit ederim.", "", listOf(), listOf("I hereby confirm my attendance."), "Örnek yanıt: I hereby confirm my attendance.", null, "I hereby confirm my attendance."))))),
        LearningUnit("C2-U4", "Fine Shades of Meaning", "Distinguish near-synonyms with full control.", listOf(
            LearningLesson("C2-U4-L1", "Fine Shades of Meaning — Words", "Recognize key vocabulary for this topic.", listOf(
                LearningExercise("c2v4e1", Skill.VOCABULARY, "Doğru anlamı seç", "'childish' ne anlama gelir?", "", listOf("çocuksu", "tutumlu", "çocukça"), listOf("çocukça"), "His response was dismissed as childish. — Tepkisi çocukça bulunup önemsenmedi.", null, null),
                LearningExercise("c2v4e2", Skill.VOCABULARY, "Doğru anlamı seç", "'childlike' ne anlama gelir?", "", listOf("aralıklarla süren", "çocuksu", "ekonomik (ekonomiyle ilgili)"), listOf("çocuksu"), "She retained a childlike curiosity. — Çocuksu bir merakını hep korudu.", null, null),
                LearningExercise("c2v4e3", Skill.VOCABULARY, "Doğru anlamı seç", "'economic' ne anlama gelir?", "", listOf("ekonomik (ekonomiyle ilgili)", "tutumlu", "çocukça"), listOf("ekonomik (ekonomiyle ilgili)"), "Economic growth slowed in the third quarter. — Ekonomik büyüme üçüncü çeyrekte yavaşladı.", null, null))),
            LearningLesson("C2-U4-L2", "Fine Shades of Meaning — In Use", "Use the new words in real sentences and listening.", listOf(
                LearningExercise("c2v4e4", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "His response was dismissed as ___.", "", listOf("economic", "childish", "childlike"), listOf("childish"), "Doğru cümle: His response was dismissed as childish. — Tepkisi çocukça bulunup önemsenmedi.", null, null),
                LearningExercise("c2v4e5", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "The new engine is remarkably ___.", "", listOf("economical", "continual", "childish"), listOf("economical"), "Doğru cümle: The new engine is remarkably economical. — Yeni motor dikkat çekici ölçüde tasarruflu.", null, null),
                LearningExercise("c2v4e6", Skill.LISTENING, "Dinle ve anlamı seç", "Cümle ne anlatıyor?", "", listOf("Tepkisi çocukça bulunup önemsenmedi.", "Ekonomik büyüme üçüncü çeyrekte yavaşladı.", "Aralıklarla süren kesintiler toplantıyı raydan çıkardı."), listOf("Aralıklarla süren kesintiler toplantıyı raydan çıkardı."), "Söylenen cümle: Continual interruptions derailed the meeting.", "Continual interruptions derailed the meeting.", null),
                LearningExercise("c2v4e10", Skill.READING, "Cümleyi oku ve doğru anlamı seç", "Okuduğun cümle ne anlatıyor?", "The new engine is remarkably economical.", listOf("Yeni motor dikkat çekici ölçüde tasarruflu.", "Çocuksu bir merakını hep korudu.", "Aralıklarla süren kesintiler toplantıyı raydan çıkardı."), listOf("Yeni motor dikkat çekici ölçüde tasarruflu."), "Cümlenin çevirisi: Yeni motor dikkat çekici ölçüde tasarruflu.", null, null))),
            LearningLesson("C2-U4-L3", "Fine Shades of Meaning — Practice", "Apply the grammar focus, speak and write.", listOf(
                LearningExercise("c2v4e7", Skill.GRAMMAR, "Doğru seçeneği işaretle", "The two terms are ___ interchangeable; context decides.", "", listOf("by no means", "by all means", "by any means"), listOf("by no means"), "By no means = kesinlikle değil.", null, null),
                LearningExercise("c2v4e8", Skill.SPEAKING, "İfadeyi sesli söyle", "Say: She retained a childlike curiosity.", "", listOf(), listOf("She retained a childlike curiosity."), "Türkçesi: Çocuksu bir merakını hep korudu.", "She retained a childlike curiosity.", "She retained a childlike curiosity."),
                LearningExercise("c2v4e9", Skill.WRITING, "Cümleyi İngilizce yaz", "İngilizcesi: Ekonomik büyüme üçüncü çeyrekte yavaşladı.", "", listOf(), listOf("Economic growth slowed in the third quarter."), "Örnek yanıt: Economic growth slowed in the third quarter.", null, "Economic growth slowed in the third quarter."))))),
        LearningUnit("C2-U5", "Academic Discourse", "Write and critique at a scholarly level.", listOf(
            LearningLesson("C2-U5-L1", "Academic Discourse — Words", "Recognize key vocabulary for this topic.", listOf(
                LearningExercise("c2v5e1", Skill.VOCABULARY, "Doğru anlamı seç", "'paradigm' ne anlama gelir?", "", listOf("öne sürmek", "paradigma", "kanıtla desteklemek"), listOf("paradigma"), "The study challenges the dominant paradigm. — Çalışma hakim paradigmaya meydan okuyor.", null, null),
                LearningExercise("c2v5e2", Skill.VOCABULARY, "Doğru anlamı seç", "'corroborate' ne anlama gelir?", "", listOf("kanıtla desteklemek", "ihtiyat kaydı", "göze çarpan"), listOf("kanıtla desteklemek"), "Independent data corroborated the results. — Bağımsız veriler sonuçları destekleyen kanıt sağladı.", null, null),
                LearningExercise("c2v5e3", Skill.VOCABULARY, "Doğru anlamı seç", "'caveat' ne anlama gelir?", "", listOf("öne sürmek", "paradigma", "ihtiyat kaydı"), listOf("ihtiyat kaydı"), "One caveat concerns the sampling method. — Bir ihtiyat kaydı örnekleme yöntemiyle ilgili.", null, null))),
            LearningLesson("C2-U5-L2", "Academic Discourse — In Use", "Use the new words in real sentences and listening.", listOf(
                LearningExercise("c2v5e4", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "The study challenges the dominant ___.", "", listOf("paradigm", "corroborate", "caveat"), listOf("paradigm"), "Doğru cümle: The study challenges the dominant paradigm. — Çalışma hakim paradigmaya meydan okuyor.", null, null),
                LearningExercise("c2v5e5", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "The authors ___ a causal mechanism.", "", listOf("salient", "paradigm", "posit"), listOf("posit"), "Doğru cümle: The authors posit a causal mechanism. — Yazarlar nedensel bir mekanizma öne sürüyor.", null, null),
                LearningExercise("c2v5e6", Skill.LISTENING, "Dinle ve anlamı seç", "Cümle ne anlatıyor?", "", listOf("Bir ihtiyat kaydı örnekleme yöntemiyle ilgili.", "Göze çarpan bulgu yaş farklarıyla ilgili.", "Çalışma hakim paradigmaya meydan okuyor."), listOf("Göze çarpan bulgu yaş farklarıyla ilgili."), "Söylenen cümle: The salient finding involves age differences.", "The salient finding involves age differences.", null),
                LearningExercise("c2v5e10", Skill.READING, "Cümleyi oku ve doğru anlamı seç", "Okuduğun cümle ne anlatıyor?", "The authors posit a causal mechanism.", listOf("Bağımsız veriler sonuçları destekleyen kanıt sağladı.", "Göze çarpan bulgu yaş farklarıyla ilgili.", "Yazarlar nedensel bir mekanizma öne sürüyor."), listOf("Yazarlar nedensel bir mekanizma öne sürüyor."), "Cümlenin çevirisi: Yazarlar nedensel bir mekanizma öne sürüyor.", null, null))),
            LearningLesson("C2-U5-L3", "Academic Discourse — Practice", "Apply the grammar focus, speak and write.", listOf(
                LearningExercise("c2v5e7", Skill.GRAMMAR, "Doğru seçeneği işaretle", "The effect, ___ significant, was small in magnitude.", "", listOf("while", "despite", "whereas of"), listOf("while"), "Kısaltılmış karşıtlık: while significant.", null, null),
                LearningExercise("c2v5e8", Skill.SPEAKING, "İfadeyi sesli söyle", "Say: Independent data corroborated the results.", "", listOf(), listOf("Independent data corroborated the results."), "Türkçesi: Bağımsız veriler sonuçları destekleyen kanıt sağladı.", "Independent data corroborated the results.", "Independent data corroborated the results."),
                LearningExercise("c2v5e9", Skill.WRITING, "Cümleyi İngilizce yaz", "İngilizcesi: Bir ihtiyat kaydı örnekleme yöntemiyle ilgili.", "", listOf(), listOf("One caveat concerns the sampling method."), "Örnek yanıt: One caveat concerns the sampling method.", null, "One caveat concerns the sampling method."))))),
        LearningUnit("C2-U6", "Literary Analysis", "Analyse voice, tone and narrative technique.", listOf(
            LearningLesson("C2-U6-L1", "Literary Analysis — Words", "Recognize key vocabulary for this topic.", listOf(
                LearningExercise("c2v6e1", Skill.VOCABULARY, "Doğru anlamı seç", "'protagonist' ne anlama gelir?", "", listOf("başkahraman", "önceden sezdirme", "güvenilmez anlatıcı"), listOf("başkahraman"), "The protagonist narrates in fragments. — Başkahraman parçalı bir anlatımla konuşur.", null, null),
                LearningExercise("c2v6e2", Skill.VOCABULARY, "Doğru anlamı seç", "'foreshadowing' ne anlama gelir?", "", listOf("alegori", "çözüm bölümü", "önceden sezdirme"), listOf("önceden sezdirme"), "The storm is a clear piece of foreshadowing. — Fırtına açık bir önceden sezdirme örneği.", null, null),
                LearningExercise("c2v6e3", Skill.VOCABULARY, "Doğru anlamı seç", "'allegory' ne anlama gelir?", "", listOf("başkahraman", "alegori", "güvenilmez anlatıcı"), listOf("alegori"), "The island functions as a political allegory. — Ada siyasi bir alegori işlevi görür.", null, null))),
            LearningLesson("C2-U6-L2", "Literary Analysis — In Use", "Use the new words in real sentences and listening.", listOf(
                LearningExercise("c2v6e4", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "The ___ narrates in fragments.", "", listOf("foreshadowing", "allegory", "protagonist"), listOf("protagonist"), "Doğru cümle: The protagonist narrates in fragments. — Başkahraman parçalı bir anlatımla konuşur.", null, null),
                LearningExercise("c2v6e5", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "The twist exposes an ___.", "", listOf("protagonist", "unreliable narrator", "denouement"), listOf("unreliable narrator"), "Doğru cümle: The twist exposes an unreliable narrator. — Sürpriz son güvenilmez bir anlatıcıyı açığa çıkarır.", null, null),
                LearningExercise("c2v6e6", Skill.LISTENING, "Dinle ve anlamı seç", "Cümle ne anlatıyor?", "", listOf("Çözüm bölümü tüm düğümleri çözer.", "Başkahraman parçalı bir anlatımla konuşur.", "Ada siyasi bir alegori işlevi görür."), listOf("Çözüm bölümü tüm düğümleri çözer."), "Söylenen cümle: The denouement ties every thread together.", "The denouement ties every thread together.", null),
                LearningExercise("c2v6e10", Skill.READING, "Cümleyi oku ve doğru anlamı seç", "Okuduğun cümle ne anlatıyor?", "The twist exposes an unreliable narrator.", listOf("Çözüm bölümü tüm düğümleri çözer.", "Sürpriz son güvenilmez bir anlatıcıyı açığa çıkarır.", "Fırtına açık bir önceden sezdirme örneği."), listOf("Sürpriz son güvenilmez bir anlatıcıyı açığa çıkarır."), "Cümlenin çevirisi: Sürpriz son güvenilmez bir anlatıcıyı açığa çıkarır.", null, null))),
            LearningLesson("C2-U6-L3", "Literary Analysis — Practice", "Apply the grammar focus, speak and write.", listOf(
                LearningExercise("c2v6e7", Skill.GRAMMAR, "Doğru seçeneği işaretle", "Not until the final chapter ___ the truth.", "", listOf("do we learn", "we learn", "we do learn"), listOf("do we learn"), "Not until başta: devrik yapı.", null, null),
                LearningExercise("c2v6e8", Skill.SPEAKING, "İfadeyi sesli söyle", "Say: The storm is a clear piece of foreshadowing.", "", listOf(), listOf("The storm is a clear piece of foreshadowing."), "Türkçesi: Fırtına açık bir önceden sezdirme örneği.", "The storm is a clear piece of foreshadowing.", "The storm is a clear piece of foreshadowing."),
                LearningExercise("c2v6e9", Skill.WRITING, "Cümleyi İngilizce yaz", "İngilizcesi: Ada siyasi bir alegori işlevi görür.", "", listOf(), listOf("The island functions as a political allegory."), "Örnek yanıt: The island functions as a political allegory.", null, "The island functions as a political allegory."))))),
        LearningUnit("C2-U7", "Negotiation Mastery", "Steer high-stakes negotiations with finesse.", listOf(
            LearningLesson("C2-U7-L1", "Negotiation Mastery — Words", "Recognize key vocabulary for this topic.", listOf(
                LearningExercise("c2v7e1", Skill.VOCABULARY, "Doğru anlamı seç", "'deadlock' ne anlama gelir?", "", listOf("bağlı olarak", "iyi niyet", "çıkmaz"), listOf("çıkmaz"), "Talks ended in deadlock after midnight. — Görüşmeler gece yarısından sonra çıkmaza girdi.", null, null),
                LearningExercise("c2v7e2", Skill.VOCABULARY, "Doğru anlamı seç", "'contingent upon' ne anlama gelir?", "", listOf("pazarlık dışı", "bağlı olarak", "riski üstlenmek"), listOf("bağlı olarak"), "The offer is contingent upon board approval. — Teklif yönetim kurulu onayına bağlı.", null, null),
                LearningExercise("c2v7e3", Skill.VOCABULARY, "Doğru anlamı seç", "'underwrite' ne anlama gelir?", "", listOf("riski üstlenmek", "iyi niyet", "çıkmaz"), listOf("riski üstlenmek"), "The bank agreed to underwrite the risk. — Banka riski üstlenmeyi kabul etti.", null, null))),
            LearningLesson("C2-U7-L2", "Negotiation Mastery — In Use", "Use the new words in real sentences and listening.", listOf(
                LearningExercise("c2v7e4", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "Talks ended in ___ after midnight.", "", listOf("underwrite", "deadlock", "contingent upon"), listOf("deadlock"), "Doğru cümle: Talks ended in deadlock after midnight. — Görüşmeler gece yarısından sonra çıkmaza girdi.", null, null),
                LearningExercise("c2v7e5", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "Both sides negotiated in ___.", "", listOf("good faith", "non-negotiable", "deadlock"), listOf("good faith"), "Doğru cümle: Both sides negotiated in good faith. — İki taraf da iyi niyetle müzakere etti.", null, null),
                LearningExercise("c2v7e6", Skill.LISTENING, "Dinle ve anlamı seç", "Cümle ne anlatıyor?", "", listOf("Görüşmeler gece yarısından sonra çıkmaza girdi.", "Banka riski üstlenmeyi kabul etti.", "Güvenlik standartları pazarlık konusu olamaz."), listOf("Güvenlik standartları pazarlık konusu olamaz."), "Söylenen cümle: Safety standards are non-negotiable.", "Safety standards are non-negotiable.", null),
                LearningExercise("c2v7e10", Skill.READING, "Cümleyi oku ve doğru anlamı seç", "Okuduğun cümle ne anlatıyor?", "Both sides negotiated in good faith.", listOf("İki taraf da iyi niyetle müzakere etti.", "Teklif yönetim kurulu onayına bağlı.", "Güvenlik standartları pazarlık konusu olamaz."), listOf("İki taraf da iyi niyetle müzakere etti."), "Cümlenin çevirisi: İki taraf da iyi niyetle müzakere etti.", null, null))),
            LearningLesson("C2-U7-L3", "Negotiation Mastery — Practice", "Apply the grammar focus, speak and write.", listOf(
                LearningExercise("c2v7e7", Skill.GRAMMAR, "Doğru seçeneği işaretle", "___ should the clause be read as a waiver.", "", listOf("In no way", "Anyway", "By the way"), listOf("In no way"), "In no way başta: devrik yapı gerekir.", null, null),
                LearningExercise("c2v7e8", Skill.SPEAKING, "İfadeyi sesli söyle", "Say: The offer is contingent upon board approval.", "", listOf(), listOf("The offer is contingent upon board approval."), "Türkçesi: Teklif yönetim kurulu onayına bağlı.", "The offer is contingent upon board approval.", "The offer is contingent upon board approval."),
                LearningExercise("c2v7e9", Skill.WRITING, "Cümleyi İngilizce yaz", "İngilizcesi: Banka riski üstlenmeyi kabul etti.", "", listOf(), listOf("The bank agreed to underwrite the risk."), "Örnek yanıt: The bank agreed to underwrite the risk.", null, "The bank agreed to underwrite the risk."))))),
        LearningUnit("C2-U8", "Humour & Wordplay", "Appreciate puns, understatement and wit.", listOf(
            LearningLesson("C2-U8-L1", "Humour & Wordplay — Words", "Recognize key vocabulary for this topic.", listOf(
                LearningExercise("c2v8e1", Skill.VOCABULARY, "Doğru anlamı seç", "'pun' ne anlama gelir?", "", listOf("şakayla karışık", "kelime oyunu", "olduğundan az gösterme"), listOf("kelime oyunu"), "The headline hides a clever pun. — Manşette zekice bir kelime oyunu gizli.", null, null),
                LearningExercise("c2v8e2", Skill.VOCABULARY, "Doğru anlamı seç", "'understatement' ne anlama gelir?", "", listOf("olduğundan az gösterme", "ciddi yüzle espri anlatımı", "nüktedan"), listOf("olduğundan az gösterme"), "Calling it a setback was an understatement. — Buna aksilik demek durumu hafife almaktı.", null, null),
                LearningExercise("c2v8e3", Skill.VOCABULARY, "Doğru anlamı seç", "'deadpan' ne anlama gelir?", "", listOf("şakayla karışık", "kelime oyunu", "ciddi yüzle espri anlatımı"), listOf("ciddi yüzle espri anlatımı"), "He delivered the joke completely deadpan. — Esprisini tamamen ifadesiz bir yüzle yaptı.", null, null))),
            LearningLesson("C2-U8-L2", "Humour & Wordplay — In Use", "Use the new words in real sentences and listening.", listOf(
                LearningExercise("c2v8e4", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "The headline hides a clever ___.", "", listOf("pun", "understatement", "deadpan"), listOf("pun"), "Doğru cümle: The headline hides a clever pun. — Manşette zekice bir kelime oyunu gizli.", null, null),
                LearningExercise("c2v8e5", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "The review was clearly ___.", "", listOf("witty", "pun", "tongue-in-cheek"), listOf("tongue-in-cheek"), "Doğru cümle: The review was clearly tongue-in-cheek. — İnceleme açıkça şakayla karışıktı.", null, null),
                LearningExercise("c2v8e6", Skill.LISTENING, "Dinle ve anlamı seç", "Cümle ne anlatıyor?", "", listOf("Esprisini tamamen ifadesiz bir yüzle yaptı.", "Nüktedan yanıtı eleştirmenleri etkisiz bıraktı.", "Manşette zekice bir kelime oyunu gizli."), listOf("Nüktedan yanıtı eleştirmenleri etkisiz bıraktı."), "Söylenen cümle: Her witty reply disarmed the critics.", "Her witty reply disarmed the critics.", null),
                LearningExercise("c2v8e10", Skill.READING, "Cümleyi oku ve doğru anlamı seç", "Okuduğun cümle ne anlatıyor?", "The review was clearly tongue-in-cheek.", listOf("Buna aksilik demek durumu hafife almaktı.", "Nüktedan yanıtı eleştirmenleri etkisiz bıraktı.", "İnceleme açıkça şakayla karışıktı."), listOf("İnceleme açıkça şakayla karışıktı."), "Cümlenin çevirisi: İnceleme açıkça şakayla karışıktı.", null, null))),
            LearningLesson("C2-U8-L3", "Humour & Wordplay — Practice", "Apply the grammar focus, speak and write.", listOf(
                LearningExercise("c2v8e7", Skill.GRAMMAR, "Doğru seçeneği işaretle", "So absurd ___ that nobody laughed at first.", "", listOf("was the claim", "the claim was", "claim was the"), listOf("was the claim"), "So + sıfat başta: devrik yapı.", null, null),
                LearningExercise("c2v8e8", Skill.SPEAKING, "İfadeyi sesli söyle", "Say: Calling it a setback was an understatement.", "", listOf(), listOf("Calling it a setback was an understatement."), "Türkçesi: Buna aksilik demek durumu hafife almaktı.", "Calling it a setback was an understatement.", "Calling it a setback was an understatement."),
                LearningExercise("c2v8e9", Skill.WRITING, "Cümleyi İngilizce yaz", "İngilizcesi: Esprisini tamamen ifadesiz bir yüzle yaptı.", "", listOf(), listOf("He delivered the joke completely deadpan."), "Örnek yanıt: He delivered the joke completely deadpan.", null, "He delivered the joke completely deadpan."))))),
        LearningUnit("C2-U9", "Formal & Archaic Language", "Decode legal, ceremonial and archaic English.", listOf(
            LearningLesson("C2-U9-L1", "Formal & Archaic Language — Words", "Recognize key vocabulary for this topic.", listOf(
                LearningExercise("c2v9e1", Skill.VOCABULARY, "Doğru anlamı seç", "'notwithstanding' ne anlama gelir?", "", listOf("rağmen", "bundan böyle", "adı geçen"), listOf("rağmen"), "Notwithstanding the objections, the act passed. — İtirazlara rağmen yasa kabul edildi.", null, null),
                LearningExercise("c2v9e2", Skill.VOCABULARY, "Doğru anlamı seç", "'henceforth' ne anlama gelir?", "", listOf("içinde", "usulünce", "bundan böyle"), listOf("bundan böyle"), "Henceforth, all requests go through the portal. — Bundan böyle tüm talepler portaldan iletilecek.", null, null),
                LearningExercise("c2v9e3", Skill.VOCABULARY, "Doğru anlamı seç", "'therein' ne anlama gelir?", "", listOf("rağmen", "içinde", "adı geçen"), listOf("içinde"), "See the appendix and the tables therein. — Eke ve içindeki tablolara bakınız.", null, null))),
            LearningLesson("C2-U9-L2", "Formal & Archaic Language — In Use", "Use the new words in real sentences and listening.", listOf(
                LearningExercise("c2v9e4", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "___ the objections, the act passed.", "", listOf("henceforth", "therein", "Notwithstanding"), listOf("Notwithstanding"), "Doğru cümle: Notwithstanding the objections, the act passed. — İtirazlara rağmen yasa kabul edildi.", null, null),
                LearningExercise("c2v9e5", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "The ___ parties signed below.", "", listOf("notwithstanding", "aforementioned", "duly"), listOf("aforementioned"), "Doğru cümle: The aforementioned parties signed below. — Adı geçen taraflar aşağıda imzaladı.", null, null),
                LearningExercise("c2v9e6", Skill.LISTENING, "Dinle ve anlamı seç", "Cümle ne anlatıyor?", "", listOf("Tebligat usulünce yapıldı.", "İtirazlara rağmen yasa kabul edildi.", "Eke ve içindeki tablolara bakınız."), listOf("Tebligat usulünce yapıldı."), "Söylenen cümle: The notice was duly delivered.", "The notice was duly delivered.", null),
                LearningExercise("c2v9e10", Skill.READING, "Cümleyi oku ve doğru anlamı seç", "Okuduğun cümle ne anlatıyor?", "The aforementioned parties signed below.", listOf("Tebligat usulünce yapıldı.", "Adı geçen taraflar aşağıda imzaladı.", "Bundan böyle tüm talepler portaldan iletilecek."), listOf("Adı geçen taraflar aşağıda imzaladı."), "Cümlenin çevirisi: Adı geçen taraflar aşağıda imzaladı.", null, null))),
            LearningLesson("C2-U9-L3", "Formal & Archaic Language — Practice", "Apply the grammar focus, speak and write.", listOf(
                LearningExercise("c2v9e7", Skill.GRAMMAR, "Aksi belirtilmedikçe anlamını koruyan bağlacı seç", "The parties agree, ___ stated otherwise, to arbitration.", "", listOf("unless", "if", "though"), listOf("unless"), "Unless stated otherwise = aksi belirtilmedikçe. If stated otherwise ters koşulu kurar; though stated otherwise taviz ilişkisidir. Bunlar hedef anlamı aynı biçimde aktarmaz.", null, null),
                LearningExercise("c2v9e8", Skill.SPEAKING, "İfadeyi sesli söyle", "Say: Henceforth, all requests go through the portal.", "", listOf(), listOf("Henceforth, all requests go through the portal."), "Türkçesi: Bundan böyle tüm talepler portaldan iletilecek.", "Henceforth, all requests go through the portal.", "Henceforth, all requests go through the portal."),
                LearningExercise("c2v9e9", Skill.WRITING, "Cümleyi İngilizce yaz", "İngilizcesi: Eke ve içindeki tablolara bakınız.", "", listOf(), listOf("See the appendix and the tables therein."), "Örnek yanıt: See the appendix and the tables therein.", null, "See the appendix and the tables therein."))))),
        LearningUnit("C2-U10", "Scientific Prose", "Read dense scientific writing fluently.", listOf(
            LearningLesson("C2-U10-L1", "Scientific Prose — Words", "Recognize key vocabulary for this topic.", listOf(
                LearningExercise("c2v10e1", Skill.VOCABULARY, "Doğru anlamı seç", "'methodology' ne anlama gelir?", "", listOf("tekrarlamak", "zayıflatmak", "yöntem bilimi"), listOf("yöntem bilimi"), "The methodology section lacks detail. — Yöntem bölümü ayrıntıdan yoksun.", null, null),
                LearningExercise("c2v10e2", Skill.VOCABULARY, "Doğru anlamı seç", "'replicate' ne anlama gelir?", "", listOf("sağlam", "tekrarlamak", "karıştırıcı etken"), listOf("tekrarlamak"), "Two labs failed to replicate the effect. — İki laboratuvar etkiyi tekrarlayamadı.", null, null),
                LearningExercise("c2v10e3", Skill.VOCABULARY, "Doğru anlamı seç", "'confound' ne anlama gelir?", "", listOf("karıştırıcı etken", "zayıflatmak", "yöntem bilimi"), listOf("karıştırıcı etken"), "Age was an obvious confound in the study. — Yaş, çalışmada bariz bir karıştırıcı etkendi.", null, null))),
            LearningLesson("C2-U10-L2", "Scientific Prose — In Use", "Use the new words in real sentences and listening.", listOf(
                LearningExercise("c2v10e4", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "The ___ section lacks detail.", "", listOf("confound", "methodology", "replicate"), listOf("methodology"), "Doğru cümle: The methodology section lacks detail. — Yöntem bölümü ayrıntıdan yoksun.", null, null),
                LearningExercise("c2v10e5", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "Controls ___d the observed effect.", "", listOf("attenuate", "robust", "methodology"), listOf("attenuate"), "Doğru cümle: Controls attenuated the observed effect. — Kontroller gözlenen etkiyi zayıflattı.", null, null),
                LearningExercise("c2v10e6", Skill.LISTENING, "Dinle ve anlamı seç", "Cümle ne anlatıyor?", "", listOf("Yöntem bölümü ayrıntıdan yoksun.", "Yaş, çalışmada bariz bir karıştırıcı etkendi.", "İlişki tüm modellerde sağlam kaldı."), listOf("İlişki tüm modellerde sağlam kaldı."), "Söylenen cümle: The association remained robust across models.", "The association remained robust across models.", null),
                LearningExercise("c2v10e10", Skill.READING, "Cümleyi oku ve doğru anlamı seç", "Okuduğun cümle ne anlatıyor?", "Controls attenuated the observed effect.", listOf("Kontroller gözlenen etkiyi zayıflattı.", "İki laboratuvar etkiyi tekrarlayamadı.", "İlişki tüm modellerde sağlam kaldı."), listOf("Kontroller gözlenen etkiyi zayıflattı."), "Cümlenin çevirisi: Kontroller gözlenen etkiyi zayıflattı.", null, null))),
            LearningLesson("C2-U10-L3", "Scientific Prose — Practice", "Apply the grammar focus, speak and write.", listOf(
                LearningExercise("c2v10e7", Skill.GRAMMAR, "Doğru seçeneği işaretle", "The data suggest, ___ prove, a causal link.", "", listOf("rather than", "instead", "more than"), listOf("rather than"), "Karşıtlık kalıbı: suggest rather than prove.", null, null),
                LearningExercise("c2v10e8", Skill.SPEAKING, "İfadeyi sesli söyle", "Say: Two labs failed to replicate the effect.", "", listOf(), listOf("Two labs failed to replicate the effect."), "Türkçesi: İki laboratuvar etkiyi tekrarlayamadı.", "Two labs failed to replicate the effect.", "Two labs failed to replicate the effect."),
                LearningExercise("c2v10e9", Skill.WRITING, "Cümleyi İngilizce yaz", "İngilizcesi: Yaş, çalışmada bariz bir karıştırıcı etkendi.", "", listOf(), listOf("Age was an obvious confound in the study."), "Örnek yanıt: Age was an obvious confound in the study.", null, "Age was an obvious confound in the study."))))),
        LearningUnit("C2-U11", "Media Criticism", "Deconstruct framing, spin and agenda.", listOf(
            LearningLesson("C2-U11-L1", "Media Criticism — Words", "Recognize key vocabulary for this topic.", listOf(
                LearningExercise("c2v11e1", Skill.VOCABULARY, "Doğru anlamı seç", "'framing' ne anlama gelir?", "", listOf("köşe yazısı", "çerçeveleme", "yönlendirme"), listOf("çerçeveleme"), "The framing of the story favours one side. — Haberin çerçevelenişi bir tarafı kayırıyor.", null, null),
                LearningExercise("c2v11e2", Skill.VOCABULARY, "Doğru anlamı seç", "'spin' ne anlama gelir?", "", listOf("yönlendirme", "sansasyonculuk", "düzeltme/geri çekme"), listOf("yönlendirme"), "The statement was pure political spin. — Açıklama düpedüz siyasi yönlendirmeydi.", null, null),
                LearningExercise("c2v11e3", Skill.VOCABULARY, "Doğru anlamı seç", "'sensationalism' ne anlama gelir?", "", listOf("köşe yazısı", "çerçeveleme", "sansasyonculuk"), listOf("sansasyonculuk"), "Sensationalism sells but erodes trust. — Sansasyonculuk satar ama güveni aşındırır.", null, null))),
            LearningLesson("C2-U11-L2", "Media Criticism — In Use", "Use the new words in real sentences and listening.", listOf(
                LearningExercise("c2v11e4", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "The ___ of the story favours one side.", "", listOf("framing", "spin", "sensationalism"), listOf("framing"), "Doğru cümle: The framing of the story favours one side. — Haberin çerçevelenişi bir tarafı kayırıyor.", null, null),
                LearningExercise("c2v11e5", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "Her ___ sparked a national debate.", "", listOf("retraction", "framing", "op-ed"), listOf("op-ed"), "Doğru cümle: Her op-ed sparked a national debate. — Köşe yazısı ülke çapında tartışma başlattı.", null, null),
                LearningExercise("c2v11e6", Skill.LISTENING, "Dinle ve anlamı seç", "Cümle ne anlatıyor?", "", listOf("Sansasyonculuk satar ama güveni aşındırır.", "Gazete tam bir düzeltme yayımladı.", "Haberin çerçevelenişi bir tarafı kayırıyor."), listOf("Gazete tam bir düzeltme yayımladı."), "Söylenen cümle: The paper issued a full retraction.", "The paper issued a full retraction.", null),
                LearningExercise("c2v11e10", Skill.READING, "Cümleyi oku ve doğru anlamı seç", "Okuduğun cümle ne anlatıyor?", "Her op-ed sparked a national debate.", listOf("Açıklama düpedüz siyasi yönlendirmeydi.", "Gazete tam bir düzeltme yayımladı.", "Köşe yazısı ülke çapında tartışma başlattı."), listOf("Köşe yazısı ülke çapında tartışma başlattı."), "Cümlenin çevirisi: Köşe yazısı ülke çapında tartışma başlattı.", null, null))),
            LearningLesson("C2-U11-L3", "Media Criticism — Practice", "Apply the grammar focus, speak and write.", listOf(
                LearningExercise("c2v11e7", Skill.GRAMMAR, "Seldom ile doğru devrik edilgen dizilişi seç", "Seldom ___ as prominently as the original error.", "", listOf("is a correction placed", "a correction is placed", "is placed a correction"), listOf("is a correction placed"), "Seldom başta olduğunda is özneden önce gelir, fakat placed özneden sonra kalır: Seldom is a correction placed... Is placed a correction bu yapının doğru dizilişi değildir.", null, null),
                LearningExercise("c2v11e8", Skill.SPEAKING, "İfadeyi sesli söyle", "Say: The statement was pure political spin.", "", listOf(), listOf("The statement was pure political spin."), "Türkçesi: Açıklama düpedüz siyasi yönlendirmeydi.", "The statement was pure political spin.", "The statement was pure political spin."),
                LearningExercise("c2v11e9", Skill.WRITING, "Cümleyi İngilizce yaz", "İngilizcesi: Sansasyonculuk satar ama güveni aşındırır.", "", listOf(), listOf("Sensationalism sells but erodes trust."), "Örnek yanıt: Sensationalism sells but erodes trust.", null, "Sensationalism sells but erodes trust."))))),
        LearningUnit("C2-U12", "Cultural Allusion", "Recognize references from history and literature.", listOf(
            LearningLesson("C2-U12-L1", "Cultural Allusion — Words", "Recognize key vocabulary for this topic.", listOf(
                LearningExercise("c2v12e1", Skill.VOCABULARY, "Doğru anlamı seç", "'Pyrrhic victory' ne anlama gelir?", "", listOf("zararı faydasından çok zafer", "zayıf nokta", "Orwellvari"), listOf("zararı faydasından çok zafer"), "Winning the case was a Pyrrhic victory. — Davayı kazanmak zararı ağır bir zaferdi.", null, null),
                LearningExercise("c2v12e2", Skill.VOCABULARY, "Doğru anlamı seç", "'Achilles heel' ne anlama gelir?", "", listOf("kısır döngü", "uzun serüven", "zayıf nokta"), listOf("zayıf nokta"), "Logistics proved the plan's Achilles heel. — Lojistik, planın zayıf noktası çıktı.", null, null),
                LearningExercise("c2v12e3", Skill.VOCABULARY, "Doğru anlamı seç", "'catch-22' ne anlama gelir?", "", listOf("zararı faydasından çok zafer", "kısır döngü", "Orwellvari"), listOf("kısır döngü"), "Needing experience to get experience is a catch-22. — Deneyim için deneyim istemek tam bir kısır döngü.", null, null))),
            LearningLesson("C2-U12-L2", "Cultural Allusion — In Use", "Use the new words in real sentences and listening.", listOf(
                LearningExercise("c2v12e4", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "Winning the case was a ___.", "", listOf("Achilles heel", "catch-22", "Pyrrhic victory"), listOf("Pyrrhic victory"), "Doğru cümle: Winning the case was a Pyrrhic victory. — Davayı kazanmak zararı ağır bir zaferdi.", null, null),
                LearningExercise("c2v12e5", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "Critics called the law ___.", "", listOf("Pyrrhic victory", "Orwellian", "odyssey"), listOf("Orwellian"), "Doğru cümle: Critics called the law Orwellian. — Eleştirmenler yasayı Orwellvari buldu.", null, null),
                LearningExercise("c2v12e6", Skill.LISTENING, "Dinle ve anlamı seç", "Cümle ne anlatıyor?", "", listOf("Girişimin yolculuğu on yıllık bir serüvendi.", "Davayı kazanmak zararı ağır bir zaferdi.", "Deneyim için deneyim istemek tam bir kısır döngü."), listOf("Girişimin yolculuğu on yıllık bir serüvendi."), "Söylenen cümle: The startup's journey was a ten-year odyssey.", "The startup's journey was a ten-year odyssey.", null),
                LearningExercise("c2v12e10", Skill.READING, "Cümleyi oku ve doğru anlamı seç", "Okuduğun cümle ne anlatıyor?", "Critics called the law Orwellian.", listOf("Girişimin yolculuğu on yıllık bir serüvendi.", "Eleştirmenler yasayı Orwellvari buldu.", "Lojistik, planın zayıf noktası çıktı."), listOf("Eleştirmenler yasayı Orwellvari buldu."), "Cümlenin çevirisi: Eleştirmenler yasayı Orwellvari buldu.", null, null))),
            LearningLesson("C2-U12-L3", "Cultural Allusion — Practice", "Apply the grammar focus, speak and write.", listOf(
                LearningExercise("c2v12e7", Skill.GRAMMAR, "Geçmiş anlatıda Such was ... that yapısını tamamla", "Such ___ the outcry that the plan was shelved.", "", listOf("was", "is", "were"), listOf("was"), "Geçmiş olay was shelved ile anlatılır. Such was the outcry tekil özneyle geçmişte devrik vurgu kurar; were sayı uyumunu, is hedef geçmiş zaman ilişkisini karşılamaz.", null, null),
                LearningExercise("c2v12e8", Skill.SPEAKING, "İfadeyi sesli söyle", "Say: Logistics proved the plan's Achilles heel.", "", listOf(), listOf("Logistics proved the plan's Achilles heel."), "Türkçesi: Lojistik, planın zayıf noktası çıktı.", "Logistics proved the plan's Achilles heel.", "Logistics proved the plan's Achilles heel."),
                LearningExercise("c2v12e9", Skill.WRITING, "Cümleyi İngilizce yaz", "İngilizcesi: Deneyim için deneyim istemek tam bir kısır döngü.", "", listOf(), listOf("Needing experience to get experience is a catch-22."), "Örnek yanıt: Needing experience to get experience is a catch-22.", null, "Needing experience to get experience is a catch-22."))))))
}
