package com.linguapro.android

/** Hacim genişletme içerik paketi: A2 seviyesi (12 ünite, 36 ders). Otomatik derlenmiş, elle küratörlü banka. */
object CourseVolumeA2 {
    val units: List<LearningUnit> = listOf(
        LearningUnit("A2-U13", "Shopping & Prices", "Ask about prices and sizes while shopping.", listOf(
            LearningLesson("A2-U13-L1", "Shopping & Prices — Words", "Recognize key vocabulary for this topic.", listOf(
                LearningExercise("a2v13e1", Skill.VOCABULARY, "Doğru anlamı seç", "'price' ne anlama gelir?", "", listOf("pahalı", "beden", "fiyat"), listOf("fiyat"), "What is the price of this bag? — Bu çantanın fiyatı ne?", null, null),
                LearningExercise("a2v13e2", Skill.VOCABULARY, "Doğru anlamı seç", "'expensive' ne anlama gelir?", "", listOf("müşteri", "pahalı", "ucuz"), listOf("pahalı"), "This coat is too expensive. — Bu palto çok pahalı.", null, null),
                LearningExercise("a2v13e3", Skill.VOCABULARY, "Doğru anlamı seç", "'cheap' ne anlama gelir?", "", listOf("ucuz", "beden", "fiyat"), listOf("ucuz"), "The market is cheaper than the mall. — Pazar alışveriş merkezinden daha ucuz.", null, null))),
            LearningLesson("A2-U13-L2", "Shopping & Prices — In Use", "Use the new words in real sentences and listening.", listOf(
                LearningExercise("a2v13e4", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "What is the ___ of this bag?", "", listOf("cheap", "price", "expensive"), listOf("price"), "Doğru cümle: What is the price of this bag? — Bu çantanın fiyatı ne?", null, null),
                LearningExercise("a2v13e5", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "Do you have this in a small ___?", "", listOf("size", "customer", "price"), listOf("size"), "Doğru cümle: Do you have this in a small size? — Bunun küçük bedeni var mı?", null, null),
                LearningExercise("a2v13e6", Skill.LISTENING, "Dinle ve anlamı seç", "Cümle ne anlatıyor?", "", listOf("Bu çantanın fiyatı ne?", "Pazar alışveriş merkezinden daha ucuz.", "Dükkan müşteriyle doluydu."), listOf("Dükkan müşteriyle doluydu."), "Söylenen cümle: The shop was full of customers.", "The shop was full of customers.", null),
                LearningExercise("a2v13e10", Skill.READING, "Cümleyi oku ve doğru anlamı seç", "Okuduğun cümle ne anlatıyor?", "Do you have this in a small size?", listOf("Bunun küçük bedeni var mı?", "Bu palto çok pahalı.", "Dükkan müşteriyle doluydu."), listOf("Bunun küçük bedeni var mı?"), "Cümlenin çevirisi: Bunun küçük bedeni var mı?", null, null))),
            LearningLesson("A2-U13-L3", "Shopping & Prices — Practice", "Apply the grammar focus, speak and write.", listOf(
                LearningExercise("a2v13e7", Skill.GRAMMAR, "Doğru seçeneği işaretle", "This phone is ___ than that one.", "", listOf("cheaper", "cheapest", "more cheap"), listOf("cheaper"), "Kısa sıfatlarda karşılaştırma -er ile yapılır.", null, null),
                LearningExercise("a2v13e8", Skill.SPEAKING, "İfadeyi sesli söyle", "Say: This coat is too expensive.", "", listOf(), listOf("This coat is too expensive."), "Türkçesi: Bu palto çok pahalı.", "This coat is too expensive.", "This coat is too expensive."),
                LearningExercise("a2v13e9", Skill.WRITING, "Cümleyi İngilizce yaz", "İngilizcesi: Pazar alışveriş merkezinden daha ucuz.", "", listOf(), listOf("The market is cheaper than the mall."), "Örnek yanıt: The market is cheaper than the mall.", null, "The market is cheaper than the mall."))))),
        LearningUnit("A2-U14", "At the Restaurant", "Order a meal and ask for the bill.", listOf(
            LearningLesson("A2-U14-L1", "At the Restaurant — Words", "Recognize key vocabulary for this topic.", listOf(
                LearningExercise("a2v14e1", Skill.VOCABULARY, "Doğru anlamı seç", "'menu' ne anlama gelir?", "", listOf("tatlı", "menü", "sipariş vermek"), listOf("menü"), "Can we see the menu, please? — Menüyü görebilir miyiz, lütfen?", null, null),
                LearningExercise("a2v14e2", Skill.VOCABULARY, "Doğru anlamı seç", "'order' ne anlama gelir?", "", listOf("sipariş vermek", "hesap", "garson"), listOf("sipariş vermek"), "Are you ready to order? — Sipariş vermeye hazır mısınız?", null, null),
                LearningExercise("a2v14e3", Skill.VOCABULARY, "Doğru anlamı seç", "'bill' ne anlama gelir?", "", listOf("tatlı", "menü", "hesap"), listOf("hesap"), "Could we have the bill, please? — Hesabı alabilir miyiz, lütfen?", null, null))),
            LearningLesson("A2-U14-L2", "At the Restaurant — In Use", "Use the new words in real sentences and listening.", listOf(
                LearningExercise("a2v14e4", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "Can we see the ___, please?", "", listOf("menu", "order", "bill"), listOf("menu"), "Doğru cümle: Can we see the menu, please? — Menüyü görebilir miyiz, lütfen?", null, null),
                LearningExercise("a2v14e5", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "Would you like a ___?", "", listOf("waiter", "menu", "dessert"), listOf("dessert"), "Doğru cümle: Would you like a dessert? — Tatlı ister misiniz?", null, null),
                LearningExercise("a2v14e6", Skill.LISTENING, "Dinle ve anlamı seç", "Cümle ne anlatıyor?", "", listOf("Hesabı alabilir miyiz, lütfen?", "Garson çorbamızı hızlıca getirdi.", "Menüyü görebilir miyiz, lütfen?"), listOf("Garson çorbamızı hızlıca getirdi."), "Söylenen cümle: The waiter brought our soup quickly.", "The waiter brought our soup quickly.", null),
                LearningExercise("a2v14e10", Skill.READING, "Cümleyi oku ve doğru anlamı seç", "Okuduğun cümle ne anlatıyor?", "Would you like a dessert?", listOf("Sipariş vermeye hazır mısınız?", "Garson çorbamızı hızlıca getirdi.", "Tatlı ister misiniz?"), listOf("Tatlı ister misiniz?"), "Cümlenin çevirisi: Tatlı ister misiniz?", null, null))),
            LearningLesson("A2-U14-L3", "At the Restaurant — Practice", "Apply the grammar focus, speak and write.", listOf(
                LearningExercise("a2v14e7", Skill.GRAMMAR, "Doğru seçeneği işaretle", "___ you like some tea?", "", listOf("Would", "Do", "Are"), listOf("Would"), "Kibar teklif: Would you like...?", null, null),
                LearningExercise("a2v14e8", Skill.SPEAKING, "İfadeyi sesli söyle", "Say: Are you ready to order?", "", listOf(), listOf("Are you ready to order?"), "Türkçesi: Sipariş vermeye hazır mısınız?", "Are you ready to order?", "Are you ready to order?"),
                LearningExercise("a2v14e9", Skill.WRITING, "Cümleyi İngilizce yaz", "İngilizcesi: Hesabı alabilir miyiz, lütfen?", "", listOf(), listOf("Could we have the bill, please?"), "Örnek yanıt: Could we have the bill, please?", null, "Could we have the bill, please?"))))),
        LearningUnit("A2-U15", "Asking for Directions", "Ask for and understand simple directions.", listOf(
            LearningLesson("A2-U15-L1", "Asking for Directions — Words", "Recognize key vocabulary for this topic.", listOf(
                LearningExercise("a2v15e1", Skill.VOCABULARY, "Doğru anlamı seç", "'turn' ne anlama gelir?", "", listOf("dönmek", "düz", "köprü"), listOf("dönmek"), "Turn left at the bank. — Bankadan sola dön.", null, null),
                LearningExercise("a2v15e2", Skill.VOCABULARY, "Doğru anlamı seç", "'straight' ne anlama gelir?", "", listOf("köşe", "uzak", "düz"), listOf("düz"), "Go straight for two minutes. — İki dakika düz git.", null, null),
                LearningExercise("a2v15e3", Skill.VOCABULARY, "Doğru anlamı seç", "'corner' ne anlama gelir?", "", listOf("dönmek", "köşe", "köprü"), listOf("köşe"), "The cafe is on the corner. — Kafe köşede.", null, null))),
            LearningLesson("A2-U15-L2", "Asking for Directions — In Use", "Use the new words in real sentences and listening.", listOf(
                LearningExercise("a2v15e4", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "___ left at the bank.", "", listOf("straight", "corner", "Turn"), listOf("Turn"), "Doğru cümle: Turn left at the bank. — Bankadan sola dön.", null, null),
                LearningExercise("a2v15e5", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "Cross the ___ and turn right.", "", listOf("turn", "bridge", "far"), listOf("bridge"), "Doğru cümle: Cross the bridge and turn right. — Köprüyü geç ve sağa dön.", null, null),
                LearningExercise("a2v15e6", Skill.LISTENING, "Dinle ve anlamı seç", "Cümle ne anlatıyor?", "", listOf("İstasyon buraya uzak mı?", "Bankadan sola dön.", "Kafe köşede."), listOf("İstasyon buraya uzak mı?"), "Söylenen cümle: Is the station far from here?", "Is the station far from here?", null),
                LearningExercise("a2v15e10", Skill.READING, "Cümleyi oku ve doğru anlamı seç", "Okuduğun cümle ne anlatıyor?", "Cross the bridge and turn right.", listOf("İstasyon buraya uzak mı?", "Köprüyü geç ve sağa dön.", "İki dakika düz git."), listOf("Köprüyü geç ve sağa dön."), "Cümlenin çevirisi: Köprüyü geç ve sağa dön.", null, null))),
            LearningLesson("A2-U15-L3", "Asking for Directions — Practice", "Apply the grammar focus, speak and write.", listOf(
                LearningExercise("a2v15e7", Skill.GRAMMAR, "Doğru seçeneği işaretle", "Excuse me, how ___ I get to the museum?", "", listOf("do", "am", "would"), listOf("do"), "Yol sorma kalıbı: How do I get to...?", null, null),
                LearningExercise("a2v15e8", Skill.SPEAKING, "İfadeyi sesli söyle", "Say: Go straight for two minutes.", "", listOf(), listOf("Go straight for two minutes."), "Türkçesi: İki dakika düz git.", "Go straight for two minutes.", "Go straight for two minutes."),
                LearningExercise("a2v15e9", Skill.WRITING, "Cümleyi İngilizce yaz", "İngilizcesi: Kafe köşede.", "", listOf(), listOf("The cafe is on the corner."), "Örnek yanıt: The cafe is on the corner.", null, "The cafe is on the corner."))))),
        LearningUnit("A2-U16", "Free Time & Hobbies", "Talk about hobbies and how often you do them.", listOf(
            LearningLesson("A2-U16-L1", "Free Time & Hobbies — Words", "Recognize key vocabulary for this topic.", listOf(
                LearningExercise("a2v16e1", Skill.VOCABULARY, "Doğru anlamı seç", "'hobby' ne anlama gelir?", "", listOf("gitar", "satranç", "hobi"), listOf("hobi"), "My favourite hobby is painting. — En sevdiğim hobi resim yapmak.", null, null),
                LearningExercise("a2v16e2", Skill.VOCABULARY, "Doğru anlamı seç", "'guitar' ne anlama gelir?", "", listOf("biriktirmek", "gitar", "fotoğrafçılık"), listOf("gitar"), "He plays the guitar very well. — Çok iyi gitar çalar.", null, null),
                LearningExercise("a2v16e3", Skill.VOCABULARY, "Doğru anlamı seç", "'photography' ne anlama gelir?", "", listOf("fotoğrafçılık", "satranç", "hobi"), listOf("fotoğrafçılık"), "She is interested in photography. — Fotoğrafçılığa ilgi duyuyor.", null, null))),
            LearningLesson("A2-U16-L2", "Free Time & Hobbies — In Use", "Use the new words in real sentences and listening.", listOf(
                LearningExercise("a2v16e4", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "My favourite ___ is painting.", "", listOf("photography", "hobby", "guitar"), listOf("hobby"), "Doğru cümle: My favourite hobby is painting. — En sevdiğim hobi resim yapmak.", null, null),
                LearningExercise("a2v16e5", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "We play ___ on Sundays.", "", listOf("chess", "collect", "hobby"), listOf("chess"), "Doğru cümle: We play chess on Sundays. — Pazarları satranç oynarız.", null, null),
                LearningExercise("a2v16e6", Skill.LISTENING, "Dinle ve anlamı seç", "Cümle ne anlatıyor?", "", listOf("En sevdiğim hobi resim yapmak.", "Fotoğrafçılığa ilgi duyuyor.", "Kardeşim eski para biriktirir."), listOf("Kardeşim eski para biriktirir."), "Söylenen cümle: My brother collects old coins.", "My brother collects old coins.", null),
                LearningExercise("a2v16e10", Skill.READING, "Cümleyi oku ve doğru anlamı seç", "Okuduğun cümle ne anlatıyor?", "We play chess on Sundays.", listOf("Pazarları satranç oynarız.", "Çok iyi gitar çalar.", "Kardeşim eski para biriktirir."), listOf("Pazarları satranç oynarız."), "Cümlenin çevirisi: Pazarları satranç oynarız.", null, null))),
            LearningLesson("A2-U16-L3", "Free Time & Hobbies — Practice", "Apply the grammar focus, speak and write.", listOf(
                LearningExercise("a2v16e7", Skill.GRAMMAR, "Doğru seçeneği işaretle", "I enjoy ___ to music in the evening.", "", listOf("listening", "listen", "to listening"), listOf("listening"), "Enjoy fiilinden sonra -ing gelir.", null, null),
                LearningExercise("a2v16e8", Skill.SPEAKING, "İfadeyi sesli söyle", "Say: He plays the guitar very well.", "", listOf(), listOf("He plays the guitar very well."), "Türkçesi: Çok iyi gitar çalar.", "He plays the guitar very well.", "He plays the guitar very well."),
                LearningExercise("a2v16e9", Skill.WRITING, "Cümleyi İngilizce yaz", "İngilizcesi: Fotoğrafçılığa ilgi duyuyor.", "", listOf(), listOf("She is interested in photography."), "Örnek yanıt: She is interested in photography.", null, "She is interested in photography."))))),
        LearningUnit("A2-U17", "Sports & Exercise", "Describe sports you do and watch.", listOf(
            LearningLesson("A2-U17-L1", "Sports & Exercise — Words", "Recognize key vocabulary for this topic.", listOf(
                LearningExercise("a2v17e1", Skill.VOCABULARY, "Doğru anlamı seç", "'swimming' ne anlama gelir?", "", listOf("antrenman", "yüzme", "maç"), listOf("yüzme"), "Swimming is good for your back. — Yüzme sırtın için iyidir.", null, null),
                LearningExercise("a2v17e2", Skill.VOCABULARY, "Doğru anlamı seç", "'match' ne anlama gelir?", "", listOf("maç", "takım", "spor salonu"), listOf("maç"), "We watched the match together. — Maçı birlikte izledik.", null, null),
                LearningExercise("a2v17e3", Skill.VOCABULARY, "Doğru anlamı seç", "'team' ne anlama gelir?", "", listOf("antrenman", "yüzme", "takım"), listOf("takım"), "Our team won on Saturday. — Takımımız cumartesi kazandı.", null, null))),
            LearningLesson("A2-U17-L2", "Sports & Exercise — In Use", "Use the new words in real sentences and listening.", listOf(
                LearningExercise("a2v17e4", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "___ is good for your back.", "", listOf("Swimming", "match", "team"), listOf("Swimming"), "Doğru cümle: Swimming is good for your back. — Yüzme sırtın için iyidir.", null, null),
                LearningExercise("a2v17e5", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "___ starts at six.", "", listOf("gym", "swimming", "Training"), listOf("Training"), "Doğru cümle: Training starts at six. — Antrenman altıda başlar.", null, null),
                LearningExercise("a2v17e6", Skill.LISTENING, "Dinle ve anlamı seç", "Cümle ne anlatıyor?", "", listOf("Takımımız cumartesi kazandı.", "Haftada iki kez spor salonuna gider.", "Yüzme sırtın için iyidir."), listOf("Haftada iki kez spor salonuna gider."), "Söylenen cümle: She goes to the gym twice a week.", "She goes to the gym twice a week.", null),
                LearningExercise("a2v17e10", Skill.READING, "Cümleyi oku ve doğru anlamı seç", "Okuduğun cümle ne anlatıyor?", "Training starts at six.", listOf("Maçı birlikte izledik.", "Haftada iki kez spor salonuna gider.", "Antrenman altıda başlar."), listOf("Antrenman altıda başlar."), "Cümlenin çevirisi: Antrenman altıda başlar.", null, null))),
            LearningLesson("A2-U17-L3", "Sports & Exercise — Practice", "Apply the grammar focus, speak and write.", listOf(
                LearningExercise("a2v17e7", Skill.GRAMMAR, "Doğru seçeneği işaretle", "How ___ do you play tennis?", "", listOf("often", "long", "much"), listOf("often"), "Sıklık sormak için how often kullanılır.", null, null),
                LearningExercise("a2v17e8", Skill.SPEAKING, "İfadeyi sesli söyle", "Say: We watched the match together.", "", listOf(), listOf("We watched the match together."), "Türkçesi: Maçı birlikte izledik.", "We watched the match together.", "We watched the match together."),
                LearningExercise("a2v17e9", Skill.WRITING, "Cümleyi İngilizce yaz", "İngilizcesi: Takımımız cumartesi kazandı.", "", listOf(), listOf("Our team won on Saturday."), "Örnek yanıt: Our team won on Saturday.", null, "Our team won on Saturday."))))),
        LearningUnit("A2-U18", "Holiday Plans", "Make simple plans for a holiday.", listOf(
            LearningLesson("A2-U18-L1", "Holiday Plans — Words", "Recognize key vocabulary for this topic.", listOf(
                LearningExercise("a2v18e1", Skill.VOCABULARY, "Doğru anlamı seç", "'ticket' ne anlama gelir?", "", listOf("bilet", "bagaj", "rezervasyon yapmak"), listOf("bilet"), "I bought the plane tickets online. — Uçak biletlerini internetten aldım.", null, null),
                LearningExercise("a2v18e2", Skill.VOCABULARY, "Doğru anlamı seç", "'luggage' ne anlama gelir?", "", listOf("plaj", "gezi", "bagaj"), listOf("bagaj"), "Your luggage is too heavy. — Bagajın çok ağır.", null, null),
                LearningExercise("a2v18e3", Skill.VOCABULARY, "Doğru anlamı seç", "'beach' ne anlama gelir?", "", listOf("bilet", "plaj", "rezervasyon yapmak"), listOf("plaj"), "The hotel is near the beach. — Otel plaja yakın.", null, null))),
            LearningLesson("A2-U18-L2", "Holiday Plans — In Use", "Use the new words in real sentences and listening.", listOf(
                LearningExercise("a2v18e4", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "I bought the plane ___s online.", "", listOf("luggage", "beach", "ticket"), listOf("ticket"), "Doğru cümle: I bought the plane tickets online. — Uçak biletlerini internetten aldım.", null, null),
                LearningExercise("a2v18e5", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "We ___ed a room for two nights.", "", listOf("ticket", "book", "trip"), listOf("book"), "Doğru cümle: We booked a room for two nights. — İki gecelik oda ayırttık.", null, null),
                LearningExercise("a2v18e6", Skill.LISTENING, "Dinle ve anlamı seç", "Cümle ne anlatıyor?", "", listOf("Adalara yapılan gezi harikaydı.", "Uçak biletlerini internetten aldım.", "Otel plaja yakın."), listOf("Adalara yapılan gezi harikaydı."), "Söylenen cümle: The trip to the islands was great.", "The trip to the islands was great.", null),
                LearningExercise("a2v18e10", Skill.READING, "Cümleyi oku ve doğru anlamı seç", "Okuduğun cümle ne anlatıyor?", "We booked a room for two nights.", listOf("Adalara yapılan gezi harikaydı.", "İki gecelik oda ayırttık.", "Bagajın çok ağır."), listOf("İki gecelik oda ayırttık."), "Cümlenin çevirisi: İki gecelik oda ayırttık.", null, null))),
            LearningLesson("A2-U18-L3", "Holiday Plans — Practice", "Apply the grammar focus, speak and write.", listOf(
                LearningExercise("a2v18e7", Skill.GRAMMAR, "Doğru seçeneği işaretle", "We ___ visit my aunt next weekend.", "", listOf("are going to", "go", "went"), listOf("are going to"), "Planlanan gelecek için be going to kullanılır.", null, null),
                LearningExercise("a2v18e8", Skill.SPEAKING, "İfadeyi sesli söyle", "Say: Your luggage is too heavy.", "", listOf(), listOf("Your luggage is too heavy."), "Türkçesi: Bagajın çok ağır.", "Your luggage is too heavy.", "Your luggage is too heavy."),
                LearningExercise("a2v18e9", Skill.WRITING, "Cümleyi İngilizce yaz", "İngilizcesi: Otel plaja yakın.", "", listOf(), listOf("The hotel is near the beach."), "Örnek yanıt: The hotel is near the beach.", null, "The hotel is near the beach."))))),
        LearningUnit("A2-U19", "Past Experiences", "Tell short stories about the past.", listOf(
            LearningLesson("A2-U19-L1", "Past Experiences — Words", "Recognize key vocabulary for this topic.", listOf(
                LearningExercise("a2v19e1", Skill.VOCABULARY, "Doğru anlamı seç", "'yesterday' ne anlama gelir?", "", listOf("önce", "bulmak", "dün"), listOf("dün"), "Yesterday I stayed at home. — Dün evde kaldım.", null, null),
                LearningExercise("a2v19e2", Skill.VOCABULARY, "Doğru anlamı seç", "'ago' ne anlama gelir?", "", listOf("olmak", "önce", "kaybetmek"), listOf("önce"), "We moved here two years ago. — Buraya iki yıl önce taşındık.", null, null),
                LearningExercise("a2v19e3", Skill.VOCABULARY, "Doğru anlamı seç", "'lose' ne anlama gelir?", "", listOf("kaybetmek", "bulmak", "dün"), listOf("kaybetmek"), "I lost my wallet on the bus. — Cüzdanımı otobüste kaybettim.", null, null))),
            LearningLesson("A2-U19-L2", "Past Experiences — In Use", "Use the new words in real sentences and listening.", listOf(
                LearningExercise("a2v19e4", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "___ I stayed at home.", "", listOf("lose", "Yesterday", "ago"), listOf("Yesterday"), "Doğru cümle: Yesterday I stayed at home. — Dün evde kaldım.", null, null),
                LearningExercise("a2v19e5", Skill.VOCABULARY, "Doğru anlamı seç", "'find' ne anlama gelir?", "", listOf("kaybetmek", "bulmak", "dün"), listOf("bulmak"), "She found a cat in the garden. — Bahçede bir kedi buldu.", null, null),
                LearningExercise("a2v19e6", Skill.LISTENING, "Dinle ve anlamı seç", "Cümle ne anlatıyor?", "", listOf("Dün evde kaldım.", "Cüzdanımı otobüste kaybettim.", "Partide ne oldu?"), listOf("Partide ne oldu?"), "Söylenen cümle: What happened at the party?", "What happened at the party?", null),
                LearningExercise("a2v19e10", Skill.READING, "Cümleyi oku ve doğru anlamı seç", "Okuduğun cümle ne anlatıyor?", "She found a cat in the garden.", listOf("Bahçede bir kedi buldu.", "Buraya iki yıl önce taşındık.", "Partide ne oldu?"), listOf("Bahçede bir kedi buldu."), "Cümlenin çevirisi: Bahçede bir kedi buldu.", null, null))),
            LearningLesson("A2-U19-L3", "Past Experiences — Practice", "Apply the grammar focus, speak and write.", listOf(
                LearningExercise("a2v19e7", Skill.GRAMMAR, "Doğru seçeneği işaretle", "They ___ to the cinema last night.", "", listOf("went", "go", "gone"), listOf("went"), "Geçmiş zaman: go fiilinin ikinci hali went.", null, null),
                LearningExercise("a2v19e8", Skill.SPEAKING, "İfadeyi sesli söyle", "Say: We moved here two years ago.", "", listOf(), listOf("We moved here two years ago."), "Türkçesi: Buraya iki yıl önce taşındık.", "We moved here two years ago.", "We moved here two years ago."),
                LearningExercise("a2v19e9", Skill.WRITING, "Cümleyi İngilizce yaz", "İngilizcesi: Cüzdanımı otobüste kaybettim.", "", listOf(), listOf("I lost my wallet on the bus."), "Örnek yanıt: I lost my wallet on the bus.", null, "I lost my wallet on the bus."))))),
        LearningUnit("A2-U20", "Housework & Chores", "Talk about daily chores at home.", listOf(
            LearningLesson("A2-U20-L1", "Housework & Chores — Words", "Recognize key vocabulary for this topic.", listOf(
                LearningExercise("a2v20e1", Skill.VOCABULARY, "Doğru anlamı seç", "'clean' ne anlama gelir?", "", listOf("toplamak", "temizlemek", "yıkamak"), listOf("temizlemek"), "I clean my room on Saturdays. — Cumartesileri odamı temizlerim.", null, null),
                LearningExercise("a2v20e2", Skill.VOCABULARY, "Doğru anlamı seç", "'wash' ne anlama gelir?", "", listOf("yıkamak", "ütülemek", "çöp"), listOf("yıkamak"), "He washes the dishes after dinner. — Akşam yemeğinden sonra bulaşıkları yıkar.", null, null),
                LearningExercise("a2v20e3", Skill.VOCABULARY, "Doğru anlamı seç", "'iron' ne anlama gelir?", "", listOf("toplamak", "temizlemek", "ütülemek"), listOf("ütülemek"), "She hates ironing shirts. — Gömlek ütülemekten nefret eder.", null, null))),
            LearningLesson("A2-U20-L2", "Housework & Chores — In Use", "Use the new words in real sentences and listening.", listOf(
                LearningExercise("a2v20e4", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "I ___ my room on Saturdays.", "", listOf("clean", "wash", "iron"), listOf("clean"), "Doğru cümle: I clean my room on Saturdays. — Cumartesileri odamı temizlerim.", null, null),
                LearningExercise("a2v20e5", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "Please ___ your desk.", "", listOf("rubbish", "clean", "tidy"), listOf("tidy"), "Doğru cümle: Please tidy your desk. — Lütfen masanı topla.", null, null),
                LearningExercise("a2v20e6", Skill.LISTENING, "Dinle ve anlamı seç", "Cümle ne anlatıyor?", "", listOf("Gömlek ütülemekten nefret eder.", "Çöpü dışarı çıkarabilir misin?", "Cumartesileri odamı temizlerim."), listOf("Çöpü dışarı çıkarabilir misin?"), "Söylenen cümle: Can you take out the rubbish?", "Can you take out the rubbish?", null),
                LearningExercise("a2v20e10", Skill.READING, "Cümleyi oku ve doğru anlamı seç", "Okuduğun cümle ne anlatıyor?", "Please tidy your desk.", listOf("Akşam yemeğinden sonra bulaşıkları yıkar.", "Çöpü dışarı çıkarabilir misin?", "Lütfen masanı topla."), listOf("Lütfen masanı topla."), "Cümlenin çevirisi: Lütfen masanı topla.", null, null))),
            LearningLesson("A2-U20-L3", "Housework & Chores — Practice", "Apply the grammar focus, speak and write.", listOf(
                LearningExercise("a2v20e7", Skill.GRAMMAR, "Doğru seçeneği işaretle", "You ___ clean your room today, it is very untidy.", "", listOf("have to", "can", "would"), listOf("have to"), "Zorunluluk için have to kullanılır.", null, null),
                LearningExercise("a2v20e8", Skill.SPEAKING, "İfadeyi sesli söyle", "Say: He washes the dishes after dinner.", "", listOf(), listOf("He washes the dishes after dinner."), "Türkçesi: Akşam yemeğinden sonra bulaşıkları yıkar.", "He washes the dishes after dinner.", "He washes the dishes after dinner."),
                LearningExercise("a2v20e9", Skill.WRITING, "Cümleyi İngilizce yaz", "İngilizcesi: Gömlek ütülemekten nefret eder.", "", listOf(), listOf("She hates ironing shirts."), "Örnek yanıt: She hates ironing shirts.", null, "She hates ironing shirts."))))),
        LearningUnit("A2-U21", "Everyday Technology", "Use simple language about phones and computers.", listOf(
            LearningLesson("A2-U21-L1", "Everyday Technology — Words", "Recognize key vocabulary for this topic.", listOf(
                LearningExercise("a2v21e1", Skill.VOCABULARY, "Doğru anlamı seç", "'charge' ne anlama gelir?", "", listOf("şarj etmek", "indirmek", "ekran"), listOf("şarj etmek"), "I need to charge my phone. — Telefonumu şarj etmem gerek.", null, null),
                LearningExercise("a2v21e2", Skill.VOCABULARY, "Doğru anlamı seç", "'download' ne anlama gelir?", "", listOf("şifre", "mesaj", "indirmek"), listOf("indirmek"), "You can download the app for free. — Uygulamayı ücretsiz indirebilirsin.", null, null),
                LearningExercise("a2v21e3", Skill.VOCABULARY, "Doğru anlamı seç", "'password' ne anlama gelir?", "", listOf("şarj etmek", "şifre", "ekran"), listOf("şifre"), "I forgot my password again. — Şifremi yine unuttum.", null, null))),
            LearningLesson("A2-U21-L2", "Everyday Technology — In Use", "Use the new words in real sentences and listening.", listOf(
                LearningExercise("a2v21e4", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "I need to ___ my phone.", "", listOf("download", "password", "charge"), listOf("charge"), "Doğru cümle: I need to charge my phone. — Telefonumu şarj etmem gerek.", null, null),
                LearningExercise("a2v21e5", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "The ___ of my tablet is broken.", "", listOf("charge", "screen", "message"), listOf("screen"), "Doğru cümle: The screen of my tablet is broken. — Tabletimin ekranı kırık.", null, null),
                LearningExercise("a2v21e6", Skill.LISTENING, "Dinle ve anlamı seç", "Cümle ne anlatıyor?", "", listOf("Varınca bana mesaj at.", "Telefonumu şarj etmem gerek.", "Şifremi yine unuttum."), listOf("Varınca bana mesaj at."), "Söylenen cümle: Send me a message when you arrive.", "Send me a message when you arrive.", null),
                LearningExercise("a2v21e10", Skill.READING, "Cümleyi oku ve doğru anlamı seç", "Okuduğun cümle ne anlatıyor?", "The screen of my tablet is broken.", listOf("Varınca bana mesaj at.", "Tabletimin ekranı kırık.", "Uygulamayı ücretsiz indirebilirsin."), listOf("Tabletimin ekranı kırık."), "Cümlenin çevirisi: Tabletimin ekranı kırık.", null, null))),
            LearningLesson("A2-U21-L3", "Everyday Technology — Practice", "Apply the grammar focus, speak and write.", listOf(
                LearningExercise("a2v21e7", Skill.GRAMMAR, "Doğru seçeneği işaretle", "My laptop is slow ___ my old one was faster.", "", listOf("but", "because", "so"), listOf("but"), "Zıt iki fikri but bağlar.", null, null),
                LearningExercise("a2v21e8", Skill.SPEAKING, "İfadeyi sesli söyle", "Say: You can download the app for free.", "", listOf(), listOf("You can download the app for free."), "Türkçesi: Uygulamayı ücretsiz indirebilirsin.", "You can download the app for free.", "You can download the app for free."),
                LearningExercise("a2v21e9", Skill.WRITING, "Cümleyi İngilizce yaz", "İngilizcesi: Şifremi yine unuttum.", "", listOf(), listOf("I forgot my password again."), "Örnek yanıt: I forgot my password again.", null, "I forgot my password again."))))),
        LearningUnit("A2-U22", "Appointments & Dates", "Make and change simple appointments.", listOf(
            LearningLesson("A2-U22-L1", "Appointments & Dates — Words", "Recognize key vocabulary for this topic.", listOf(
                LearningExercise("a2v22e1", Skill.VOCABULARY, "Doğru anlamı seç", "'appointment' ne anlama gelir?", "", listOf("iptal etmek", "meşgul", "randevu"), listOf("randevu"), "I have a dentist appointment at three. — Üçte diş hekimi randevum var.", null, null),
                LearningExercise("a2v22e2", Skill.VOCABULARY, "Doğru anlamı seç", "'cancel' ne anlama gelir?", "", listOf("müsait", "iptal etmek", "erken"), listOf("iptal etmek"), "I had to cancel the meeting. — Toplantıyı iptal etmek zorunda kaldım.", null, null),
                LearningExercise("a2v22e3", Skill.VOCABULARY, "Doğru anlamı seç", "'early' ne anlama gelir?", "", listOf("erken", "meşgul", "randevu"), listOf("erken"), "Can we meet a bit earlier? — Biraz daha erken buluşabilir miyiz?", null, null))),
            LearningLesson("A2-U22-L2", "Appointments & Dates — In Use", "Use the new words in real sentences and listening.", listOf(
                LearningExercise("a2v22e4", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "I have a dentist ___ at three.", "", listOf("early", "appointment", "cancel"), listOf("appointment"), "Doğru cümle: I have a dentist appointment at three. — Üçte diş hekimi randevum var.", null, null),
                LearningExercise("a2v22e5", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "I am ___ on Friday morning.", "", listOf("busy", "free", "appointment"), listOf("busy"), "Doğru cümle: I am busy on Friday morning. — Cuma sabahı meşgulüm.", null, null),
                LearningExercise("a2v22e6", Skill.LISTENING, "Dinle ve anlamı seç", "Cümle ne anlatıyor?", "", listOf("Üçte diş hekimi randevum var.", "Biraz daha erken buluşabilir miyiz?", "Yarın öğleden sonra müsait misin?"), listOf("Yarın öğleden sonra müsait misin?"), "Söylenen cümle: Are you free tomorrow afternoon?", "Are you free tomorrow afternoon?", null),
                LearningExercise("a2v22e10", Skill.READING, "Cümleyi oku ve doğru anlamı seç", "Okuduğun cümle ne anlatıyor?", "I am busy on Friday morning.", listOf("Cuma sabahı meşgulüm.", "Toplantıyı iptal etmek zorunda kaldım.", "Yarın öğleden sonra müsait misin?"), listOf("Cuma sabahı meşgulüm."), "Cümlenin çevirisi: Cuma sabahı meşgulüm.", null, null))),
            LearningLesson("A2-U22-L3", "Appointments & Dates — Practice", "Apply the grammar focus, speak and write.", listOf(
                LearningExercise("a2v22e7", Skill.GRAMMAR, "Doğru seçeneği işaretle", "___ we meet at five instead of four?", "", listOf("Could", "Must", "Did"), listOf("Could"), "Kibar öneri ve rica için could kullanılır.", null, null),
                LearningExercise("a2v22e8", Skill.SPEAKING, "İfadeyi sesli söyle", "Say: I had to cancel the meeting.", "", listOf(), listOf("I had to cancel the meeting."), "Türkçesi: Toplantıyı iptal etmek zorunda kaldım.", "I had to cancel the meeting.", "I had to cancel the meeting."),
                LearningExercise("a2v22e9", Skill.WRITING, "Cümleyi İngilizce yaz", "İngilizcesi: Biraz daha erken buluşabilir miyiz?", "", listOf(), listOf("Can we meet a bit earlier?"), "Örnek yanıt: Can we meet a bit earlier?", null, "Can we meet a bit earlier?"))))),
        LearningUnit("A2-U23", "Feelings & Moods", "Say how you feel and ask about others.", listOf(
            LearningLesson("A2-U23-L1", "Feelings & Moods — Words", "Recognize key vocabulary for this topic.", listOf(
                LearningExercise("a2v23e1", Skill.VOCABULARY, "Doğru anlamı seç", "'tired' ne anlama gelir?", "", listOf("şaşırmış", "yorgun", "heyecanlı"), listOf("yorgun"), "I am tired after work. — İşten sonra yorgunum.", null, null),
                LearningExercise("a2v23e2", Skill.VOCABULARY, "Doğru anlamı seç", "'excited' ne anlama gelir?", "", listOf("heyecanlı", "endişeli", "gururlu"), listOf("heyecanlı"), "She is excited about the trip. — Gezi için heyecanlı.", null, null),
                LearningExercise("a2v23e3", Skill.VOCABULARY, "Doğru anlamı seç", "'worried' ne anlama gelir?", "", listOf("şaşırmış", "yorgun", "endişeli"), listOf("endişeli"), "He is worried about the exam. — Sınav için endişeli.", null, null))),
            LearningLesson("A2-U23-L2", "Feelings & Moods — In Use", "Use the new words in real sentences and listening.", listOf(
                LearningExercise("a2v23e4", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "I am ___ after work.", "", listOf("tired", "excited", "worried"), listOf("tired"), "Doğru cümle: I am tired after work. — İşten sonra yorgunum.", null, null),
                LearningExercise("a2v23e5", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "We were ___ by the news.", "", listOf("proud", "tired", "surprised"), listOf("surprised"), "Doğru cümle: We were surprised by the news. — Habere şaşırdık.", null, null),
                LearningExercise("a2v23e6", Skill.LISTENING, "Dinle ve anlamı seç", "Cümle ne anlatıyor?", "", listOf("Sınav için endişeli.", "Kızlarıyla gurur duyuyorlar.", "İşten sonra yorgunum."), listOf("Kızlarıyla gurur duyuyorlar."), "Söylenen cümle: They are proud of their daughter.", "They are proud of their daughter.", null),
                LearningExercise("a2v23e10", Skill.READING, "Cümleyi oku ve doğru anlamı seç", "Okuduğun cümle ne anlatıyor?", "We were surprised by the news.", listOf("Gezi için heyecanlı.", "Kızlarıyla gurur duyuyorlar.", "Habere şaşırdık."), listOf("Habere şaşırdık."), "Cümlenin çevirisi: Habere şaşırdık.", null, null))),
            LearningLesson("A2-U23-L3", "Feelings & Moods — Practice", "Apply the grammar focus, speak and write.", listOf(
                LearningExercise("a2v23e7", Skill.GRAMMAR, "Doğru seçeneği işaretle", "Why ___ you sad yesterday?", "", listOf("were", "are", "did"), listOf("were"), "Geçmişte durum: you ile were kullanılır.", null, null),
                LearningExercise("a2v23e8", Skill.SPEAKING, "İfadeyi sesli söyle", "Say: She is excited about the trip.", "", listOf(), listOf("She is excited about the trip."), "Türkçesi: Gezi için heyecanlı.", "She is excited about the trip.", "She is excited about the trip."),
                LearningExercise("a2v23e9", Skill.WRITING, "Cümleyi İngilizce yaz", "İngilizcesi: Sınav için endişeli.", "", listOf(), listOf("He is worried about the exam."), "Örnek yanıt: He is worried about the exam.", null, "He is worried about the exam."))))),
        LearningUnit("A2-U24", "Nature & Animals", "Describe nature, pets and simple facts.", listOf(
            LearningLesson("A2-U24-L1", "Nature & Animals — Words", "Recognize key vocabulary for this topic.", listOf(
                LearningExercise("a2v24e1", Skill.VOCABULARY, "Doğru anlamı seç", "'forest' ne anlama gelir?", "", listOf("orman", "nehir", "at"), listOf("orman"), "We walked in the forest for hours. — Ormanda saatlerce yürüdük.", null, null),
                LearningExercise("a2v24e2", Skill.VOCABULARY, "Doğru anlamı seç", "'river' ne anlama gelir?", "", listOf("kuş", "dağ", "nehir"), listOf("nehir"), "The river is very clean here. — Nehir burada çok temiz.", null, null),
                LearningExercise("a2v24e3", Skill.VOCABULARY, "Doğru anlamı seç", "'bird' ne anlama gelir?", "", listOf("orman", "kuş", "at"), listOf("kuş"), "A small bird sat on the window. — Küçük bir kuş pencereye kondu.", null, null))),
            LearningLesson("A2-U24-L2", "Nature & Animals — In Use", "Use the new words in real sentences and listening.", listOf(
                LearningExercise("a2v24e4", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "We walked in the ___ for hours.", "", listOf("river", "bird", "forest"), listOf("forest"), "Doğru cümle: We walked in the forest for hours. — Ormanda saatlerce yürüdük.", null, null),
                LearningExercise("a2v24e5", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "My uncle has two ___s.", "", listOf("forest", "horse", "mountain"), listOf("horse"), "Doğru cümle: My uncle has two horses. — Amcamın iki atı var.", null, null),
                LearningExercise("a2v24e6", Skill.LISTENING, "Dinle ve anlamı seç", "Cümle ne anlatıyor?", "", listOf("Dağ karla kaplı.", "Ormanda saatlerce yürüdük.", "Küçük bir kuş pencereye kondu."), listOf("Dağ karla kaplı."), "Söylenen cümle: The mountain is covered with snow.", "The mountain is covered with snow.", null),
                LearningExercise("a2v24e10", Skill.READING, "Cümleyi oku ve doğru anlamı seç", "Okuduğun cümle ne anlatıyor?", "My uncle has two horses.", listOf("Dağ karla kaplı.", "Amcamın iki atı var.", "Nehir burada çok temiz."), listOf("Amcamın iki atı var."), "Cümlenin çevirisi: Amcamın iki atı var.", null, null))),
            LearningLesson("A2-U24-L3", "Nature & Animals — Practice", "Apply the grammar focus, speak and write.", listOf(
                LearningExercise("a2v24e7", Skill.GRAMMAR, "Doğru seçeneği işaretle", "Elephants are ___ than horses.", "", listOf("bigger", "biggest", "more big"), listOf("bigger"), "Kısa sıfatta karşılaştırma: big - bigger.", null, null),
                LearningExercise("a2v24e8", Skill.SPEAKING, "İfadeyi sesli söyle", "Say: The river is very clean here.", "", listOf(), listOf("The river is very clean here."), "Türkçesi: Nehir burada çok temiz.", "The river is very clean here.", "The river is very clean here."),
                LearningExercise("a2v24e9", Skill.WRITING, "Cümleyi İngilizce yaz", "İngilizcesi: Küçük bir kuş pencereye kondu.", "", listOf(), listOf("A small bird sat on the window."), "Örnek yanıt: A small bird sat on the window.", null, "A small bird sat on the window."))))))
}
