package com.linguapro.android

/** Hacim genişletme içerik paketi: B2 seviyesi (12 ünite, 36 ders). Otomatik derlenmiş, elle küratörlü banka. */
object CourseVolumeB2 {
    val units: List<LearningUnit> = listOf(
        LearningUnit("B2-U13", "Project Management", "Plan, delegate and report on projects.", listOf(
            LearningLesson("B2-U13-L1", "Project Management — Words", "Recognize key vocabulary for this topic.", listOf(
                LearningExercise("b2v13e1", Skill.VOCABULARY, "Doğru anlamı seç", "'milestone' ne anlama gelir?", "", listOf("tahsis etmek", "kapsam", "kilometre taşı"), listOf("kilometre taşı"), "We reached the first milestone on time. — İlk kilometre taşına zamanında ulaştık.", null, null),
                LearningExercise("b2v13e2", Skill.VOCABULARY, "Doğru anlamı seç", "'allocate' ne anlama gelir?", "", listOf("sonuç", "tahsis etmek", "paydaş"), listOf("tahsis etmek"), "The budget was allocated to three teams. — Bütçe üç ekibe tahsis edildi.", null, null),
                LearningExercise("b2v13e3", Skill.VOCABULARY, "Doğru anlamı seç", "'stakeholder' ne anlama gelir?", "", listOf("paydaş", "kapsam", "kilometre taşı"), listOf("paydaş"), "All stakeholders approved the plan. — Tüm paydaşlar planı onayladı.", null, null))),
            LearningLesson("B2-U13-L2", "Project Management — In Use", "Use the new words in real sentences and listening.", listOf(
                LearningExercise("b2v13e4", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "We reached the first ___ on time.", "", listOf("stakeholder", "milestone", "allocate"), listOf("milestone"), "Doğru cümle: We reached the first milestone on time. — İlk kilometre taşına zamanında ulaştık.", null, null),
                LearningExercise("b2v13e5", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "The ___ of the project grew quickly.", "", listOf("scope", "outcome", "milestone"), listOf("scope"), "Doğru cümle: The scope of the project grew quickly. — Projenin kapsamı hızla büyüdü.", null, null),
                LearningExercise("b2v13e6", Skill.LISTENING, "Dinle ve anlamı seç", "Cümle ne anlatıyor?", "", listOf("İlk kilometre taşına zamanında ulaştık.", "Tüm paydaşlar planı onayladı.", "Sonuç beklentilerimizi aştı."), listOf("Sonuç beklentilerimizi aştı."), "Söylenen cümle: The outcome exceeded our expectations.", "The outcome exceeded our expectations.", null),
                LearningExercise("b2v13e10", Skill.READING, "Cümleyi oku ve doğru anlamı seç", "Okuduğun cümle ne anlatıyor?", "The scope of the project grew quickly.", listOf("Projenin kapsamı hızla büyüdü.", "Bütçe üç ekibe tahsis edildi.", "Sonuç beklentilerimizi aştı."), listOf("Projenin kapsamı hızla büyüdü."), "Cümlenin çevirisi: Projenin kapsamı hızla büyüdü.", null, null))),
            LearningLesson("B2-U13-L3", "Project Management — Practice", "Apply the grammar focus, speak and write.", listOf(
                LearningExercise("b2v13e7", Skill.GRAMMAR, "Doğru seçeneği işaretle", "Had we started earlier, we ___ the deadline.", "", listOf("would have met", "will meet", "met"), listOf("would have met"), "Üçüncü koşul: geçmişteki hayalî sonuç.", null, null),
                LearningExercise("b2v13e8", Skill.SPEAKING, "İfadeyi sesli söyle", "Say: The budget was allocated to three teams.", "", listOf(), listOf("The budget was allocated to three teams."), "Türkçesi: Bütçe üç ekibe tahsis edildi.", "The budget was allocated to three teams.", "The budget was allocated to three teams."),
                LearningExercise("b2v13e9", Skill.WRITING, "Cümleyi İngilizce yaz", "İngilizcesi: Tüm paydaşlar planı onayladı.", "", listOf(), listOf("All stakeholders approved the plan."), "Örnek yanıt: All stakeholders approved the plan.", null, "All stakeholders approved the plan."))))),
        LearningUnit("B2-U14", "Marketing & Branding", "Discuss campaigns, audiences and brand image.", listOf(
            LearningLesson("B2-U14-L1", "Marketing & Branding — Words", "Recognize key vocabulary for this topic.", listOf(
                LearningExercise("b2v14e1", Skill.VOCABULARY, "Doğru anlamı seç", "'campaign' ne anlama gelir?", "", listOf("piyasaya sürmek", "kampanya", "hedef kitle"), listOf("kampanya"), "The campaign doubled our online sales. — Kampanya çevrim içi satışlarımızı ikiye katladı.", null, null),
                LearningExercise("b2v14e2", Skill.VOCABULARY, "Doğru anlamı seç", "'target audience' ne anlama gelir?", "", listOf("hedef kitle", "marka bilinirliği", "etkileşim"), listOf("hedef kitle"), "Our target audience is young professionals. — Hedef kitlemiz genç profesyoneller.", null, null),
                LearningExercise("b2v14e3", Skill.VOCABULARY, "Doğru anlamı seç", "'brand awareness' ne anlama gelir?", "", listOf("piyasaya sürmek", "kampanya", "marka bilinirliği"), listOf("marka bilinirliği"), "Brand awareness rose after the event. — Etkinlikten sonra marka bilinirliği arttı.", null, null))),
            LearningLesson("B2-U14-L2", "Marketing & Branding — In Use", "Use the new words in real sentences and listening.", listOf(
                LearningExercise("b2v14e4", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "The ___ doubled our online sales.", "", listOf("campaign", "target audience", "brand awareness"), listOf("campaign"), "Doğru cümle: The campaign doubled our online sales. — Kampanya çevrim içi satışlarımızı ikiye katladı.", null, null),
                LearningExercise("b2v14e5", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "They ___ed the product in March.", "", listOf("engagement", "campaign", "launch"), listOf("launch"), "Doğru cümle: They launched the product in March. — Ürünü martta piyasaya sürdüler.", null, null),
                LearningExercise("b2v14e6", Skill.LISTENING, "Dinle ve anlamı seç", "Cümle ne anlatıyor?", "", listOf("Etkinlikten sonra marka bilinirliği arttı.", "Gönderideki etkileşim etkileyiciydi.", "Kampanya çevrim içi satışlarımızı ikiye katladı."), listOf("Gönderideki etkileşim etkileyiciydi."), "Söylenen cümle: Engagement on the post was impressive.", "Engagement on the post was impressive.", null),
                LearningExercise("b2v14e10", Skill.READING, "Cümleyi oku ve doğru anlamı seç", "Okuduğun cümle ne anlatıyor?", "They launched the product in March.", listOf("Hedef kitlemiz genç profesyoneller.", "Gönderideki etkileşim etkileyiciydi.", "Ürünü martta piyasaya sürdüler."), listOf("Ürünü martta piyasaya sürdüler."), "Cümlenin çevirisi: Ürünü martta piyasaya sürdüler.", null, null))),
            LearningLesson("B2-U14-L3", "Marketing & Branding — Practice", "Apply the grammar focus, speak and write.", listOf(
                LearningExercise("b2v14e7", Skill.GRAMMAR, "Doğru seçeneği işaretle", "The results, ___ were published Friday, look promising.", "", listOf("which", "that", "what"), listOf("which"), "Virgüllü ek bilgi cümlesinde which kullanılır.", null, null),
                LearningExercise("b2v14e8", Skill.SPEAKING, "İfadeyi sesli söyle", "Say: Our target audience is young professionals.", "", listOf(), listOf("Our target audience is young professionals."), "Türkçesi: Hedef kitlemiz genç profesyoneller.", "Our target audience is young professionals.", "Our target audience is young professionals."),
                LearningExercise("b2v14e9", Skill.WRITING, "Cümleyi İngilizce yaz", "İngilizcesi: Etkinlikten sonra marka bilinirliği arttı.", "", listOf(), listOf("Brand awareness rose after the event."), "Örnek yanıt: Brand awareness rose after the event.", null, "Brand awareness rose after the event."))))),
        LearningUnit("B2-U15", "Negotiation Basics", "Negotiate terms and reach agreements.", listOf(
            LearningLesson("B2-U15-L1", "Negotiation Basics — Words", "Recognize key vocabulary for this topic.", listOf(
                LearningExercise("b2v15e1", Skill.VOCABULARY, "Doğru anlamı seç", "'concession' ne anlama gelir?", "", listOf("taviz", "uzlaşma", "koz"), listOf("taviz"), "Both sides made small concessions. — İki taraf da küçük tavizler verdi.", null, null),
                LearningExercise("b2v15e2", Skill.VOCABULARY, "Doğru anlamı seç", "'compromise' ne anlama gelir?", "", listOf("şartlar", "masadan kalkmak", "uzlaşma"), listOf("uzlaşma"), "We reached a fair compromise. — Adil bir uzlaşmaya vardık.", null, null),
                LearningExercise("b2v15e3", Skill.VOCABULARY, "Doğru anlamı seç", "'terms' ne anlama gelir?", "", listOf("taviz", "şartlar", "koz"), listOf("şartlar"), "The terms of the contract are flexible. — Sözleşmenin şartları esnek.", null, null))),
            LearningLesson("B2-U15-L2", "Negotiation Basics — In Use", "Use the new words in real sentences and listening.", listOf(
                LearningExercise("b2v15e4", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "Both sides made small ___s.", "", listOf("compromise", "terms", "concession"), listOf("concession"), "Doğru cümle: Both sides made small concessions. — İki taraf da küçük tavizler verdi.", null, null),
                LearningExercise("b2v15e5", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "Their market share gave them ___.", "", listOf("concession", "leverage", "walk away"), listOf("leverage"), "Doğru cümle: Their market share gave them leverage. — Pazar payları onlara koz sağladı.", null, null),
                LearningExercise("b2v15e6", Skill.LISTENING, "Dinle ve anlamı seç", "Cümle ne anlatıyor?", "", listOf("Kötü bir anlaşmadan vazgeçmeye hazır ol.", "İki taraf da küçük tavizler verdi.", "Sözleşmenin şartları esnek."), listOf("Kötü bir anlaşmadan vazgeçmeye hazır ol."), "Söylenen cümle: Be ready to walk away from a bad deal.", "Be ready to walk away from a bad deal.", null),
                LearningExercise("b2v15e10", Skill.READING, "Cümleyi oku ve doğru anlamı seç", "Okuduğun cümle ne anlatıyor?", "Their market share gave them leverage.", listOf("Kötü bir anlaşmadan vazgeçmeye hazır ol.", "Pazar payları onlara koz sağladı.", "Adil bir uzlaşmaya vardık."), listOf("Pazar payları onlara koz sağladı."), "Cümlenin çevirisi: Pazar payları onlara koz sağladı.", null, null))),
            LearningLesson("B2-U15-L3", "Negotiation Basics — Practice", "Apply the grammar focus, speak and write.", listOf(
                LearningExercise("b2v15e7", Skill.GRAMMAR, "Doğru seçeneği işaretle", "___ we lower the price, could you sign today?", "", listOf("Provided", "Unless", "Despite"), listOf("Provided"), "Şart bildiren bağlaç: provided (that).", null, null),
                LearningExercise("b2v15e8", Skill.SPEAKING, "İfadeyi sesli söyle", "Say: We reached a fair compromise.", "", listOf(), listOf("We reached a fair compromise."), "Türkçesi: Adil bir uzlaşmaya vardık.", "We reached a fair compromise.", "We reached a fair compromise."),
                LearningExercise("b2v15e9", Skill.WRITING, "Cümleyi İngilizce yaz", "İngilizcesi: Sözleşmenin şartları esnek.", "", listOf(), listOf("The terms of the contract are flexible."), "Örnek yanıt: The terms of the contract are flexible.", null, "The terms of the contract are flexible."))))),
        LearningUnit("B2-U16", "Economy & Markets", "Understand basic economic news and trends.", listOf(
            LearningLesson("B2-U16-L1", "Economy & Markets — Words", "Recognize key vocabulary for this topic.", listOf(
                LearningExercise("b2v16e1", Skill.VOCABULARY, "Doğru anlamı seç", "'inflation' ne anlama gelir?", "", listOf("talep", "yatırım", "enflasyon"), listOf("enflasyon"), "Inflation slowed down last quarter. — Enflasyon geçen çeyrekte yavaşladı.", null, null),
                LearningExercise("b2v16e2", Skill.VOCABULARY, "Doğru anlamı seç", "'demand' ne anlama gelir?", "", listOf("durgunluk", "talep", "arz"), listOf("talep"), "Demand for housing remains high. — Konut talebi yüksek seyrediyor.", null, null),
                LearningExercise("b2v16e3", Skill.VOCABULARY, "Doğru anlamı seç", "'supply' ne anlama gelir?", "", listOf("arz", "yatırım", "enflasyon"), listOf("arz"), "Supply problems pushed prices up. — Arz sorunları fiyatları yukarı itti.", null, null))),
            LearningLesson("B2-U16-L2", "Economy & Markets — In Use", "Use the new words in real sentences and listening.", listOf(
                LearningExercise("b2v16e4", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "___ slowed down last quarter.", "", listOf("supply", "Inflation", "demand"), listOf("Inflation"), "Doğru cümle: Inflation slowed down last quarter. — Enflasyon geçen çeyrekte yavaşladı.", null, null),
                LearningExercise("b2v16e5", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "Foreign ___ increased this year.", "", listOf("investment", "recession", "inflation"), listOf("investment"), "Doğru cümle: Foreign investment increased this year. — Yabancı yatırım bu yıl arttı.", null, null),
                LearningExercise("b2v16e6", Skill.LISTENING, "Dinle ve anlamı seç", "Cümle ne anlatıyor?", "", listOf("Enflasyon geçen çeyrekte yavaşladı.", "Arz sorunları fiyatları yukarı itti.", "Ülke derin bir durgunluktan kurtuldu."), listOf("Ülke derin bir durgunluktan kurtuldu."), "Söylenen cümle: The country avoided a deep recession.", "The country avoided a deep recession.", null),
                LearningExercise("b2v16e10", Skill.READING, "Cümleyi oku ve doğru anlamı seç", "Okuduğun cümle ne anlatıyor?", "Foreign investment increased this year.", listOf("Yabancı yatırım bu yıl arttı.", "Konut talebi yüksek seyrediyor.", "Ülke derin bir durgunluktan kurtuldu."), listOf("Yabancı yatırım bu yıl arttı."), "Cümlenin çevirisi: Yabancı yatırım bu yıl arttı.", null, null))),
            LearningLesson("B2-U16-L3", "Economy & Markets — Practice", "Apply the grammar focus, speak and write.", listOf(
                LearningExercise("b2v16e7", Skill.GRAMMAR, "Doğru seçeneği işaretle", "Prices are expected ___ further next year.", "", listOf("to rise", "rising", "rise"), listOf("to rise"), "Be expected + to + fiil kalıbı.", null, null),
                LearningExercise("b2v16e8", Skill.SPEAKING, "İfadeyi sesli söyle", "Say: Demand for housing remains high.", "", listOf(), listOf("Demand for housing remains high."), "Türkçesi: Konut talebi yüksek seyrediyor.", "Demand for housing remains high.", "Demand for housing remains high."),
                LearningExercise("b2v16e9", Skill.WRITING, "Cümleyi İngilizce yaz", "İngilizcesi: Arz sorunları fiyatları yukarı itti.", "", listOf(), listOf("Supply problems pushed prices up."), "Örnek yanıt: Supply problems pushed prices up.", null, "Supply problems pushed prices up."))))),
        LearningUnit("B2-U17", "Science & Innovation", "Discuss discoveries and new technologies.", listOf(
            LearningLesson("B2-U17-L1", "Science & Innovation — Words", "Recognize key vocabulary for this topic.", listOf(
                LearningExercise("b2v17e1", Skill.VOCABULARY, "Doğru anlamı seç", "'breakthrough' ne anlama gelir?", "", listOf("cihaz", "çığır açan gelişme", "hipotez"), listOf("çığır açan gelişme"), "The discovery was a real breakthrough. — Keşif gerçek bir çığır açtı.", null, null),
                LearningExercise("b2v17e2", Skill.VOCABULARY, "Doğru anlamı seç", "'hypothesis' ne anlama gelir?", "", listOf("hipotez", "deneme", "yapay"), listOf("hipotez"), "The data did not support the hypothesis. — Veriler hipotezi desteklemedi.", null, null),
                LearningExercise("b2v17e3", Skill.VOCABULARY, "Doğru anlamı seç", "'trial' ne anlama gelir?", "", listOf("cihaz", "çığır açan gelişme", "deneme"), listOf("deneme"), "The new drug passed its clinical trials. — Yeni ilaç klinik denemeleri geçti.", null, null))),
            LearningLesson("B2-U17-L2", "Science & Innovation — In Use", "Use the new words in real sentences and listening.", listOf(
                LearningExercise("b2v17e4", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "The discovery was a real ___.", "", listOf("breakthrough", "hypothesis", "trial"), listOf("breakthrough"), "Doğru cümle: The discovery was a real breakthrough. — Keşif gerçek bir çığır açtı.", null, null),
                LearningExercise("b2v17e5", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "The ___ measures air quality.", "", listOf("artificial", "breakthrough", "device"), listOf("device"), "Doğru cümle: The device measures air quality. — Cihaz hava kalitesini ölçüyor.", null, null),
                LearningExercise("b2v17e6", Skill.LISTENING, "Dinle ve anlamı seç", "Cümle ne anlatıyor?", "", listOf("Yeni ilaç klinik denemeleri geçti.", "Yapay ışık uyku düzenini etkiler.", "Keşif gerçek bir çığır açtı."), listOf("Yapay ışık uyku düzenini etkiler."), "Söylenen cümle: Artificial light affects sleep patterns.", "Artificial light affects sleep patterns.", null),
                LearningExercise("b2v17e10", Skill.READING, "Cümleyi oku ve doğru anlamı seç", "Okuduğun cümle ne anlatıyor?", "The device measures air quality.", listOf("Veriler hipotezi desteklemedi.", "Yapay ışık uyku düzenini etkiler.", "Cihaz hava kalitesini ölçüyor."), listOf("Cihaz hava kalitesini ölçüyor."), "Cümlenin çevirisi: Cihaz hava kalitesini ölçüyor.", null, null))),
            LearningLesson("B2-U17-L3", "Science & Innovation — Practice", "Apply the grammar focus, speak and write.", listOf(
                LearningExercise("b2v17e7", Skill.GRAMMAR, "Doğru seçeneği işaretle", "Rarely ___ such clear results in one study.", "", listOf("do we see", "we see", "we do see"), listOf("do we see"), "Rarely ile devrik yapı kullanılır.", null, null),
                LearningExercise("b2v17e8", Skill.SPEAKING, "İfadeyi sesli söyle", "Say: The data did not support the hypothesis.", "", listOf(), listOf("The data did not support the hypothesis."), "Türkçesi: Veriler hipotezi desteklemedi.", "The data did not support the hypothesis.", "The data did not support the hypothesis."),
                LearningExercise("b2v17e9", Skill.WRITING, "Cümleyi İngilizce yaz", "İngilizcesi: Yeni ilaç klinik denemeleri geçti.", "", listOf(), listOf("The new drug passed its clinical trials."), "Örnek yanıt: The new drug passed its clinical trials.", null, "The new drug passed its clinical trials."))))),
        LearningUnit("B2-U18", "Contracts & Agreements", "Read simple contracts and formal letters.", listOf(
            LearningLesson("B2-U18-L1", "Contracts & Agreements — Words", "Recognize key vocabulary for this topic.", listOf(
                LearningExercise("b2v18e1", Skill.VOCABULARY, "Doğru anlamı seç", "'clause' ne anlama gelir?", "", listOf("madde", "yükümlülük", "taraf"), listOf("madde"), "Read the cancellation clause carefully. — İptal maddesini dikkatle oku.", null, null),
                LearningExercise("b2v18e2", Skill.VOCABULARY, "Doğru anlamı seç", "'liability' ne anlama gelir?", "", listOf("ihlal", "yenilemek", "yükümlülük"), listOf("yükümlülük"), "The company accepted limited liability. — Şirket sınırlı yükümlülük kabul etti.", null, null),
                LearningExercise("b2v18e3", Skill.VOCABULARY, "Doğru anlamı seç", "'breach' ne anlama gelir?", "", listOf("madde", "ihlal", "taraf"), listOf("ihlal"), "Late delivery is a breach of contract. — Geç teslimat sözleşme ihlalidir.", null, null))),
            LearningLesson("B2-U18-L2", "Contracts & Agreements — In Use", "Use the new words in real sentences and listening.", listOf(
                LearningExercise("b2v18e4", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "Read the cancellation ___ carefully.", "", listOf("liability", "breach", "clause"), listOf("clause"), "Doğru cümle: Read the cancellation clause carefully. — İptal maddesini dikkatle oku.", null, null),
                LearningExercise("b2v18e5", Skill.VOCABULARY, "Doğru anlamı seç", "'party' ne anlama gelir?", "", listOf("madde", "ihlal", "taraf"), listOf("taraf"), "Both parties signed the agreement. — Her iki taraf da anlaşmayı imzaladı.", null, null),
                LearningExercise("b2v18e6", Skill.LISTENING, "Dinle ve anlamı seç", "Cümle ne anlatıyor?", "", listOf("Kira sözleşmesini yenilemeye karar verdik.", "İptal maddesini dikkatle oku.", "Geç teslimat sözleşme ihlalidir."), listOf("Kira sözleşmesini yenilemeye karar verdik."), "Söylenen cümle: We decided to renew the lease.", "We decided to renew the lease.", null),
                LearningExercise("b2v18e10", Skill.READING, "Cümleyi oku ve doğru anlamı seç", "Okuduğun cümle ne anlatıyor?", "Both parties signed the agreement.", listOf("Kira sözleşmesini yenilemeye karar verdik.", "Her iki taraf da anlaşmayı imzaladı.", "Şirket sınırlı yükümlülük kabul etti."), listOf("Her iki taraf da anlaşmayı imzaladı."), "Cümlenin çevirisi: Her iki taraf da anlaşmayı imzaladı.", null, null))),
            LearningLesson("B2-U18-L3", "Contracts & Agreements — Practice", "Apply the grammar focus, speak and write.", listOf(
                LearningExercise("b2v18e7", Skill.GRAMMAR, "Doğru seçeneği işaretle", "The contract must ___ by both parties.", "", listOf("be signed", "sign", "signed"), listOf("be signed"), "Modal sonrası edilgen: must be signed.", null, null),
                LearningExercise("b2v18e8", Skill.SPEAKING, "İfadeyi sesli söyle", "Say: The company accepted limited liability.", "", listOf(), listOf("The company accepted limited liability."), "Türkçesi: Şirket sınırlı yükümlülük kabul etti.", "The company accepted limited liability.", "The company accepted limited liability."),
                LearningExercise("b2v18e9", Skill.WRITING, "Cümleyi İngilizce yaz", "İngilizcesi: Geç teslimat sözleşme ihlalidir.", "", listOf(), listOf("Late delivery is a breach of contract."), "Örnek yanıt: Late delivery is a breach of contract.", null, "Late delivery is a breach of contract."))))),
        LearningUnit("B2-U19", "Behaviour & Psychology", "Talk about motivation, habits and behaviour.", listOf(
            LearningLesson("B2-U19-L1", "Behaviour & Psychology — Words", "Recognize key vocabulary for this topic.", listOf(
                LearningExercise("b2v19e1", Skill.VOCABULARY, "Doğru anlamı seç", "'motivation' ne anlama gelir?", "", listOf("önyargı", "eğilim", "motivasyon"), listOf("motivasyon"), "Clear goals increase motivation. — Net hedefler motivasyonu artırır.", null, null),
                LearningExercise("b2v19e2", Skill.VOCABULARY, "Doğru anlamı seç", "'bias' ne anlama gelir?", "", listOf("algı", "önyargı", "ödül"), listOf("önyargı"), "We all have hidden biases. — Hepimizin gizli önyargıları vardır.", null, null),
                LearningExercise("b2v19e3", Skill.VOCABULARY, "Doğru anlamı seç", "'reward' ne anlama gelir?", "", listOf("ödül", "eğilim", "motivasyon"), listOf("ödül"), "Small rewards build strong habits. — Küçük ödüller güçlü alışkanlıklar oluşturur.", null, null))),
            LearningLesson("B2-U19-L2", "Behaviour & Psychology — In Use", "Use the new words in real sentences and listening.", listOf(
                LearningExercise("b2v19e4", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "Clear goals increase ___.", "", listOf("reward", "motivation", "bias"), listOf("motivation"), "Doğru cümle: Clear goals increase motivation. — Net hedefler motivasyonu artırır.", null, null),
                LearningExercise("b2v19e5", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "He has a ___ to postpone tasks.", "", listOf("tendency", "perception", "motivation"), listOf("tendency"), "Doğru cümle: He has a tendency to postpone tasks. — İşleri erteleme eğilimi var.", null, null),
                LearningExercise("b2v19e6", Skill.LISTENING, "Dinle ve anlamı seç", "Cümle ne anlatıyor?", "", listOf("Net hedefler motivasyonu artırır.", "Küçük ödüller güçlü alışkanlıklar oluşturur.", "Renk, tat algımızı etkiler."), listOf("Renk, tat algımızı etkiler."), "Söylenen cümle: Colour affects our perception of taste.", "Colour affects our perception of taste.", null),
                LearningExercise("b2v19e10", Skill.READING, "Cümleyi oku ve doğru anlamı seç", "Okuduğun cümle ne anlatıyor?", "He has a tendency to postpone tasks.", listOf("İşleri erteleme eğilimi var.", "Hepimizin gizli önyargıları vardır.", "Renk, tat algımızı etkiler."), listOf("İşleri erteleme eğilimi var."), "Cümlenin çevirisi: İşleri erteleme eğilimi var.", null, null))),
            LearningLesson("B2-U19-L3", "Behaviour & Psychology — Practice", "Apply the grammar focus, speak and write.", listOf(
                LearningExercise("b2v19e7", Skill.GRAMMAR, "Doğru seçeneği işaretle", "It is the routine ___ makes change possible.", "", listOf("that", "what", "who"), listOf("that"), "Vurgu cümlesi: It is X that...", null, null),
                LearningExercise("b2v19e8", Skill.SPEAKING, "İfadeyi sesli söyle", "Say: We all have hidden biases.", "", listOf(), listOf("We all have hidden biases."), "Türkçesi: Hepimizin gizli önyargıları vardır.", "We all have hidden biases.", "We all have hidden biases."),
                LearningExercise("b2v19e9", Skill.WRITING, "Cümleyi İngilizce yaz", "İngilizcesi: Küçük ödüller güçlü alışkanlıklar oluşturur.", "", listOf(), listOf("Small rewards build strong habits."), "Örnek yanıt: Small rewards build strong habits.", null, "Small rewards build strong habits."))))),
        LearningUnit("B2-U20", "Presentations & Public Speaking", "Deliver clear, structured presentations.", listOf(
            LearningLesson("B2-U20-L1", "Presentations & Public Speaking — Words", "Recognize key vocabulary for this topic.", listOf(
                LearningExercise("b2v20e1", Skill.VOCABULARY, "Doğru anlamı seç", "'outline' ne anlama gelir?", "", listOf("çıkarım", "ana hat", "görsel"), listOf("ana hat"), "Let me outline the three key points. — Üç ana noktayı özetleyeyim.", null, null),
                LearningExercise("b2v20e2", Skill.VOCABULARY, "Doğru anlamı seç", "'visual' ne anlama gelir?", "", listOf("görsel", "geçiş", "prova yapmak"), listOf("görsel"), "Use visuals to support your message. — Mesajını desteklemek için görseller kullan.", null, null),
                LearningExercise("b2v20e3", Skill.VOCABULARY, "Doğru anlamı seç", "'transition' ne anlama gelir?", "", listOf("çıkarım", "ana hat", "geçiş"), listOf("geçiş"), "Smooth transitions keep the audience focused. — Akıcı geçişler dinleyiciyi odakta tutar.", null, null))),
            LearningLesson("B2-U20-L2", "Presentations & Public Speaking — In Use", "Use the new words in real sentences and listening.", listOf(
                LearningExercise("b2v20e4", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "Let me ___ the three key points.", "", listOf("outline", "visual", "transition"), listOf("outline"), "Doğru cümle: Let me outline the three key points. — Üç ana noktayı özetleyeyim.", null, null),
                LearningExercise("b2v20e5", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "The main ___ is simple: start early.", "", listOf("rehearse", "outline", "takeaway"), listOf("takeaway"), "Doğru cümle: The main takeaway is simple: start early. — Ana çıkarım basit: erken başla.", null, null),
                LearningExercise("b2v20e6", Skill.LISTENING, "Dinle ve anlamı seç", "Cümle ne anlatıyor?", "", listOf("Akıcı geçişler dinleyiciyi odakta tutar.", "Konuşmanın en az iki kez provasını yap.", "Üç ana noktayı özetleyeyim."), listOf("Konuşmanın en az iki kez provasını yap."), "Söylenen cümle: Rehearse the talk at least twice.", "Rehearse the talk at least twice.", null),
                LearningExercise("b2v20e10", Skill.READING, "Cümleyi oku ve doğru anlamı seç", "Okuduğun cümle ne anlatıyor?", "The main takeaway is simple: start early.", listOf("Mesajını desteklemek için görseller kullan.", "Konuşmanın en az iki kez provasını yap.", "Ana çıkarım basit: erken başla."), listOf("Ana çıkarım basit: erken başla."), "Cümlenin çevirisi: Ana çıkarım basit: erken başla.", null, null))),
            LearningLesson("B2-U20-L3", "Presentations & Public Speaking — Practice", "Apply the grammar focus, speak and write.", listOf(
                LearningExercise("b2v20e7", Skill.GRAMMAR, "Doğru seçeneği işaretle", "Not only ___ the data, but she also explained its limits.", "", listOf("did she present", "she presented", "she did present"), listOf("did she present"), "Not only başta: devrik yapı gerekir.", null, null),
                LearningExercise("b2v20e8", Skill.SPEAKING, "İfadeyi sesli söyle", "Say: Use visuals to support your message.", "", listOf(), listOf("Use visuals to support your message."), "Türkçesi: Mesajını desteklemek için görseller kullan.", "Use visuals to support your message.", "Use visuals to support your message."),
                LearningExercise("b2v20e9", Skill.WRITING, "Cümleyi İngilizce yaz", "İngilizcesi: Akıcı geçişler dinleyiciyi odakta tutar.", "", listOf(), listOf("Smooth transitions keep the audience focused."), "Örnek yanıt: Smooth transitions keep the audience focused.", null, "Smooth transitions keep the audience focused."))))),
        LearningUnit("B2-U21", "Data & Analysis", "Describe trends, figures and comparisons.", listOf(
            LearningLesson("B2-U21-L1", "Data & Analysis — Words", "Recognize key vocabulary for this topic.", listOf(
                LearningExercise("b2v21e1", Skill.VOCABULARY, "Doğru anlamı seç", "'trend' ne anlama gelir?", "", listOf("eğilim", "düşüş", "yaklaşık"), listOf("eğilim"), "The upward trend continued in May. — Yükseliş eğilimi mayısta sürdü.", null, null),
                LearningExercise("b2v21e2", Skill.VOCABULARY, "Doğru anlamı seç", "'decline' ne anlama gelir?", "", listOf("anlamlı", "zirve", "düşüş"), listOf("düşüş"), "Sales showed a slight decline. — Satışlar hafif bir düşüş gösterdi.", null, null),
                LearningExercise("b2v21e3", Skill.VOCABULARY, "Doğru anlamı seç", "'significant' ne anlama gelir?", "", listOf("eğilim", "anlamlı", "yaklaşık"), listOf("anlamlı"), "The difference was statistically significant. — Fark istatistiksel olarak anlamlıydı.", null, null))),
            LearningLesson("B2-U21-L2", "Data & Analysis — In Use", "Use the new words in real sentences and listening.", listOf(
                LearningExercise("b2v21e4", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "The upward ___ continued in May.", "", listOf("decline", "significant", "trend"), listOf("trend"), "Doğru cümle: The upward trend continued in May. — Yükseliş eğilimi mayısta sürdü.", null, null),
                LearningExercise("b2v21e5", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "___ a third of users responded.", "", listOf("trend", "Roughly", "peak"), listOf("Roughly"), "Doğru cümle: Roughly a third of users responded. — Kullanıcıların yaklaşık üçte biri yanıt verdi.", null, null),
                LearningExercise("b2v21e6", Skill.LISTENING, "Dinle ve anlamı seç", "Cümle ne anlatıyor?", "", listOf("Trafik öğlen zirveye ulaştı.", "Yükseliş eğilimi mayısta sürdü.", "Fark istatistiksel olarak anlamlıydı."), listOf("Trafik öğlen zirveye ulaştı."), "Söylenen cümle: Traffic reached its peak at noon.", "Traffic reached its peak at noon.", null),
                LearningExercise("b2v21e10", Skill.READING, "Cümleyi oku ve doğru anlamı seç", "Okuduğun cümle ne anlatıyor?", "Roughly a third of users responded.", listOf("Trafik öğlen zirveye ulaştı.", "Kullanıcıların yaklaşık üçte biri yanıt verdi.", "Satışlar hafif bir düşüş gösterdi."), listOf("Kullanıcıların yaklaşık üçte biri yanıt verdi."), "Cümlenin çevirisi: Kullanıcıların yaklaşık üçte biri yanıt verdi.", null, null))),
            LearningLesson("B2-U21-L3", "Data & Analysis — Practice", "Apply the grammar focus, speak and write.", listOf(
                LearningExercise("b2v21e7", Skill.GRAMMAR, "Doğru seçeneği işaretle", "The figures ___ steadily since January.", "", listOf("have been rising", "rise", "are rising"), listOf("have been rising"), "Since ile süregelen süreç: present perfect continuous.", null, null),
                LearningExercise("b2v21e8", Skill.SPEAKING, "İfadeyi sesli söyle", "Say: Sales showed a slight decline.", "", listOf(), listOf("Sales showed a slight decline."), "Türkçesi: Satışlar hafif bir düşüş gösterdi.", "Sales showed a slight decline.", "Sales showed a slight decline."),
                LearningExercise("b2v21e9", Skill.WRITING, "Cümleyi İngilizce yaz", "İngilizcesi: Fark istatistiksel olarak anlamlıydı.", "", listOf(), listOf("The difference was statistically significant."), "Örnek yanıt: The difference was statistically significant.", null, "The difference was statistically significant."))))),
        LearningUnit("B2-U22", "Workplace Ethics", "Discuss fairness, transparency and conduct.", listOf(
            LearningLesson("B2-U22-L1", "Workplace Ethics — Words", "Recognize key vocabulary for this topic.", listOf(
                LearningExercise("b2v22e1", Skill.VOCABULARY, "Doğru anlamı seç", "'integrity' ne anlama gelir?", "", listOf("şeffaf", "ifşa etmek", "dürüstlük"), listOf("dürüstlük"), "She is known for her integrity. — Dürüstlüğüyle tanınır.", null, null),
                LearningExercise("b2v22e2", Skill.VOCABULARY, "Doğru anlamı seç", "'transparent' ne anlama gelir?", "", listOf("hesap verebilirlik", "şeffaf", "gizli"), listOf("şeffaf"), "The hiring process should be transparent. — İşe alım süreci şeffaf olmalı.", null, null),
                LearningExercise("b2v22e3", Skill.VOCABULARY, "Doğru anlamı seç", "'confidential' ne anlama gelir?", "", listOf("gizli", "ifşa etmek", "dürüstlük"), listOf("gizli"), "Keep client data confidential. — Müşteri verilerini gizli tut.", null, null))),
            LearningLesson("B2-U22-L2", "Workplace Ethics — In Use", "Use the new words in real sentences and listening.", listOf(
                LearningExercise("b2v22e4", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "She is known for her ___.", "", listOf("confidential", "integrity", "transparent"), listOf("integrity"), "Doğru cümle: She is known for her integrity. — Dürüstlüğüyle tanınır.", null, null),
                LearningExercise("b2v22e5", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "He ___d the conflict of interest.", "", listOf("disclose", "accountability", "integrity"), listOf("disclose"), "Doğru cümle: He disclosed the conflict of interest. — Çıkar çatışmasını açıkladı.", null, null),
                LearningExercise("b2v22e6", Skill.LISTENING, "Dinle ve anlamı seç", "Cümle ne anlatıyor?", "", listOf("Dürüstlüğüyle tanınır.", "Müşteri verilerini gizli tut.", "Hesap verebilirlik ekipte güven oluşturur."), listOf("Hesap verebilirlik ekipte güven oluşturur."), "Söylenen cümle: Accountability builds trust in teams.", "Accountability builds trust in teams.", null),
                LearningExercise("b2v22e10", Skill.READING, "Cümleyi oku ve doğru anlamı seç", "Okuduğun cümle ne anlatıyor?", "He disclosed the conflict of interest.", listOf("Çıkar çatışmasını açıkladı.", "İşe alım süreci şeffaf olmalı.", "Hesap verebilirlik ekipte güven oluşturur."), listOf("Çıkar çatışmasını açıkladı."), "Cümlenin çevirisi: Çıkar çatışmasını açıkladı.", null, null))),
            LearningLesson("B2-U22-L3", "Workplace Ethics — Practice", "Apply the grammar focus, speak and write.", listOf(
                LearningExercise("b2v22e7", Skill.GRAMMAR, "Doğru seçeneği işaretle", "Employees ___ report misconduct without fear.", "", listOf("should be able to", "should to", "are able"), listOf("should be able to"), "Modal zinciri: should be able to.", null, null),
                LearningExercise("b2v22e8", Skill.SPEAKING, "İfadeyi sesli söyle", "Say: The hiring process should be transparent.", "", listOf(), listOf("The hiring process should be transparent."), "Türkçesi: İşe alım süreci şeffaf olmalı.", "The hiring process should be transparent.", "The hiring process should be transparent."),
                LearningExercise("b2v22e9", Skill.WRITING, "Cümleyi İngilizce yaz", "İngilizcesi: Müşteri verilerini gizli tut.", "", listOf(), listOf("Keep client data confidential."), "Örnek yanıt: Keep client data confidential.", null, "Keep client data confidential."))))),
        LearningUnit("B2-U23", "Global Issues", "Debate migration, inequality and development.", listOf(
            LearningLesson("B2-U23-L1", "Global Issues — Words", "Recognize key vocabulary for this topic.", listOf(
                LearningExercise("b2v23e1", Skill.VOCABULARY, "Doğru anlamı seç", "'inequality' ne anlama gelir?", "", listOf("kriz", "eşitsizlik", "yardım"), listOf("eşitsizlik"), "Income inequality widened over the decade. — Gelir eşitsizliği on yılda derinleşti.", null, null),
                LearningExercise("b2v23e2", Skill.VOCABULARY, "Doğru anlamı seç", "'aid' ne anlama gelir?", "", listOf("yardım", "sürdürülebilir", "politika"), listOf("yardım"), "International aid reached the region quickly. — Uluslararası yardım bölgeye hızla ulaştı.", null, null),
                LearningExercise("b2v23e3", Skill.VOCABULARY, "Doğru anlamı seç", "'sustainable' ne anlama gelir?", "", listOf("kriz", "eşitsizlik", "sürdürülebilir"), listOf("sürdürülebilir"), "We need sustainable growth, not quick fixes. — Hızlı çözümler değil sürdürülebilir büyüme gerekli.", null, null))),
            LearningLesson("B2-U23-L2", "Global Issues — In Use", "Use the new words in real sentences and listening.", listOf(
                LearningExercise("b2v23e4", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "Income ___ widened over the decade.", "", listOf("inequality", "aid", "sustainable"), listOf("inequality"), "Doğru cümle: Income inequality widened over the decade. — Gelir eşitsizliği on yılda derinleşti.", null, null),
                LearningExercise("b2v23e5", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "The water ___ affects millions.", "", listOf("policy", "inequality", "crisis"), listOf("crisis"), "Doğru cümle: The water crisis affects millions. — Su krizi milyonları etkiliyor.", null, null),
                LearningExercise("b2v23e6", Skill.LISTENING, "Dinle ve anlamı seç", "Cümle ne anlatıyor?", "", listOf("Hızlı çözümler değil sürdürülebilir büyüme gerekli.", "Yeni politika genç işsizliğini hedefliyor.", "Gelir eşitsizliği on yılda derinleşti."), listOf("Yeni politika genç işsizliğini hedefliyor."), "Söylenen cümle: The new policy targets youth unemployment.", "The new policy targets youth unemployment.", null),
                LearningExercise("b2v23e10", Skill.READING, "Cümleyi oku ve doğru anlamı seç", "Okuduğun cümle ne anlatıyor?", "The water crisis affects millions.", listOf("Uluslararası yardım bölgeye hızla ulaştı.", "Yeni politika genç işsizliğini hedefliyor.", "Su krizi milyonları etkiliyor."), listOf("Su krizi milyonları etkiliyor."), "Cümlenin çevirisi: Su krizi milyonları etkiliyor.", null, null))),
            LearningLesson("B2-U23-L3", "Global Issues — Practice", "Apply the grammar focus, speak and write.", listOf(
                LearningExercise("b2v23e7", Skill.GRAMMAR, "Doğru seçeneği işaretle", "___ the challenges, progress has been made.", "", listOf("Despite", "Although", "However"), listOf("Despite"), "İsim öbeğinden önce despite kullanılır.", null, null),
                LearningExercise("b2v23e8", Skill.SPEAKING, "İfadeyi sesli söyle", "Say: International aid reached the region quickly.", "", listOf(), listOf("International aid reached the region quickly."), "Türkçesi: Uluslararası yardım bölgeye hızla ulaştı.", "International aid reached the region quickly.", "International aid reached the region quickly."),
                LearningExercise("b2v23e9", Skill.WRITING, "Cümleyi İngilizce yaz", "İngilizcesi: Hızlı çözümler değil sürdürülebilir büyüme gerekli.", "", listOf(), listOf("We need sustainable growth, not quick fixes."), "Örnek yanıt: We need sustainable growth, not quick fixes.", null, "We need sustainable growth, not quick fixes."))))),
        LearningUnit("B2-U24", "Academic Writing Basics", "Structure essays and support arguments.", listOf(
            LearningLesson("B2-U24-L1", "Academic Writing Basics — Words", "Recognize key vocabulary for this topic.", listOf(
                LearningExercise("b2v24e1", Skill.VOCABULARY, "Doğru anlamı seç", "'thesis' ne anlama gelir?", "", listOf("tez", "kanıt", "paragraf"), listOf("tez"), "State your thesis in the first paragraph. — Tezini ilk paragrafta belirt.", null, null),
                LearningExercise("b2v24e2", Skill.VOCABULARY, "Doğru anlamı seç", "'evidence' ne anlama gelir?", "", listOf("alıntılamak", "sonuç bölümü", "kanıt"), listOf("kanıt"), "Support every claim with evidence. — Her iddiayı kanıtla destekle.", null, null),
                LearningExercise("b2v24e3", Skill.VOCABULARY, "Doğru anlamı seç", "'cite' ne anlama gelir?", "", listOf("tez", "alıntılamak", "paragraf"), listOf("alıntılamak"), "Cite your sources correctly. — Kaynaklarını doğru şekilde alıntıla.", null, null))),
            LearningLesson("B2-U24-L2", "Academic Writing Basics — In Use", "Use the new words in real sentences and listening.", listOf(
                LearningExercise("b2v24e4", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "State your ___ in the first paragraph.", "", listOf("evidence", "cite", "thesis"), listOf("thesis"), "Doğru cümle: State your thesis in the first paragraph. — Tezini ilk paragrafta belirt.", null, null),
                LearningExercise("b2v24e5", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "Each ___ should have one main idea.", "", listOf("thesis", "paragraph", "conclusion"), listOf("paragraph"), "Doğru cümle: Each paragraph should have one main idea. — Her paragrafın tek bir ana fikri olmalı.", null, null),
                LearningExercise("b2v24e6", Skill.LISTENING, "Dinle ve anlamı seç", "Cümle ne anlatıyor?", "", listOf("Sonuç bölümü ana savı yeniden ifade eder.", "Tezini ilk paragrafta belirt.", "Kaynaklarını doğru şekilde alıntıla."), listOf("Sonuç bölümü ana savı yeniden ifade eder."), "Söylenen cümle: The conclusion restates the main argument.", "The conclusion restates the main argument.", null),
                LearningExercise("b2v24e10", Skill.READING, "Cümleyi oku ve doğru anlamı seç", "Okuduğun cümle ne anlatıyor?", "Each paragraph should have one main idea.", listOf("Sonuç bölümü ana savı yeniden ifade eder.", "Her paragrafın tek bir ana fikri olmalı.", "Her iddiayı kanıtla destekle."), listOf("Her paragrafın tek bir ana fikri olmalı."), "Cümlenin çevirisi: Her paragrafın tek bir ana fikri olmalı.", null, null))),
            LearningLesson("B2-U24-L3", "Academic Writing Basics — Practice", "Apply the grammar focus, speak and write.", listOf(
                LearningExercise("b2v24e7", Skill.GRAMMAR, "Doğru seçeneği işaretle", "The essay argues ___ remote work increases productivity.", "", listOf("that", "what", "which"), listOf("that"), "Argue fiilinden sonra that-cümleciği gelir.", null, null),
                LearningExercise("b2v24e8", Skill.SPEAKING, "İfadeyi sesli söyle", "Say: Support every claim with evidence.", "", listOf(), listOf("Support every claim with evidence."), "Türkçesi: Her iddiayı kanıtla destekle.", "Support every claim with evidence.", "Support every claim with evidence."),
                LearningExercise("b2v24e9", Skill.WRITING, "Cümleyi İngilizce yaz", "İngilizcesi: Kaynaklarını doğru şekilde alıntıla.", "", listOf(), listOf("Cite your sources correctly."), "Örnek yanıt: Cite your sources correctly.", null, "Cite your sources correctly."))))))
}
