package com.linguapro.android

/** Hacim genişletme içerik paketi: A1 seviyesi (8 ünite, 24 ders). Otomatik derlenmiş, elle küratörlü banka. */
object CourseVolumeA1 {
    val units: List<LearningUnit> = listOf(
        LearningUnit("A1-U13", "Household Objects", "Name and locate common objects at home.", listOf(
            LearningLesson("A1-U13-L1", "Household Objects — Words", "Recognize key vocabulary for this topic.", listOf(
                LearningExercise("a1v13e1", Skill.VOCABULARY, "Doğru anlamı seç", "'table' ne anlama gelir?", "", listOf("sandalye", "ayna", "masa"), listOf("masa"), "The table is in the kitchen. — Masa mutfakta.", null, null),
                LearningExercise("a1v13e2", Skill.VOCABULARY, "Doğru anlamı seç", "'chair' ne anlama gelir?", "", listOf("anahtar", "sandalye", "lamba"), listOf("sandalye"), "There are four chairs in the room. — Odada dört sandalye var.", null, null),
                LearningExercise("a1v13e3", Skill.VOCABULARY, "Doğru anlamı seç", "'lamp' ne anlama gelir?", "", listOf("lamba", "ayna", "masa"), listOf("lamba"), "The lamp is next to the bed. — Lamba yatağın yanında.", null, null))),
            LearningLesson("A1-U13-L2", "Household Objects — In Use", "Use the new words in real sentences and listening.", listOf(
                LearningExercise("a1v13e4", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "The ___ is in the kitchen.", "", listOf("lamp", "table", "chair"), listOf("table"), "Doğru cümle: The table is in the kitchen. — Masa mutfakta.", null, null),
                LearningExercise("a1v13e5", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "The ___ is on the wall.", "", listOf("mirror", "key", "table"), listOf("mirror"), "Doğru cümle: The mirror is on the wall. — Ayna duvarda.", null, null),
                LearningExercise("a1v13e6", Skill.LISTENING, "Dinle ve anlamı seç", "Cümle ne anlatıyor?", "", listOf("Masa mutfakta.", "Lamba yatağın yanında.", "Anahtarlarım çantamda."), listOf("Anahtarlarım çantamda."), "Söylenen cümle: My keys are in my bag.", "My keys are in my bag.", null))),
            LearningLesson("A1-U13-L3", "Household Objects — Practice", "Apply the grammar focus, speak and write.", listOf(
                LearningExercise("a1v13e7", Skill.GRAMMAR, "Doğru seçeneği işaretle", "There ___ two chairs in the kitchen.", "", listOf("is", "are", "be"), listOf("are"), "Çoğul isimlerle there are kullanılır.", null, null),
                LearningExercise("a1v13e8", Skill.SPEAKING, "İfadeyi sesli söyle", "Say: There are four chairs in the room.", "", listOf(), listOf("There are four chairs in the room."), "Türkçesi: Odada dört sandalye var.", "There are four chairs in the room.", "There are four chairs in the room."),
                LearningExercise("a1v13e9", Skill.WRITING, "Cümleyi İngilizce yaz", "İngilizcesi: Lamba yatağın yanında.", "", listOf(), listOf("The lamp is next to the bed."), "Örnek yanıt: The lamp is next to the bed.", null, "The lamp is next to the bed."))))),
        LearningUnit("A1-U14", "Food & Drinks", "Order simple food and talk about meals.", listOf(
            LearningLesson("A1-U14-L1", "Food & Drinks — Words", "Recognize key vocabulary for this topic.", listOf(
                LearningExercise("a1v14e1", Skill.VOCABULARY, "Doğru anlamı seç", "'bread' ne anlama gelir?", "", listOf("peynir", "ekmek", "süt"), listOf("ekmek"), "We eat bread at breakfast. — Kahvaltıda ekmek yeriz.", null, null),
                LearningExercise("a1v14e2", Skill.VOCABULARY, "Doğru anlamı seç", "'milk' ne anlama gelir?", "", listOf("süt", "elma", "su"), listOf("süt"), "I drink milk every morning. — Her sabah süt içerim.", null, null),
                LearningExercise("a1v14e3", Skill.VOCABULARY, "Doğru anlamı seç", "'apple' ne anlama gelir?", "", listOf("peynir", "ekmek", "elma"), listOf("elma"), "She eats an apple after lunch. — Öğle yemeğinden sonra bir elma yer.", null, null))),
            LearningLesson("A1-U14-L2", "Food & Drinks — In Use", "Use the new words in real sentences and listening.", listOf(
                LearningExercise("a1v14e4", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "We eat ___ at breakfast.", "", listOf("bread", "milk", "apple"), listOf("bread"), "Doğru cümle: We eat bread at breakfast. — Kahvaltıda ekmek yeriz.", null, null),
                LearningExercise("a1v14e5", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "This ___ is very good.", "", listOf("water", "bread", "cheese"), listOf("cheese"), "Doğru cümle: This cheese is very good. — Bu peynir çok güzel.", null, null),
                LearningExercise("a1v14e6", Skill.LISTENING, "Dinle ve anlamı seç", "Cümle ne anlatıyor?", "", listOf("Öğle yemeğinden sonra bir elma yer.", "Biraz su alabilir miyim, lütfen?", "Kahvaltıda ekmek yeriz."), listOf("Biraz su alabilir miyim, lütfen?"), "Söylenen cümle: Can I have some water, please?", "Can I have some water, please?", null))),
            LearningLesson("A1-U14-L3", "Food & Drinks — Practice", "Apply the grammar focus, speak and write.", listOf(
                LearningExercise("a1v14e7", Skill.GRAMMAR, "Doğru seçeneği işaretle", "I would like ___ orange juice.", "", listOf("some", "many", "a few"), listOf("some"), "Sayılamayan isimlerle some kullanılır.", null, null),
                LearningExercise("a1v14e8", Skill.SPEAKING, "İfadeyi sesli söyle", "Say: I drink milk every morning.", "", listOf(), listOf("I drink milk every morning."), "Türkçesi: Her sabah süt içerim.", "I drink milk every morning.", "I drink milk every morning."),
                LearningExercise("a1v14e9", Skill.WRITING, "Cümleyi İngilizce yaz", "İngilizcesi: Öğle yemeğinden sonra bir elma yer.", "", listOf(), listOf("She eats an apple after lunch."), "Örnek yanıt: She eats an apple after lunch.", null, "She eats an apple after lunch."))))),
        LearningUnit("A1-U15", "Rooms of the Home", "Describe rooms and say where things are.", listOf(
            LearningLesson("A1-U15-L1", "Rooms of the Home — Words", "Recognize key vocabulary for this topic.", listOf(
                LearningExercise("a1v15e1", Skill.VOCABULARY, "Doğru anlamı seç", "'kitchen' ne anlama gelir?", "", listOf("mutfak", "banyo", "bahçe"), listOf("mutfak"), "My mother is in the kitchen. — Annem mutfakta.", null, null),
                LearningExercise("a1v15e2", Skill.VOCABULARY, "Doğru anlamı seç", "'bathroom' ne anlama gelir?", "", listOf("yatak odası", "pencere", "banyo"), listOf("banyo"), "The bathroom is upstairs. — Banyo üst katta.", null, null),
                LearningExercise("a1v15e3", Skill.VOCABULARY, "Doğru anlamı seç", "'bedroom' ne anlama gelir?", "", listOf("mutfak", "yatak odası", "bahçe"), listOf("yatak odası"), "My bedroom is small but nice. — Yatak odam küçük ama güzel.", null, null))),
            LearningLesson("A1-U15-L2", "Rooms of the Home — In Use", "Use the new words in real sentences and listening.", listOf(
                LearningExercise("a1v15e4", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "My mother is in the ___.", "", listOf("bathroom", "bedroom", "kitchen"), listOf("kitchen"), "Doğru cümle: My mother is in the kitchen. — Annem mutfakta.", null, null),
                LearningExercise("a1v15e5", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "The children play in the ___.", "", listOf("kitchen", "garden", "window"), listOf("garden"), "Doğru cümle: The children play in the garden. — Çocuklar bahçede oynar.", null, null),
                LearningExercise("a1v15e6", Skill.LISTENING, "Dinle ve anlamı seç", "Cümle ne anlatıyor?", "", listOf("Lütfen pencereyi aç.", "Annem mutfakta.", "Yatak odam küçük ama güzel."), listOf("Lütfen pencereyi aç."), "Söylenen cümle: Please open the window.", "Please open the window.", null))),
            LearningLesson("A1-U15-L3", "Rooms of the Home — Practice", "Apply the grammar focus, speak and write.", listOf(
                LearningExercise("a1v15e7", Skill.GRAMMAR, "Doğru seçeneği işaretle", "The cat is ___ the sofa.", "", listOf("on", "at", "to"), listOf("on"), "Bir yüzeyin üzerindeki konum için on kullanılır.", null, null),
                LearningExercise("a1v15e8", Skill.SPEAKING, "İfadeyi sesli söyle", "Say: The bathroom is upstairs.", "", listOf(), listOf("The bathroom is upstairs."), "Türkçesi: Banyo üst katta.", "The bathroom is upstairs.", "The bathroom is upstairs."),
                LearningExercise("a1v15e9", Skill.WRITING, "Cümleyi İngilizce yaz", "İngilizcesi: Yatak odam küçük ama güzel.", "", listOf(), listOf("My bedroom is small but nice."), "Örnek yanıt: My bedroom is small but nice.", null, "My bedroom is small but nice."))))),
        LearningUnit("A1-U16", "Around Town", "Name common places in a town.", listOf(
            LearningLesson("A1-U16-L1", "Around Town — Words", "Recognize key vocabulary for this topic.", listOf(
                LearningExercise("a1v16e1", Skill.VOCABULARY, "Doğru anlamı seç", "'school' ne anlama gelir?", "", listOf("hastane", "banka", "okul"), listOf("okul"), "The school is near my house. — Okul evimin yakınında.", null, null),
                LearningExercise("a1v16e2", Skill.VOCABULARY, "Doğru anlamı seç", "'hospital' ne anlama gelir?", "", listOf("park", "hastane", "pazar"), listOf("hastane"), "The hospital is on King Street. — Hastane King Caddesinde.", null, null),
                LearningExercise("a1v16e3", Skill.VOCABULARY, "Doğru anlamı seç", "'market' ne anlama gelir?", "", listOf("pazar", "banka", "okul"), listOf("pazar"), "We buy fruit at the market. — Meyveyi pazardan alırız.", null, null))),
            LearningLesson("A1-U16-L2", "Around Town — In Use", "Use the new words in real sentences and listening.", listOf(
                LearningExercise("a1v16e4", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "The ___ is near my house.", "", listOf("market", "school", "hospital"), listOf("school"), "Doğru cümle: The school is near my house. — Okul evimin yakınında.", null, null),
                LearningExercise("a1v16e5", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "The ___ opens at nine.", "", listOf("bank", "park", "school"), listOf("bank"), "Doğru cümle: The bank opens at nine. — Banka dokuzda açılır.", null, null),
                LearningExercise("a1v16e6", Skill.LISTENING, "Dinle ve anlamı seç", "Cümle ne anlatıyor?", "", listOf("Okul evimin yakınında.", "Meyveyi pazardan alırız.", "Her gün parkta yürürler."), listOf("Her gün parkta yürürler."), "Söylenen cümle: They walk in the park every day.", "They walk in the park every day.", null))),
            LearningLesson("A1-U16-L3", "Around Town — Practice", "Apply the grammar focus, speak and write.", listOf(
                LearningExercise("a1v16e7", Skill.GRAMMAR, "Doğru seçeneği işaretle", "___ there a pharmacy near here?", "", listOf("Is", "Are", "Do"), listOf("Is"), "Tekil isimlerle Is there...? sorusu kurulur.", null, null),
                LearningExercise("a1v16e8", Skill.SPEAKING, "İfadeyi sesli söyle", "Say: The hospital is on King Street.", "", listOf(), listOf("The hospital is on King Street."), "Türkçesi: Hastane King Caddesinde.", "The hospital is on King Street.", "The hospital is on King Street."),
                LearningExercise("a1v16e9", Skill.WRITING, "Cümleyi İngilizce yaz", "İngilizcesi: Meyveyi pazardan alırız.", "", listOf(), listOf("We buy fruit at the market."), "Örnek yanıt: We buy fruit at the market.", null, "We buy fruit at the market."))))),
        LearningUnit("A1-U17", "Days & Time", "Say days, months and tell the time.", listOf(
            LearningLesson("A1-U17-L1", "Days & Time — Words", "Recognize key vocabulary for this topic.", listOf(
                LearningExercise("a1v17e1", Skill.VOCABULARY, "Doğru anlamı seç", "'Monday' ne anlama gelir?", "", listOf("bugün", "Pazartesi", "hafta sonu"), listOf("Pazartesi"), "The lesson is on Monday. — Ders pazartesi günü.", null, null),
                LearningExercise("a1v17e2", Skill.VOCABULARY, "Doğru anlamı seç", "'weekend' ne anlama gelir?", "", listOf("hafta sonu", "ay", "saat"), listOf("hafta sonu"), "We relax at the weekend. — Hafta sonu dinleniriz.", null, null),
                LearningExercise("a1v17e3", Skill.VOCABULARY, "Doğru anlamı seç", "'month' ne anlama gelir?", "", listOf("bugün", "Pazartesi", "ay"), listOf("ay"), "January is the first month. — Ocak ilk aydır.", null, null))),
            LearningLesson("A1-U17-L2", "Days & Time — In Use", "Use the new words in real sentences and listening.", listOf(
                LearningExercise("a1v17e4", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "The lesson is on ___.", "", listOf("Monday", "weekend", "month"), listOf("Monday"), "Doğru cümle: The lesson is on Monday. — Ders pazartesi günü.", null, null),
                LearningExercise("a1v17e5", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "___ is my birthday.", "", listOf("clock", "Monday", "Today"), listOf("Today"), "Doğru cümle: Today is my birthday. — Bugün benim doğum günüm.", null, null),
                LearningExercise("a1v17e6", Skill.LISTENING, "Dinle ve anlamı seç", "Cümle ne anlatıyor?", "", listOf("Ocak ilk aydır.", "Saat duvarda.", "Ders pazartesi günü."), listOf("Saat duvarda."), "Söylenen cümle: The clock is on the wall.", "The clock is on the wall.", null))),
            LearningLesson("A1-U17-L3", "Days & Time — Practice", "Apply the grammar focus, speak and write.", listOf(
                LearningExercise("a1v17e7", Skill.GRAMMAR, "Doğru seçeneği işaretle", "My English class is ___ Tuesday.", "", listOf("on", "in", "at"), listOf("on"), "Günlerle on kullanılır: on Tuesday.", null, null),
                LearningExercise("a1v17e8", Skill.SPEAKING, "İfadeyi sesli söyle", "Say: We relax at the weekend.", "", listOf(), listOf("We relax at the weekend."), "Türkçesi: Hafta sonu dinleniriz.", "We relax at the weekend.", "We relax at the weekend."),
                LearningExercise("a1v17e9", Skill.WRITING, "Cümleyi İngilizce yaz", "İngilizcesi: Ocak ilk aydır.", "", listOf(), listOf("January is the first month."), "Örnek yanıt: January is the first month.", null, "January is the first month."))))),
        LearningUnit("A1-U18", "Clothes & Colours", "Talk about clothes and colours.", listOf(
            LearningLesson("A1-U18-L1", "Clothes & Colours — Words", "Recognize key vocabulary for this topic.", listOf(
                LearningExercise("a1v18e1", Skill.VOCABULARY, "Doğru anlamı seç", "'shirt' ne anlama gelir?", "", listOf("gömlek", "ayakkabı", "elbise"), listOf("gömlek"), "He wears a white shirt at work. — İşte beyaz bir gömlek giyer.", null, null),
                LearningExercise("a1v18e2", Skill.VOCABULARY, "Doğru anlamı seç", "'shoes' ne anlama gelir?", "", listOf("ceket", "şapka", "ayakkabı"), listOf("ayakkabı"), "These shoes are new. — Bu ayakkabılar yeni.", null, null),
                LearningExercise("a1v18e3", Skill.VOCABULARY, "Doğru anlamı seç", "'jacket' ne anlama gelir?", "", listOf("gömlek", "ceket", "elbise"), listOf("ceket"), "Take your jacket, it is cold. — Ceketini al, hava soğuk.", null, null))),
            LearningLesson("A1-U18-L2", "Clothes & Colours — In Use", "Use the new words in real sentences and listening.", listOf(
                LearningExercise("a1v18e4", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "He wears a white ___ at work.", "", listOf("shoes", "jacket", "shirt"), listOf("shirt"), "Doğru cümle: He wears a white shirt at work. — İşte beyaz bir gömlek giyer.", null, null),
                LearningExercise("a1v18e5", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "She likes her red ___.", "", listOf("shirt", "dress", "hat"), listOf("dress"), "Doğru cümle: She likes her red dress. — Kırmızı elbisesini seviyor.", null, null),
                LearningExercise("a1v18e6", Skill.LISTENING, "Dinle ve anlamı seç", "Cümle ne anlatıyor?", "", listOf("Çocuğun mavi bir şapkası var.", "İşte beyaz bir gömlek giyer.", "Ceketini al, hava soğuk."), listOf("Çocuğun mavi bir şapkası var."), "Söylenen cümle: The boy has a blue hat.", "The boy has a blue hat.", null))),
            LearningLesson("A1-U18-L3", "Clothes & Colours — Practice", "Apply the grammar focus, speak and write.", listOf(
                LearningExercise("a1v18e7", Skill.GRAMMAR, "Doğru seçeneği işaretle", "Whose jacket is this? It is ___.", "", listOf("hers", "her", "she"), listOf("hers"), "Sahiplik zamiri: hers = onunki.", null, null),
                LearningExercise("a1v18e8", Skill.SPEAKING, "İfadeyi sesli söyle", "Say: These shoes are new.", "", listOf(), listOf("These shoes are new."), "Türkçesi: Bu ayakkabılar yeni.", "These shoes are new.", "These shoes are new."),
                LearningExercise("a1v18e9", Skill.WRITING, "Cümleyi İngilizce yaz", "İngilizcesi: Ceketini al, hava soğuk.", "", listOf(), listOf("Take your jacket, it is cold."), "Örnek yanıt: Take your jacket, it is cold.", null, "Take your jacket, it is cold."))))),
        LearningUnit("A1-U19", "My Body & Health", "Name parts of the body and simple problems.", listOf(
            LearningLesson("A1-U19-L1", "My Body & Health — Words", "Recognize key vocabulary for this topic.", listOf(
                LearningExercise("a1v19e1", Skill.VOCABULARY, "Doğru anlamı seç", "'head' ne anlama gelir?", "", listOf("el", "diş", "baş"), listOf("baş"), "My head hurts. — Başım ağrıyor.", null, null),
                LearningExercise("a1v19e2", Skill.VOCABULARY, "Doğru anlamı seç", "'hand' ne anlama gelir?", "", listOf("doktor", "el", "göz"), listOf("el"), "Wash your hands before dinner. — Yemekten önce ellerini yıka.", null, null),
                LearningExercise("a1v19e3", Skill.VOCABULARY, "Doğru anlamı seç", "'eye' ne anlama gelir?", "", listOf("göz", "diş", "baş"), listOf("göz"), "She has green eyes. — Yeşil gözleri var.", null, null))),
            LearningLesson("A1-U19-L2", "My Body & Health — In Use", "Use the new words in real sentences and listening.", listOf(
                LearningExercise("a1v19e4", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "My ___ hurts.", "", listOf("eye", "head", "hand"), listOf("head"), "Doğru cümle: My head hurts. — Başım ağrıyor.", null, null),
                LearningExercise("a1v19e5", Skill.VOCABULARY, "Doğru anlamı seç", "'tooth' ne anlama gelir?", "", listOf("göz", "diş", "baş"), listOf("diş"), "Brush your teeth every night. — Her gece dişlerini fırçala.", null, null),
                LearningExercise("a1v19e6", Skill.LISTENING, "Dinle ve anlamı seç", "Cümle ne anlatıyor?", "", listOf("Başım ağrıyor.", "Yeşil gözleri var.", "Bir doktora görünmem gerek."), listOf("Bir doktora görünmem gerek."), "Söylenen cümle: I need to see a doctor.", "I need to see a doctor.", null))),
            LearningLesson("A1-U19-L3", "My Body & Health — Practice", "Apply the grammar focus, speak and write.", listOf(
                LearningExercise("a1v19e7", Skill.GRAMMAR, "Doğru seçeneği işaretle", "I ___ swim very well.", "", listOf("can", "am", "do"), listOf("can"), "Yetenek için can + fiilin yalın hali kullanılır.", null, null),
                LearningExercise("a1v19e8", Skill.SPEAKING, "İfadeyi sesli söyle", "Say: Wash your hands before dinner.", "", listOf(), listOf("Wash your hands before dinner."), "Türkçesi: Yemekten önce ellerini yıka.", "Wash your hands before dinner.", "Wash your hands before dinner."),
                LearningExercise("a1v19e9", Skill.WRITING, "Cümleyi İngilizce yaz", "İngilizcesi: Yeşil gözleri var.", "", listOf(), listOf("She has green eyes."), "Örnek yanıt: She has green eyes.", null, "She has green eyes."))))),
        LearningUnit("A1-U20", "Weather & Seasons", "Talk about the weather and seasons.", listOf(
            LearningLesson("A1-U20-L1", "Weather & Seasons — Words", "Recognize key vocabulary for this topic.", listOf(
                LearningExercise("a1v20e1", Skill.VOCABULARY, "Doğru anlamı seç", "'sunny' ne anlama gelir?", "", listOf("yaz", "güneşli", "yağmur"), listOf("güneşli"), "It is sunny today. — Bugün hava güneşli.", null, null),
                LearningExercise("a1v20e2", Skill.VOCABULARY, "Doğru anlamı seç", "'rain' ne anlama gelir?", "", listOf("yağmur", "kış", "rüzgar"), listOf("yağmur"), "Take an umbrella, there is rain. — Şemsiye al, yağmur var.", null, null),
                LearningExercise("a1v20e3", Skill.VOCABULARY, "Doğru anlamı seç", "'winter' ne anlama gelir?", "", listOf("yaz", "güneşli", "kış"), listOf("kış"), "Winter is very cold here. — Burada kış çok soğuk olur.", null, null))),
            LearningLesson("A1-U20-L2", "Weather & Seasons — In Use", "Use the new words in real sentences and listening.", listOf(
                LearningExercise("a1v20e4", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "It is ___ today.", "", listOf("sunny", "rain", "winter"), listOf("sunny"), "Doğru cümle: It is sunny today. — Bugün hava güneşli.", null, null),
                LearningExercise("a1v20e5", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "We go to the sea in ___.", "", listOf("wind", "sunny", "summer"), listOf("summer"), "Doğru cümle: We go to the sea in summer. — Yazın denize gideriz.", null, null),
                LearningExercise("a1v20e6", Skill.LISTENING, "Dinle ve anlamı seç", "Cümle ne anlatıyor?", "", listOf("Burada kış çok soğuk olur.", "Bu gece rüzgar kuvvetli.", "Bugün hava güneşli."), listOf("Bu gece rüzgar kuvvetli."), "Söylenen cümle: The wind is strong tonight.", "The wind is strong tonight.", null))),
            LearningLesson("A1-U20-L3", "Weather & Seasons — Practice", "Apply the grammar focus, speak and write.", listOf(
                LearningExercise("a1v20e7", Skill.GRAMMAR, "Doğru seçeneği işaretle", "It ___ raining now.", "", listOf("is", "are", "does"), listOf("is"), "Şu an olan eylem: it is raining (şimdiki zaman).", null, null),
                LearningExercise("a1v20e8", Skill.SPEAKING, "İfadeyi sesli söyle", "Say: Take an umbrella, there is rain.", "", listOf(), listOf("Take an umbrella, there is rain."), "Türkçesi: Şemsiye al, yağmur var.", "Take an umbrella, there is rain.", "Take an umbrella, there is rain."),
                LearningExercise("a1v20e9", Skill.WRITING, "Cümleyi İngilizce yaz", "İngilizcesi: Burada kış çok soğuk olur.", "", listOf(), listOf("Winter is very cold here."), "Örnek yanıt: Winter is very cold here.", null, "Winter is very cold here."))))))
}
