package com.linguapro.android

/** Hacim genişletme içerik paketi: B1 seviyesi (14 ünite, 42 ders). Otomatik derlenmiş, elle küratörlü banka. */
object CourseVolumeB1 {
    val units: List<LearningUnit> = listOf(
        LearningUnit("B1-U13", "Job Interviews", "Present yourself and answer common interview questions.", listOf(
            LearningLesson("B1-U13-L1", "Job Interviews — Words", "Recognize key vocabulary for this topic.", listOf(
                LearningExercise("b1v13e1", Skill.VOCABULARY, "Doğru anlamı seç", "'strength' ne anlama gelir?", "", listOf("deneyim", "maaş", "güçlü yön"), listOf("güçlü yön"), "My main strength is problem solving. — En güçlü yönüm problem çözmek.", null, null),
                LearningExercise("b1v13e2", Skill.VOCABULARY, "Doğru anlamı seç", "'experience' ne anlama gelir?", "", listOf("sorumluluk", "deneyim", "başvurmak"), listOf("deneyim"), "I have three years of experience in sales. — Satışta üç yıllık deneyimim var.", null, null),
                LearningExercise("b1v13e3", Skill.VOCABULARY, "Doğru anlamı seç", "'apply' ne anlama gelir?", "", listOf("başvurmak", "maaş", "güçlü yön"), listOf("başvurmak"), "I applied for the marketing position. — Pazarlama pozisyonuna başvurdum.", null, null))),
            LearningLesson("B1-U13-L2", "Job Interviews — In Use", "Use the new words in real sentences and listening.", listOf(
                LearningExercise("b1v13e4", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "My main ___ is problem solving.", "", listOf("apply", "strength", "experience"), listOf("strength"), "Doğru cümle: My main strength is problem solving. — En güçlü yönüm problem çözmek.", null, null),
                LearningExercise("b1v13e5", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "The ___ depends on experience.", "", listOf("salary", "responsibility", "strength"), listOf("salary"), "Doğru cümle: The salary depends on experience. — Maaş deneyime göre değişir.", null, null),
                LearningExercise("b1v13e6", Skill.LISTENING, "Dinle ve anlamı seç", "Cümle ne anlatıyor?", "", listOf("En güçlü yönüm problem çözmek.", "Pazarlama pozisyonuna başvurdum.", "Sorumluluklarım arasında müşteri desteği vardı."), listOf("Sorumluluklarım arasında müşteri desteği vardı."), "Söylenen cümle: My responsibilities included customer support.", "My responsibilities included customer support.", null),
                LearningExercise("b1v13e10", Skill.READING, "Cümleyi oku ve doğru anlamı seç", "Okuduğun cümle ne anlatıyor?", "The salary depends on experience.", listOf("Maaş deneyime göre değişir.", "Satışta üç yıllık deneyimim var.", "Sorumluluklarım arasında müşteri desteği vardı."), listOf("Maaş deneyime göre değişir."), "Cümlenin çevirisi: Maaş deneyime göre değişir.", null, null))),
            LearningLesson("B1-U13-L3", "Job Interviews — Practice", "Apply the grammar focus, speak and write.", listOf(
                LearningExercise("b1v13e7", Skill.GRAMMAR, "Doğru seçeneği işaretle", "I ___ in this company since 2021.", "", listOf("have worked", "work", "am working"), listOf("have worked"), "Since ile süregelen deneyim: present perfect kullanılır.", null, null),
                LearningExercise("b1v13e8", Skill.SPEAKING, "İfadeyi sesli söyle", "Say: I have three years of experience in sales.", "", listOf(), listOf("I have three years of experience in sales."), "Türkçesi: Satışta üç yıllık deneyimim var.", "I have three years of experience in sales.", "I have three years of experience in sales."),
                LearningExercise("b1v13e9", Skill.WRITING, "Cümleyi İngilizce yaz", "İngilizcesi: Pazarlama pozisyonuna başvurdum.", "", listOf(), listOf("I applied for the marketing position."), "Örnek yanıt: I applied for the marketing position.", null, "I applied for the marketing position."))))),
        LearningUnit("B1-U14", "Office Communication", "Write short messages and handle polite requests at work.", listOf(
            LearningLesson("B1-U14-L1", "Office Communication — Words", "Recognize key vocabulary for this topic.", listOf(
                LearningExercise("b1v14e1", Skill.VOCABULARY, "Doğru anlamı seç", "'attach' ne anlama gelir?", "", listOf("iletmek", "eklemek", "son teslim tarihi"), listOf("eklemek"), "I attached the report to this email. — Raporu bu e-postaya ekledim.", null, null),
                LearningExercise("b1v14e2", Skill.VOCABULARY, "Doğru anlamı seç", "'deadline' ne anlama gelir?", "", listOf("son teslim tarihi", "onaylamak", "acil"), listOf("son teslim tarihi"), "The deadline for the project is Friday. — Projenin son teslim tarihi cuma.", null, null),
                LearningExercise("b1v14e3", Skill.VOCABULARY, "Doğru anlamı seç", "'confirm' ne anlama gelir?", "", listOf("iletmek", "eklemek", "onaylamak"), listOf("onaylamak"), "Please confirm the meeting time. — Lütfen toplantı saatini onayla.", null, null))),
            LearningLesson("B1-U14-L2", "Office Communication — In Use", "Use the new words in real sentences and listening.", listOf(
                LearningExercise("b1v14e4", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "I ___ed the report to this email.", "", listOf("attach", "deadline", "confirm"), listOf("attach"), "Doğru cümle: I attached the report to this email. — Raporu bu e-postaya ekledim.", null, null),
                LearningExercise("b1v14e5", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "Could you ___ this message to the team?", "", listOf("urgent", "attach", "forward"), listOf("forward"), "Doğru cümle: Could you forward this message to the team? — Bu mesajı ekibe iletebilir misin?", null, null),
                LearningExercise("b1v14e6", Skill.LISTENING, "Dinle ve anlamı seç", "Cümle ne anlatıyor?", "", listOf("Lütfen toplantı saatini onayla.", "Bu talep acil.", "Raporu bu e-postaya ekledim."), listOf("Bu talep acil."), "Söylenen cümle: This request is urgent.", "This request is urgent.", null),
                LearningExercise("b1v14e10", Skill.READING, "Cümleyi oku ve doğru anlamı seç", "Okuduğun cümle ne anlatıyor?", "Could you forward this message to the team?", listOf("Projenin son teslim tarihi cuma.", "Bu talep acil.", "Bu mesajı ekibe iletebilir misin?"), listOf("Bu mesajı ekibe iletebilir misin?"), "Cümlenin çevirisi: Bu mesajı ekibe iletebilir misin?", null, null))),
            LearningLesson("B1-U14-L3", "Office Communication — Practice", "Apply the grammar focus, speak and write.", listOf(
                LearningExercise("b1v14e7", Skill.GRAMMAR, "Doğru seçeneği işaretle", "The report ___ every Monday morning.", "", listOf("is sent", "sends", "is sending"), listOf("is sent"), "Düzenli yapılan işte edilgen yapı: is sent.", null, null),
                LearningExercise("b1v14e8", Skill.SPEAKING, "İfadeyi sesli söyle", "Say: The deadline for the project is Friday.", "", listOf(), listOf("The deadline for the project is Friday."), "Türkçesi: Projenin son teslim tarihi cuma.", "The deadline for the project is Friday.", "The deadline for the project is Friday."),
                LearningExercise("b1v14e9", Skill.WRITING, "Cümleyi İngilizce yaz", "İngilizcesi: Lütfen toplantı saatini onayla.", "", listOf(), listOf("Please confirm the meeting time."), "Örnek yanıt: Please confirm the meeting time.", null, "Please confirm the meeting time."))))),
        LearningUnit("B1-U15", "News & Media", "Understand simple news stories and headlines.", listOf(
            LearningLesson("B1-U15-L1", "News & Media — Words", "Recognize key vocabulary for this topic.", listOf(
                LearningExercise("b1v15e1", Skill.VOCABULARY, "Doğru anlamı seç", "'headline' ne anlama gelir?", "", listOf("manşet", "röportaj", "izleyici kitlesi"), listOf("manşet"), "The headline was about the new bridge. — Manşet yeni köprüyle ilgiliydi.", null, null),
                LearningExercise("b1v15e2", Skill.VOCABULARY, "Doğru anlamı seç", "'interview' ne anlama gelir?", "", listOf("haber", "kaynak", "röportaj"), listOf("röportaj"), "The journalist did an interview with the mayor. — Gazeteci belediye başkanıyla röportaj yaptı.", null, null),
                LearningExercise("b1v15e3", Skill.VOCABULARY, "Doğru anlamı seç", "'report' ne anlama gelir?", "", listOf("manşet", "haber", "izleyici kitlesi"), listOf("haber"), "According to the report, prices will rise. — Habere göre fiyatlar artacak.", null, null))),
            LearningLesson("B1-U15-L2", "News & Media — In Use", "Use the new words in real sentences and listening.", listOf(
                LearningExercise("b1v15e4", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "The ___ was about the new bridge.", "", listOf("interview", "report", "headline"), listOf("headline"), "Doğru cümle: The headline was about the new bridge. — Manşet yeni köprüyle ilgiliydi.", null, null),
                LearningExercise("b1v15e5", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "The programme has a large ___.", "", listOf("headline", "audience", "source"), listOf("audience"), "Doğru cümle: The programme has a large audience. — Programın geniş bir izleyici kitlesi var.", null, null),
                LearningExercise("b1v15e6", Skill.LISTENING, "Dinle ve anlamı seç", "Cümle ne anlatıyor?", "", listOf("Haberin kaynağını her zaman kontrol et.", "Manşet yeni köprüyle ilgiliydi.", "Habere göre fiyatlar artacak."), listOf("Haberin kaynağını her zaman kontrol et."), "Söylenen cümle: Always check the source of the news.", "Always check the source of the news.", null),
                LearningExercise("b1v15e10", Skill.READING, "Cümleyi oku ve doğru anlamı seç", "Okuduğun cümle ne anlatıyor?", "The programme has a large audience.", listOf("Haberin kaynağını her zaman kontrol et.", "Programın geniş bir izleyici kitlesi var.", "Gazeteci belediye başkanıyla röportaj yaptı."), listOf("Programın geniş bir izleyici kitlesi var."), "Cümlenin çevirisi: Programın geniş bir izleyici kitlesi var.", null, null))),
            LearningLesson("B1-U15-L3", "News & Media — Practice", "Apply the grammar focus, speak and write.", listOf(
                LearningExercise("b1v15e7", Skill.GRAMMAR, "Doğru seçeneği işaretle", "The story, ___ appeared yesterday, surprised everyone.", "", listOf("which", "who", "what"), listOf("which"), "Cansız isimleri niteleyen ilgi zamiri which olur.", null, null),
                LearningExercise("b1v15e8", Skill.SPEAKING, "İfadeyi sesli söyle", "Say: The journalist did an interview with the mayor.", "", listOf(), listOf("The journalist did an interview with the mayor."), "Türkçesi: Gazeteci belediye başkanıyla röportaj yaptı.", "The journalist did an interview with the mayor.", "The journalist did an interview with the mayor."),
                LearningExercise("b1v15e9", Skill.WRITING, "Cümleyi İngilizce yaz", "İngilizcesi: Habere göre fiyatlar artacak.", "", listOf(), listOf("According to the report, prices will rise."), "Örnek yanıt: According to the report, prices will rise.", null, "According to the report, prices will rise."))))),
        LearningUnit("B1-U16", "Healthy Living", "Talk about habits, diet and simple health advice.", listOf(
            LearningLesson("B1-U16-L1", "Healthy Living — Words", "Recognize key vocabulary for this topic.", listOf(
                LearningExercise("b1v16e1", Skill.VOCABULARY, "Doğru anlamı seç", "'habit' ne anlama gelir?", "", listOf("dengeli", "stres", "alışkanlık"), listOf("alışkanlık"), "Walking is a healthy habit. — Yürümek sağlıklı bir alışkanlıktır.", null, null),
                LearningExercise("b1v16e2", Skill.VOCABULARY, "Doğru anlamı seç", "'balanced' ne anlama gelir?", "", listOf("uyku", "dengeli", "kaçınmak"), listOf("dengeli"), "Try to eat a balanced diet. — Dengeli beslenmeye çalış.", null, null),
                LearningExercise("b1v16e3", Skill.VOCABULARY, "Doğru anlamı seç", "'avoid' ne anlama gelir?", "", listOf("kaçınmak", "stres", "alışkanlık"), listOf("kaçınmak"), "You should avoid sugary drinks. — Şekerli içeceklerden kaçınmalısın.", null, null))),
            LearningLesson("B1-U16-L2", "Healthy Living — In Use", "Use the new words in real sentences and listening.", listOf(
                LearningExercise("b1v16e4", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "Walking is a healthy ___.", "", listOf("avoid", "habit", "balanced"), listOf("habit"), "Doğru cümle: Walking is a healthy habit. — Yürümek sağlıklı bir alışkanlıktır.", null, null),
                LearningExercise("b1v16e5", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "Exercise helps reduce ___.", "", listOf("stress", "sleep", "habit"), listOf("stress"), "Doğru cümle: Exercise helps reduce stress. — Egzersiz stresi azaltmaya yardımcı olur.", null, null),
                LearningExercise("b1v16e6", Skill.LISTENING, "Dinle ve anlamı seç", "Cümle ne anlatıyor?", "", listOf("Yürümek sağlıklı bir alışkanlıktır.", "Şekerli içeceklerden kaçınmalısın.", "İyi uyku hafızanı güçlendirir."), listOf("İyi uyku hafızanı güçlendirir."), "Söylenen cümle: Good sleep improves your memory.", "Good sleep improves your memory.", null),
                LearningExercise("b1v16e10", Skill.READING, "Cümleyi oku ve doğru anlamı seç", "Okuduğun cümle ne anlatıyor?", "Exercise helps reduce stress.", listOf("Egzersiz stresi azaltmaya yardımcı olur.", "Dengeli beslenmeye çalış.", "İyi uyku hafızanı güçlendirir."), listOf("Egzersiz stresi azaltmaya yardımcı olur."), "Cümlenin çevirisi: Egzersiz stresi azaltmaya yardımcı olur.", null, null))),
            LearningLesson("B1-U16-L3", "Healthy Living — Practice", "Apply the grammar focus, speak and write.", listOf(
                LearningExercise("b1v16e7", Skill.GRAMMAR, "Doğru seçeneği işaretle", "If you drink more water, you ___ better.", "", listOf("will feel", "felt", "would felt"), listOf("will feel"), "Birinci koşul: if + geniş zaman, will + fiil.", null, null),
                LearningExercise("b1v16e8", Skill.SPEAKING, "İfadeyi sesli söyle", "Say: Try to eat a balanced diet.", "", listOf(), listOf("Try to eat a balanced diet."), "Türkçesi: Dengeli beslenmeye çalış.", "Try to eat a balanced diet.", "Try to eat a balanced diet."),
                LearningExercise("b1v16e9", Skill.WRITING, "Cümleyi İngilizce yaz", "İngilizcesi: Şekerli içeceklerden kaçınmalısın.", "", listOf(), listOf("You should avoid sugary drinks."), "Örnek yanıt: You should avoid sugary drinks.", null, "You should avoid sugary drinks."))))),
        LearningUnit("B1-U17", "Education & Courses", "Discuss courses, exams and learning goals.", listOf(
            LearningLesson("B1-U17-L1", "Education & Courses — Words", "Recognize key vocabulary for this topic.", listOf(
                LearningExercise("b1v17e1", Skill.VOCABULARY, "Doğru anlamı seç", "'enrol' ne anlama gelir?", "", listOf("tekrar etmek", "kaydolmak", "sertifika"), listOf("kaydolmak"), "She enrolled in an online course. — Çevrim içi bir kursa kaydoldu.", null, null),
                LearningExercise("b1v17e2", Skill.VOCABULARY, "Doğru anlamı seç", "'certificate' ne anlama gelir?", "", listOf("sertifika", "geliştirmek", "başarısız olmak"), listOf("sertifika"), "You get a certificate at the end. — Sonunda bir sertifika alırsın.", null, null),
                LearningExercise("b1v17e3", Skill.VOCABULARY, "Doğru anlamı seç", "'improve' ne anlama gelir?", "", listOf("tekrar etmek", "kaydolmak", "geliştirmek"), listOf("geliştirmek"), "I want to improve my speaking. — Konuşmamı geliştirmek istiyorum.", null, null))),
            LearningLesson("B1-U17-L2", "Education & Courses — In Use", "Use the new words in real sentences and listening.", listOf(
                LearningExercise("b1v17e4", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "She ___led in an online course.", "", listOf("enrol", "certificate", "improve"), listOf("enrol"), "Doğru cümle: She enrolled in an online course. — Çevrim içi bir kursa kaydoldu.", null, null),
                LearningExercise("b1v17e5", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "We ___d the unit before the test.", "", listOf("fail", "enrol", "revise"), listOf("revise"), "Doğru cümle: We revised the unit before the test. — Testten önce üniteyi tekrar ettik.", null, null),
                LearningExercise("b1v17e6", Skill.LISTENING, "Dinle ve anlamı seç", "Cümle ne anlatıyor?", "", listOf("Konuşmamı geliştirmek istiyorum.", "İlk sınavda kaldı ama sonra geçti.", "Çevrim içi bir kursa kaydoldu."), listOf("İlk sınavda kaldı ama sonra geçti."), "Söylenen cümle: He failed the first exam but passed later.", "He failed the first exam but passed later.", null),
                LearningExercise("b1v17e10", Skill.READING, "Cümleyi oku ve doğru anlamı seç", "Okuduğun cümle ne anlatıyor?", "We revised the unit before the test.", listOf("Sonunda bir sertifika alırsın.", "İlk sınavda kaldı ama sonra geçti.", "Testten önce üniteyi tekrar ettik."), listOf("Testten önce üniteyi tekrar ettik."), "Cümlenin çevirisi: Testten önce üniteyi tekrar ettik.", null, null))),
            LearningLesson("B1-U17-L3", "Education & Courses — Practice", "Apply the grammar focus, speak and write.", listOf(
                LearningExercise("b1v17e7", Skill.GRAMMAR, "Doğru seçeneği işaretle", "She asked me ___ the course was difficult.", "", listOf("if", "that", "what"), listOf("if"), "Dolaylı evet-hayır sorusu if ile aktarılır.", null, null),
                LearningExercise("b1v17e8", Skill.SPEAKING, "İfadeyi sesli söyle", "Say: You get a certificate at the end.", "", listOf(), listOf("You get a certificate at the end."), "Türkçesi: Sonunda bir sertifika alırsın.", "You get a certificate at the end.", "You get a certificate at the end."),
                LearningExercise("b1v17e9", Skill.WRITING, "Cümleyi İngilizce yaz", "İngilizcesi: Konuşmamı geliştirmek istiyorum.", "", listOf(), listOf("I want to improve my speaking."), "Örnek yanıt: I want to improve my speaking.", null, "I want to improve my speaking."))))),
        LearningUnit("B1-U18", "City Life & Transport", "Compare transport options and city routines.", listOf(
            LearningLesson("B1-U18-L1", "City Life & Transport — Words", "Recognize key vocabulary for this topic.", listOf(
                LearningExercise("b1v18e1", Skill.VOCABULARY, "Doğru anlamı seç", "'commute' ne anlama gelir?", "", listOf("işe gidip gelmek", "kalabalık", "yol ücreti"), listOf("işe gidip gelmek"), "My commute takes forty minutes. — İşe gidip gelmem kırk dakika sürüyor.", null, null),
                LearningExercise("b1v18e2", Skill.VOCABULARY, "Doğru anlamı seç", "'crowded' ne anlama gelir?", "", listOf("trafik", "kullanışlı", "kalabalık"), listOf("kalabalık"), "The metro is crowded at eight. — Metro sekizde kalabalık oluyor.", null, null),
                LearningExercise("b1v18e3", Skill.VOCABULARY, "Doğru anlamı seç", "'traffic' ne anlama gelir?", "", listOf("işe gidip gelmek", "trafik", "yol ücreti"), listOf("trafik"), "Traffic is heavy on Monday mornings. — Pazartesi sabahları trafik yoğun.", null, null))),
            LearningLesson("B1-U18-L2", "City Life & Transport — In Use", "Use the new words in real sentences and listening.", listOf(
                LearningExercise("b1v18e4", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "My ___ takes forty minutes.", "", listOf("crowded", "traffic", "commute"), listOf("commute"), "Doğru cümle: My commute takes forty minutes. — İşe gidip gelmem kırk dakika sürüyor.", null, null),
                LearningExercise("b1v18e5", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "The bus ___ went up last month.", "", listOf("commute", "fare", "convenient"), listOf("fare"), "Doğru cümle: The bus fare went up last month. — Otobüs ücreti geçen ay arttı.", null, null),
                LearningExercise("b1v18e6", Skill.LISTENING, "Dinle ve anlamı seç", "Cümle ne anlatıyor?", "", listOf("Kısa yolculuklar için bisiklet kullanışlı.", "İşe gidip gelmem kırk dakika sürüyor.", "Pazartesi sabahları trafik yoğun."), listOf("Kısa yolculuklar için bisiklet kullanışlı."), "Söylenen cümle: Cycling is convenient for short trips.", "Cycling is convenient for short trips.", null),
                LearningExercise("b1v18e10", Skill.READING, "Cümleyi oku ve doğru anlamı seç", "Okuduğun cümle ne anlatıyor?", "The bus fare went up last month.", listOf("Kısa yolculuklar için bisiklet kullanışlı.", "Otobüs ücreti geçen ay arttı.", "Metro sekizde kalabalık oluyor."), listOf("Otobüs ücreti geçen ay arttı."), "Cümlenin çevirisi: Otobüs ücreti geçen ay arttı.", null, null))),
            LearningLesson("B1-U18-L3", "City Life & Transport — Practice", "Apply the grammar focus, speak and write.", listOf(
                LearningExercise("b1v18e7", Skill.GRAMMAR, "Doğru seçeneği işaretle", "You ___ buy a ticket before you get on the tram.", "", listOf("must", "might", "would"), listOf("must"), "Kural bildiren zorunluluk: must.", null, null),
                LearningExercise("b1v18e8", Skill.SPEAKING, "İfadeyi sesli söyle", "Say: The metro is crowded at eight.", "", listOf(), listOf("The metro is crowded at eight."), "Türkçesi: Metro sekizde kalabalık oluyor.", "The metro is crowded at eight.", "The metro is crowded at eight."),
                LearningExercise("b1v18e9", Skill.WRITING, "Cümleyi İngilizce yaz", "İngilizcesi: Pazartesi sabahları trafik yoğun.", "", listOf(), listOf("Traffic is heavy on Monday mornings."), "Örnek yanıt: Traffic is heavy on Monday mornings.", null, "Traffic is heavy on Monday mornings."))))),
        LearningUnit("B1-U19", "Money & Budgeting", "Talk about saving, spending and simple banking.", listOf(
            LearningLesson("B1-U19-L1", "Money & Budgeting — Words", "Recognize key vocabulary for this topic.", listOf(
                LearningExercise("b1v19e1", Skill.VOCABULARY, "Doğru anlamı seç", "'budget' ne anlama gelir?", "", listOf("biriktirmek", "hesap", "bütçe"), listOf("bütçe"), "We set a monthly budget for food. — Yemek için aylık bir bütçe belirledik.", null, null),
                LearningExercise("b1v19e2", Skill.VOCABULARY, "Doğru anlamı seç", "'save' ne anlama gelir?", "", listOf("fiş", "biriktirmek", "ödünç almak"), listOf("biriktirmek"), "I am saving for a new bike. — Yeni bir bisiklet için para biriktiriyorum.", null, null),
                LearningExercise("b1v19e3", Skill.VOCABULARY, "Doğru anlamı seç", "'borrow' ne anlama gelir?", "", listOf("ödünç almak", "hesap", "bütçe"), listOf("ödünç almak"), "Can I borrow some money until Friday? — Cumaya kadar biraz borç alabilir miyim?", null, null))),
            LearningLesson("B1-U19-L2", "Money & Budgeting — In Use", "Use the new words in real sentences and listening.", listOf(
                LearningExercise("b1v19e4", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "We set a monthly ___ for food.", "", listOf("borrow", "budget", "save"), listOf("budget"), "Doğru cümle: We set a monthly budget for food. — Yemek için aylık bir bütçe belirledik.", null, null),
                LearningExercise("b1v19e5", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "I opened a bank ___ last week.", "", listOf("account", "receipt", "budget"), listOf("account"), "Doğru cümle: I opened a bank account last week. — Geçen hafta bir banka hesabı açtım.", null, null),
                LearningExercise("b1v19e6", Skill.LISTENING, "Dinle ve anlamı seç", "Cümle ne anlatıyor?", "", listOf("Yemek için aylık bir bütçe belirledik.", "Cumaya kadar biraz borç alabilir miyim?", "İade ihtimaline karşı fişi sakla."), listOf("İade ihtimaline karşı fişi sakla."), "Söylenen cümle: Keep the receipt in case you return it.", "Keep the receipt in case you return it.", null),
                LearningExercise("b1v19e10", Skill.READING, "Cümleyi oku ve doğru anlamı seç", "Okuduğun cümle ne anlatıyor?", "I opened a bank account last week.", listOf("Geçen hafta bir banka hesabı açtım.", "Yeni bir bisiklet için para biriktiriyorum.", "İade ihtimaline karşı fişi sakla."), listOf("Geçen hafta bir banka hesabı açtım."), "Cümlenin çevirisi: Geçen hafta bir banka hesabı açtım.", null, null))),
            LearningLesson("B1-U19-L3", "Money & Budgeting — Practice", "Apply the grammar focus, speak and write.", listOf(
                LearningExercise("b1v19e7", Skill.GRAMMAR, "Doğru seçeneği işaretle", "If I had more money, I ___ travel more.", "", listOf("would", "will", "can"), listOf("would"), "İkinci koşul: hayalî durumda would kullanılır.", null, null),
                LearningExercise("b1v19e8", Skill.SPEAKING, "İfadeyi sesli söyle", "Say: I am saving for a new bike.", "", listOf(), listOf("I am saving for a new bike."), "Türkçesi: Yeni bir bisiklet için para biriktiriyorum.", "I am saving for a new bike.", "I am saving for a new bike."),
                LearningExercise("b1v19e9", Skill.WRITING, "Cümleyi İngilizce yaz", "İngilizcesi: Cumaya kadar biraz borç alabilir miyim?", "", listOf(), listOf("Can I borrow some money until Friday?"), "Örnek yanıt: Can I borrow some money until Friday?", null, "Can I borrow some money until Friday?"))))),
        LearningUnit("B1-U20", "Films & Culture", "Describe films, books and cultural events.", listOf(
            LearningLesson("B1-U20-L1", "Films & Culture — Words", "Recognize key vocabulary for this topic.", listOf(
                LearningExercise("b1v20e1", Skill.VOCABULARY, "Doğru anlamı seç", "'plot' ne anlama gelir?", "", listOf("sahnelemek", "konu", "karakter"), listOf("konu"), "The plot of the film was exciting. — Filmin konusu heyecan vericiydi.", null, null),
                LearningExercise("b1v20e2", Skill.VOCABULARY, "Doğru anlamı seç", "'character' ne anlama gelir?", "", listOf("karakter", "inceleme", "sergi"), listOf("karakter"), "The main character is a young doctor. — Ana karakter genç bir doktor.", null, null),
                LearningExercise("b1v20e3", Skill.VOCABULARY, "Doğru anlamı seç", "'review' ne anlama gelir?", "", listOf("sahnelemek", "konu", "inceleme"), listOf("inceleme"), "The reviews of the book were positive. — Kitabın incelemeleri olumluydu.", null, null))),
            LearningLesson("B1-U20-L2", "Films & Culture — In Use", "Use the new words in real sentences and listening.", listOf(
                LearningExercise("b1v20e4", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "The ___ of the film was exciting.", "", listOf("plot", "character", "review"), listOf("plot"), "Doğru cümle: The plot of the film was exciting. — Filmin konusu heyecan vericiydi.", null, null),
                LearningExercise("b1v20e5", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "The band ___ed in the old theatre.", "", listOf("exhibition", "plot", "perform"), listOf("perform"), "Doğru cümle: The band performed in the old theatre. — Grup eski tiyatroda sahne aldı.", null, null),
                LearningExercise("b1v20e6", Skill.LISTENING, "Dinle ve anlamı seç", "Cümle ne anlatıyor?", "", listOf("Kitabın incelemeleri olumluydu.", "Bir fotoğraf sergisini gezdik.", "Filmin konusu heyecan vericiydi."), listOf("Bir fotoğraf sergisini gezdik."), "Söylenen cümle: We visited a photography exhibition.", "We visited a photography exhibition.", null),
                LearningExercise("b1v20e10", Skill.READING, "Cümleyi oku ve doğru anlamı seç", "Okuduğun cümle ne anlatıyor?", "The band performed in the old theatre.", listOf("Ana karakter genç bir doktor.", "Bir fotoğraf sergisini gezdik.", "Grup eski tiyatroda sahne aldı."), listOf("Grup eski tiyatroda sahne aldı."), "Cümlenin çevirisi: Grup eski tiyatroda sahne aldı.", null, null))),
            LearningLesson("B1-U20-L3", "Films & Culture — Practice", "Apply the grammar focus, speak and write.", listOf(
                LearningExercise("b1v20e7", Skill.GRAMMAR, "Doğru seçeneği işaretle", "The film ___ by a famous director.", "", listOf("was made", "made", "is making"), listOf("was made"), "Geçmişte edilgen yapı: was made.", null, null),
                LearningExercise("b1v20e8", Skill.SPEAKING, "İfadeyi sesli söyle", "Say: The main character is a young doctor.", "", listOf(), listOf("The main character is a young doctor."), "Türkçesi: Ana karakter genç bir doktor.", "The main character is a young doctor.", "The main character is a young doctor."),
                LearningExercise("b1v20e9", Skill.WRITING, "Cümleyi İngilizce yaz", "İngilizcesi: Kitabın incelemeleri olumluydu.", "", listOf(), listOf("The reviews of the book were positive."), "Örnek yanıt: The reviews of the book were positive.", null, "The reviews of the book were positive."))))),
        LearningUnit("B1-U21", "Social Media & Internet", "Discuss online habits and digital safety.", listOf(
            LearningLesson("B1-U21-L1", "Social Media & Internet — Words", "Recognize key vocabulary for this topic.", listOf(
                LearningExercise("b1v21e1", Skill.VOCABULARY, "Doğru anlamı seç", "'share' ne anlama gelir?", "", listOf("paylaşmak", "hesap", "gizlilik"), listOf("paylaşmak"), "Think before you share personal photos. — Kişisel fotoğrafları paylaşmadan önce düşün.", null, null),
                LearningExercise("b1v21e2", Skill.VOCABULARY, "Doğru anlamı seç", "'account' ne anlama gelir?", "", listOf("yorum", "takip etmek", "hesap"), listOf("hesap"), "She deleted her old social media account. — Eski sosyal medya hesabını sildi.", null, null),
                LearningExercise("b1v21e3", Skill.VOCABULARY, "Doğru anlamı seç", "'comment' ne anlama gelir?", "", listOf("paylaşmak", "yorum", "gizlilik"), listOf("yorum"), "He left a kind comment under the video. — Videonun altına nazik bir yorum bıraktı.", null, null))),
            LearningLesson("B1-U21-L2", "Social Media & Internet — In Use", "Use the new words in real sentences and listening.", listOf(
                LearningExercise("b1v21e4", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "Think before you ___ personal photos.", "", listOf("account", "comment", "share"), listOf("share"), "Doğru cümle: Think before you share personal photos. — Kişisel fotoğrafları paylaşmadan önce düşün.", null, null),
                LearningExercise("b1v21e5", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "Check your ___ settings regularly.", "", listOf("share", "privacy", "follow"), listOf("privacy"), "Doğru cümle: Check your privacy settings regularly. — Gizlilik ayarlarını düzenli kontrol et.", null, null),
                LearningExercise("b1v21e6", Skill.LISTENING, "Dinle ve anlamı seç", "Cümle ne anlatıyor?", "", listOf("Birkaç haber sayfasını takip ediyorum.", "Kişisel fotoğrafları paylaşmadan önce düşün.", "Videonun altına nazik bir yorum bıraktı."), listOf("Birkaç haber sayfasını takip ediyorum."), "Söylenen cümle: I follow several news pages.", "I follow several news pages.", null),
                LearningExercise("b1v21e10", Skill.READING, "Cümleyi oku ve doğru anlamı seç", "Okuduğun cümle ne anlatıyor?", "Check your privacy settings regularly.", listOf("Birkaç haber sayfasını takip ediyorum.", "Gizlilik ayarlarını düzenli kontrol et.", "Eski sosyal medya hesabını sildi."), listOf("Gizlilik ayarlarını düzenli kontrol et."), "Cümlenin çevirisi: Gizlilik ayarlarını düzenli kontrol et.", null, null))),
            LearningLesson("B1-U21-L3", "Social Media & Internet — Practice", "Apply the grammar focus, speak and write.", listOf(
                LearningExercise("b1v21e7", Skill.GRAMMAR, "Doğru seçeneği işaretle", "You should not share your password, ___?", "", listOf("should you", "do you", "are you"), listOf("should you"), "Olumsuz cümlenin eklenti sorusu olumlu olur: should you?", null, null),
                LearningExercise("b1v21e8", Skill.SPEAKING, "İfadeyi sesli söyle", "Say: She deleted her old social media account.", "", listOf(), listOf("She deleted her old social media account."), "Türkçesi: Eski sosyal medya hesabını sildi.", "She deleted her old social media account.", "She deleted her old social media account."),
                LearningExercise("b1v21e9", Skill.WRITING, "Cümleyi İngilizce yaz", "İngilizcesi: Videonun altına nazik bir yorum bıraktı.", "", listOf(), listOf("He left a kind comment under the video."), "Örnek yanıt: He left a kind comment under the video.", null, "He left a kind comment under the video."))))),
        LearningUnit("B1-U22", "Environment & Recycling", "Talk about environmental problems and habits.", listOf(
            LearningLesson("B1-U22-L1", "Environment & Recycling — Words", "Recognize key vocabulary for this topic.", listOf(
                LearningExercise("b1v22e1", Skill.VOCABULARY, "Doğru anlamı seç", "'recycle' ne anlama gelir?", "", listOf("kirlilik", "plastik", "geri dönüştürmek"), listOf("geri dönüştürmek"), "We recycle glass and paper at home. — Evde cam ve kağıdı geri dönüştürürüz.", null, null),
                LearningExercise("b1v22e2", Skill.VOCABULARY, "Doğru anlamı seç", "'pollution' ne anlama gelir?", "", listOf("enerji", "kirlilik", "israf etmek"), listOf("kirlilik"), "Air pollution is a serious problem here. — Hava kirliliği burada ciddi bir sorun.", null, null),
                LearningExercise("b1v22e3", Skill.VOCABULARY, "Doğru anlamı seç", "'waste' ne anlama gelir?", "", listOf("israf etmek", "plastik", "geri dönüştürmek"), listOf("israf etmek"), "Do not waste water while brushing. — Diş fırçalarken suyu israf etme.", null, null))),
            LearningLesson("B1-U22-L2", "Environment & Recycling — In Use", "Use the new words in real sentences and listening.", listOf(
                LearningExercise("b1v22e4", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "We ___ glass and paper at home.", "", listOf("waste", "recycle", "pollution"), listOf("recycle"), "Doğru cümle: We recycle glass and paper at home. — Evde cam ve kağıdı geri dönüştürürüz.", null, null),
                LearningExercise("b1v22e5", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "Single-use ___ should be reduced.", "", listOf("plastic", "energy", "recycle"), listOf("plastic"), "Doğru cümle: Single-use plastic should be reduced. — Tek kullanımlık plastik azaltılmalı.", null, null),
                LearningExercise("b1v22e6", Skill.LISTENING, "Dinle ve anlamı seç", "Cümle ne anlatıyor?", "", listOf("Evde cam ve kağıdı geri dönüştürürüz.", "Diş fırçalarken suyu israf etme.", "Güneş enerjisi giderek ucuzluyor."), listOf("Güneş enerjisi giderek ucuzluyor."), "Söylenen cümle: Solar energy is becoming cheaper.", "Solar energy is becoming cheaper.", null),
                LearningExercise("b1v22e10", Skill.READING, "Cümleyi oku ve doğru anlamı seç", "Okuduğun cümle ne anlatıyor?", "Single-use plastic should be reduced.", listOf("Tek kullanımlık plastik azaltılmalı.", "Hava kirliliği burada ciddi bir sorun.", "Güneş enerjisi giderek ucuzluyor."), listOf("Tek kullanımlık plastik azaltılmalı."), "Cümlenin çevirisi: Tek kullanımlık plastik azaltılmalı.", null, null))),
            LearningLesson("B1-U22-L3", "Environment & Recycling — Practice", "Apply the grammar focus, speak and write.", listOf(
                LearningExercise("b1v22e7", Skill.GRAMMAR, "Doğru seçeneği işaretle", "Plastic bags ___ in many cities now.", "", listOf("are banned", "ban", "banned are"), listOf("are banned"), "Genel kural edilgen: are banned.", null, null),
                LearningExercise("b1v22e8", Skill.SPEAKING, "İfadeyi sesli söyle", "Say: Air pollution is a serious problem here.", "", listOf(), listOf("Air pollution is a serious problem here."), "Türkçesi: Hava kirliliği burada ciddi bir sorun.", "Air pollution is a serious problem here.", "Air pollution is a serious problem here."),
                LearningExercise("b1v22e9", Skill.WRITING, "Cümleyi İngilizce yaz", "İngilizcesi: Diş fırçalarken suyu israf etme.", "", listOf(), listOf("Do not waste water while brushing."), "Örnek yanıt: Do not waste water while brushing.", null, "Do not waste water while brushing."))))),
        LearningUnit("B1-U23", "Community & Neighbours", "Handle everyday situations with neighbours.", listOf(
            LearningLesson("B1-U23-L1", "Community & Neighbours — Words", "Recognize key vocabulary for this topic.", listOf(
                LearningExercise("b1v23e1", Skill.VOCABULARY, "Doğru anlamı seç", "'neighbour' ne anlama gelir?", "", listOf("şikayet etmek", "komşu", "gürültü"), listOf("komşu"), "Our neighbours are very friendly. — Komşularımız çok cana yakın.", null, null),
                LearningExercise("b1v23e2", Skill.VOCABULARY, "Doğru anlamı seç", "'noise' ne anlama gelir?", "", listOf("gürültü", "iyilik", "gönüllü"), listOf("gürültü"), "The noise from upstairs woke me up. — Üst kattan gelen gürültü beni uyandırdı.", null, null),
                LearningExercise("b1v23e3", Skill.VOCABULARY, "Doğru anlamı seç", "'favour' ne anlama gelir?", "", listOf("şikayet etmek", "komşu", "iyilik"), listOf("iyilik"), "Could you do me a small favour? — Bana küçük bir iyilik yapabilir misin?", null, null))),
            LearningLesson("B1-U23-L2", "Community & Neighbours — In Use", "Use the new words in real sentences and listening.", listOf(
                LearningExercise("b1v23e4", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "Our ___s are very friendly.", "", listOf("neighbour", "noise", "favour"), listOf("neighbour"), "Doğru cümle: Our neighbours are very friendly. — Komşularımız çok cana yakın.", null, null),
                LearningExercise("b1v23e5", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "He ___ed about the broken lift.", "", listOf("volunteer", "neighbour", "complain"), listOf("complain"), "Doğru cümle: He complained about the broken lift. — Bozuk asansörü şikayet etti.", null, null),
                LearningExercise("b1v23e6", Skill.LISTENING, "Dinle ve anlamı seç", "Cümle ne anlatıyor?", "", listOf("Bana küçük bir iyilik yapabilir misin?", "Yerel kütüphanede gönüllü çalışıyor.", "Komşularımız çok cana yakın."), listOf("Yerel kütüphanede gönüllü çalışıyor."), "Söylenen cümle: She volunteers at the local library.", "She volunteers at the local library.", null),
                LearningExercise("b1v23e10", Skill.READING, "Cümleyi oku ve doğru anlamı seç", "Okuduğun cümle ne anlatıyor?", "He complained about the broken lift.", listOf("Üst kattan gelen gürültü beni uyandırdı.", "Yerel kütüphanede gönüllü çalışıyor.", "Bozuk asansörü şikayet etti."), listOf("Bozuk asansörü şikayet etti."), "Cümlenin çevirisi: Bozuk asansörü şikayet etti.", null, null))),
            LearningLesson("B1-U23-L3", "Community & Neighbours — Practice", "Apply the grammar focus, speak and write.", listOf(
                LearningExercise("b1v23e7", Skill.GRAMMAR, "Doğru seçeneği işaretle", "I wish the music upstairs ___ quieter.", "", listOf("were", "is", "be"), listOf("were"), "Wish ile şimdiki hayıflanma: wish + geçmiş biçim.", null, null),
                LearningExercise("b1v23e8", Skill.SPEAKING, "İfadeyi sesli söyle", "Say: The noise from upstairs woke me up.", "", listOf(), listOf("The noise from upstairs woke me up."), "Türkçesi: Üst kattan gelen gürültü beni uyandırdı.", "The noise from upstairs woke me up.", "The noise from upstairs woke me up."),
                LearningExercise("b1v23e9", Skill.WRITING, "Cümleyi İngilizce yaz", "İngilizcesi: Bana küçük bir iyilik yapabilir misin?", "", listOf(), listOf("Could you do me a small favour?"), "Örnek yanıt: Could you do me a small favour?", null, "Could you do me a small favour?"))))),
        LearningUnit("B1-U24", "Travel Problems", "Solve common problems while travelling.", listOf(
            LearningLesson("B1-U24-L1", "Travel Problems — Words", "Recognize key vocabulary for this topic.", listOf(
                LearningExercise("b1v24e1", Skill.VOCABULARY, "Doğru anlamı seç", "'delay' ne anlama gelir?", "", listOf("rötar", "kaçırmak", "sigorta"), listOf("rötar"), "Our flight had a two-hour delay. — Uçuşumuz iki saat rötar yaptı.", null, null),
                LearningExercise("b1v24e2", Skill.VOCABULARY, "Doğru anlamı seç", "'miss' ne anlama gelir?", "", listOf("geri ödeme", "büyükelçilik", "kaçırmak"), listOf("kaçırmak"), "We almost missed the connection. — Aktarmayı az kalsın kaçırıyorduk.", null, null),
                LearningExercise("b1v24e3", Skill.VOCABULARY, "Doğru anlamı seç", "'refund' ne anlama gelir?", "", listOf("rötar", "geri ödeme", "sigorta"), listOf("geri ödeme"), "I asked for a refund for the ticket. — Bilet için geri ödeme istedim.", null, null))),
            LearningLesson("B1-U24-L2", "Travel Problems — In Use", "Use the new words in real sentences and listening.", listOf(
                LearningExercise("b1v24e4", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "Our flight had a two-hour ___.", "", listOf("miss", "refund", "delay"), listOf("delay"), "Doğru cümle: Our flight had a two-hour delay. — Uçuşumuz iki saat rötar yaptı.", null, null),
                LearningExercise("b1v24e5", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "Travel ___ saved us a lot of money.", "", listOf("delay", "insurance", "embassy"), listOf("insurance"), "Doğru cümle: Travel insurance saved us a lot of money. — Seyahat sigortası bize çok para kazandırdı.", null, null),
                LearningExercise("b1v24e6", Skill.LISTENING, "Dinle ve anlamı seç", "Cümle ne anlatıyor?", "", listOf("Pasaportunu kaybetti ve büyükelçiliği aradı.", "Uçuşumuz iki saat rötar yaptı.", "Bilet için geri ödeme istedim."), listOf("Pasaportunu kaybetti ve büyükelçiliği aradı."), "Söylenen cümle: He lost his passport and called the embassy.", "He lost his passport and called the embassy.", null),
                LearningExercise("b1v24e10", Skill.READING, "Cümleyi oku ve doğru anlamı seç", "Okuduğun cümle ne anlatıyor?", "Travel insurance saved us a lot of money.", listOf("Pasaportunu kaybetti ve büyükelçiliği aradı.", "Seyahat sigortası bize çok para kazandırdı.", "Aktarmayı az kalsın kaçırıyorduk."), listOf("Seyahat sigortası bize çok para kazandırdı."), "Cümlenin çevirisi: Seyahat sigortası bize çok para kazandırdı.", null, null))),
            LearningLesson("B1-U24-L3", "Travel Problems — Practice", "Apply the grammar focus, speak and write.", listOf(
                LearningExercise("b1v24e7", Skill.GRAMMAR, "Doğru seçeneği işaretle", "By the time we arrived, the bus ___.", "", listOf("had left", "left", "has left"), listOf("had left"), "Geçmişte daha önce olan eylem: past perfect.", null, null),
                LearningExercise("b1v24e8", Skill.SPEAKING, "İfadeyi sesli söyle", "Say: We almost missed the connection.", "", listOf(), listOf("We almost missed the connection."), "Türkçesi: Aktarmayı az kalsın kaçırıyorduk.", "We almost missed the connection.", "We almost missed the connection."),
                LearningExercise("b1v24e9", Skill.WRITING, "Cümleyi İngilizce yaz", "İngilizcesi: Bilet için geri ödeme istedim.", "", listOf(), listOf("I asked for a refund for the ticket."), "Örnek yanıt: I asked for a refund for the ticket.", null, "I asked for a refund for the ticket."))))),
        LearningUnit("B1-U25", "Food Culture & Cooking", "Describe recipes and eating habits.", listOf(
            LearningLesson("B1-U25-L1", "Food Culture & Cooking — Words", "Recognize key vocabulary for this topic.", listOf(
                LearningExercise("b1v25e1", Skill.VOCABULARY, "Doğru anlamı seç", "'recipe' ne anlama gelir?", "", listOf("malzeme", "tat", "tarif"), listOf("tarif"), "This soup recipe is from my grandmother. — Bu çorba tarifi babaannemden.", null, null),
                LearningExercise("b1v25e2", Skill.VOCABULARY, "Doğru anlamı seç", "'ingredient' ne anlama gelir?", "", listOf("geleneksel", "malzeme", "haşlamak"), listOf("malzeme"), "The main ingredient is fresh basil. — Ana malzeme taze fesleğen.", null, null),
                LearningExercise("b1v25e3", Skill.VOCABULARY, "Doğru anlamı seç", "'boil' ne anlama gelir?", "", listOf("haşlamak", "tat", "tarif"), listOf("haşlamak"), "Boil the potatoes for ten minutes. — Patatesleri on dakika haşla.", null, null))),
            LearningLesson("B1-U25-L2", "Food Culture & Cooking — In Use", "Use the new words in real sentences and listening.", listOf(
                LearningExercise("b1v25e4", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "This soup ___ is from my grandmother.", "", listOf("boil", "recipe", "ingredient"), listOf("recipe"), "Doğru cümle: This soup recipe is from my grandmother. — Bu çorba tarifi babaannemden.", null, null),
                LearningExercise("b1v25e5", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "The sauce has a rich ___.", "", listOf("taste", "traditional", "recipe"), listOf("taste"), "Doğru cümle: The sauce has a rich taste. — Sosun zengin bir tadı var.", null, null),
                LearningExercise("b1v25e6", Skill.LISTENING, "Dinle ve anlamı seç", "Cümle ne anlatıyor?", "", listOf("Bu çorba tarifi babaannemden.", "Patatesleri on dakika haşla.", "Kuzeye özgü geleneksel bir yemek."), listOf("Kuzeye özgü geleneksel bir yemek."), "Söylenen cümle: It is a traditional dish from the north.", "It is a traditional dish from the north.", null),
                LearningExercise("b1v25e10", Skill.READING, "Cümleyi oku ve doğru anlamı seç", "Okuduğun cümle ne anlatıyor?", "The sauce has a rich taste.", listOf("Sosun zengin bir tadı var.", "Ana malzeme taze fesleğen.", "Kuzeye özgü geleneksel bir yemek."), listOf("Sosun zengin bir tadı var."), "Cümlenin çevirisi: Sosun zengin bir tadı var.", null, null))),
            LearningLesson("B1-U25-L3", "Food Culture & Cooking — Practice", "Apply the grammar focus, speak and write.", listOf(
                LearningExercise("b1v25e7", Skill.GRAMMAR, "Doğru seçeneği işaretle", "The cake smells ___.", "", listOf("wonderful", "wonderfully", "wonder"), listOf("wonderful"), "Duyu fiillerinden sonra sıfat gelir: smells wonderful.", null, null),
                LearningExercise("b1v25e8", Skill.SPEAKING, "İfadeyi sesli söyle", "Say: The main ingredient is fresh basil.", "", listOf(), listOf("The main ingredient is fresh basil."), "Türkçesi: Ana malzeme taze fesleğen.", "The main ingredient is fresh basil.", "The main ingredient is fresh basil."),
                LearningExercise("b1v25e9", Skill.WRITING, "Cümleyi İngilizce yaz", "İngilizcesi: Patatesleri on dakika haşla.", "", listOf(), listOf("Boil the potatoes for ten minutes."), "Örnek yanıt: Boil the potatoes for ten minutes.", null, "Boil the potatoes for ten minutes."))))),
        LearningUnit("B1-U26", "Goals & Plans", "Describe personal goals and intentions clearly.", listOf(
            LearningLesson("B1-U26-L1", "Goals & Plans — Words", "Recognize key vocabulary for this topic.", listOf(
                LearningExercise("b1v26e1", Skill.VOCABULARY, "Doğru anlamı seç", "'goal' ne anlama gelir?", "", listOf("vazgeçmek", "hedef", "başarmak"), listOf("hedef"), "My goal is to speak English fluently. — Hedefim akıcı İngilizce konuşmak.", null, null),
                LearningExercise("b1v26e2", Skill.VOCABULARY, "Doğru anlamı seç", "'achieve' ne anlama gelir?", "", listOf("başarmak", "karar vermek", "ilerleme"), listOf("başarmak"), "She achieved everything she planned. — Planladığı her şeyi başardı.", null, null),
                LearningExercise("b1v26e3", Skill.VOCABULARY, "Doğru anlamı seç", "'decide' ne anlama gelir?", "", listOf("vazgeçmek", "hedef", "karar vermek"), listOf("karar vermek"), "I decided to take a gap year. — Bir yıl ara vermeye karar verdim.", null, null))),
            LearningLesson("B1-U26-L2", "Goals & Plans — In Use", "Use the new words in real sentences and listening.", listOf(
                LearningExercise("b1v26e4", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "My ___ is to speak English fluently.", "", listOf("goal", "achieve", "decide"), listOf("goal"), "Doğru cümle: My goal is to speak English fluently. — Hedefim akıcı İngilizce konuşmak.", null, null),
                LearningExercise("b1v26e5", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "Never ___ on your dreams.", "", listOf("progress", "goal", "give up"), listOf("give up"), "Doğru cümle: Never give up on your dreams. — Hayallerinden asla vazgeçme.", null, null),
                LearningExercise("b1v26e6", Skill.LISTENING, "Dinle ve anlamı seç", "Cümle ne anlatıyor?", "", listOf("Bir yıl ara vermeye karar verdim.", "Yazmamda gerçek bir ilerleme görüyorum.", "Hedefim akıcı İngilizce konuşmak."), listOf("Yazmamda gerçek bir ilerleme görüyorum."), "Söylenen cümle: I can see real progress in my writing.", "I can see real progress in my writing.", null),
                LearningExercise("b1v26e10", Skill.READING, "Cümleyi oku ve doğru anlamı seç", "Okuduğun cümle ne anlatıyor?", "Never give up on your dreams.", listOf("Planladığı her şeyi başardı.", "Yazmamda gerçek bir ilerleme görüyorum.", "Hayallerinden asla vazgeçme."), listOf("Hayallerinden asla vazgeçme."), "Cümlenin çevirisi: Hayallerinden asla vazgeçme.", null, null))),
            LearningLesson("B1-U26-L3", "Goals & Plans — Practice", "Apply the grammar focus, speak and write.", listOf(
                LearningExercise("b1v26e7", Skill.GRAMMAR, "Doğru seçeneği işaretle", "I am thinking ___ a new language course.", "", listOf("of starting", "to start", "start"), listOf("of starting"), "Think of + -ing kalıbı kullanılır.", null, null),
                LearningExercise("b1v26e8", Skill.SPEAKING, "İfadeyi sesli söyle", "Say: She achieved everything she planned.", "", listOf(), listOf("She achieved everything she planned."), "Türkçesi: Planladığı her şeyi başardı.", "She achieved everything she planned.", "She achieved everything she planned."),
                LearningExercise("b1v26e9", Skill.WRITING, "Cümleyi İngilizce yaz", "İngilizcesi: Bir yıl ara vermeye karar verdim.", "", listOf(), listOf("I decided to take a gap year."), "Örnek yanıt: I decided to take a gap year.", null, "I decided to take a gap year."))))))
}
