package com.linguapro.android

/** Hacim genişletme içerik paketi: C1 seviyesi (8 ünite, 24 ders). Otomatik derlenmiş, elle küratörlü banka. */
object CourseVolumeC1 {
    val units: List<LearningUnit> = listOf(
        LearningUnit("C1-U13", "Advanced Idioms", "Use common idioms naturally in conversation.", listOf(
            LearningLesson("C1-U13-L1", "Advanced Idioms — Words", "Recognize key vocabulary for this topic.", listOf(
                LearningExercise("c1v13e1", Skill.VOCABULARY, "Doğru anlamı seç", "'hit the ground running' ne anlama gelir?", "", listOf("görmezden gelinen sorun", "uzun vadede", "hızlı başlamak"), listOf("hızlı başlamak"), "She hit the ground running in her new role. — Yeni görevine hızlı bir başlangıç yaptı.", null, null),
                LearningExercise("c1v13e2", Skill.VOCABULARY, "Doğru anlamı seç", "'the elephant in the room' ne anlama gelir?", "", listOf("günü bitirmek", "görmezden gelinen sorun", "işi baştan savmak"), listOf("görmezden gelinen sorun"), "Budget cuts were the elephant in the room. — Bütçe kesintileri odadaki görünmez fildi.", null, null),
                LearningExercise("c1v13e3", Skill.VOCABULARY, "Doğru anlamı seç", "'cut corners' ne anlama gelir?", "", listOf("işi baştan savmak", "uzun vadede", "hızlı başlamak"), listOf("işi baştan savmak"), "Never cut corners on safety checks. — Güvenlik kontrollerinde asla işi baştan savma.", null, null))),
            LearningLesson("C1-U13-L2", "Advanced Idioms — In Use", "Use the new words in real sentences and listening.", listOf(
                LearningExercise("c1v13e4", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "She ___ in her new role.", "", listOf("cut corners", "hit the ground running", "the elephant in the room"), listOf("hit the ground running"), "Doğru cümle: She hit the ground running in her new role. — Yeni görevine hızlı bir başlangıç yaptı.", null, null),
                LearningExercise("c1v13e5", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "Quality pays off ___.", "", listOf("in the long run", "call it a day", "hit the ground running"), listOf("in the long run"), "Doğru cümle: Quality pays off in the long run. — Kalite uzun vadede karşılığını verir.", null, null),
                LearningExercise("c1v13e6", Skill.LISTENING, "Dinle ve anlamı seç", "Cümle ne anlatıyor?", "", listOf("Yeni görevine hızlı bir başlangıç yaptı.", "Güvenlik kontrollerinde asla işi baştan savma.", "Geç oldu; bugünlük bu kadar diyelim."), listOf("Geç oldu; bugünlük bu kadar diyelim."), "Söylenen cümle: It is late; let us call it a day.", "It is late; let us call it a day.", null),
                LearningExercise("c1v13e10", Skill.READING, "Cümleyi oku ve doğru anlamı seç", "Okuduğun cümle ne anlatıyor?", "Quality pays off in the long run.", listOf("Kalite uzun vadede karşılığını verir.", "Bütçe kesintileri odadaki görünmez fildi.", "Geç oldu; bugünlük bu kadar diyelim."), listOf("Kalite uzun vadede karşılığını verir."), "Cümlenin çevirisi: Kalite uzun vadede karşılığını verir.", null, null))),
            LearningLesson("C1-U13-L3", "Advanced Idioms — Practice", "Apply the grammar focus, speak and write.", listOf(
                LearningExercise("c1v13e7", Skill.GRAMMAR, "Doğru seçeneği işaretle", "Only after the audit ___ the full picture.", "", listOf("did we see", "we saw", "we did see"), listOf("did we see"), "Only after başta: devrik yapı gerekir.", null, null),
                LearningExercise("c1v13e8", Skill.SPEAKING, "İfadeyi sesli söyle", "Say: Budget cuts were the elephant in the room.", "", listOf(), listOf("Budget cuts were the elephant in the room."), "Türkçesi: Bütçe kesintileri odadaki görünmez fildi.", "Budget cuts were the elephant in the room.", "Budget cuts were the elephant in the room."),
                LearningExercise("c1v13e9", Skill.WRITING, "Cümleyi İngilizce yaz", "İngilizcesi: Güvenlik kontrollerinde asla işi baştan savma.", "", listOf(), listOf("Never cut corners on safety checks."), "Örnek yanıt: Never cut corners on safety checks.", null, "Never cut corners on safety checks."))))),
        LearningUnit("C1-U14", "Nuance & Synonyms", "Choose precise words among close synonyms.", listOf(
            LearningLesson("C1-U14-L1", "Nuance & Synonyms — Words", "Recognize key vocabulary for this topic.", listOf(
                LearningExercise("c1v14e1", Skill.VOCABULARY, "Doğru anlamı seç", "'imply' ne anlama gelir?", "", listOf("ünlü", "ima etmek", "çıkarım yapmak"), listOf("ima etmek"), "Her tone implied disagreement. — Ses tonu itirazı ima ediyordu.", null, null),
                LearningExercise("c1v14e2", Skill.VOCABULARY, "Doğru anlamı seç", "'infer' ne anlama gelir?", "", listOf("çıkarım yapmak", "adı çıkmış", "ince"), listOf("çıkarım yapmak"), "Readers inferred a hidden motive. — Okurlar gizli bir amaç olduğu çıkarımını yaptı.", null, null),
                LearningExercise("c1v14e3", Skill.VOCABULARY, "Doğru anlamı seç", "'notorious' ne anlama gelir?", "", listOf("ünlü", "ima etmek", "adı çıkmış"), listOf("adı çıkmış"), "The road is notorious for accidents. — Yol kazalarla adı çıkmış durumda.", null, null))),
            LearningLesson("C1-U14-L2", "Nuance & Synonyms — In Use", "Use the new words in real sentences and listening.", listOf(
                LearningExercise("c1v14e4", Skill.VOCABULARY, "Doğru anlamı seç", "'imply' ne anlama gelir?", "", listOf("ince", "ima etmek", "adı çıkmış"), listOf("ima etmek"), "Her tone implied disagreement. — Ses tonu itirazı ima ediyordu.", null, null),
                LearningExercise("c1v14e5", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "She is a ___ heart surgeon.", "", listOf("subtle", "imply", "renowned"), listOf("renowned"), "Doğru cümle: She is a renowned heart surgeon. — Tanınmış bir kalp cerrahıdır.", null, null),
                LearningExercise("c1v14e6", Skill.LISTENING, "Dinle ve anlamı seç", "Cümle ne anlatıyor?", "", listOf("Yol kazalarla adı çıkmış durumda.", "İkisi arasında ince bir fark var.", "Ses tonu itirazı ima ediyordu."), listOf("İkisi arasında ince bir fark var."), "Söylenen cümle: There is a subtle difference between the two.", "There is a subtle difference between the two.", null),
                LearningExercise("c1v14e10", Skill.READING, "Cümleyi oku ve doğru anlamı seç", "Okuduğun cümle ne anlatıyor?", "She is a renowned heart surgeon.", listOf("Okurlar gizli bir amaç olduğu çıkarımını yaptı.", "İkisi arasında ince bir fark var.", "Tanınmış bir kalp cerrahıdır."), listOf("Tanınmış bir kalp cerrahıdır."), "Cümlenin çevirisi: Tanınmış bir kalp cerrahıdır.", null, null))),
            LearningLesson("C1-U14-L3", "Nuance & Synonyms — Practice", "Apply the grammar focus, speak and write.", listOf(
                LearningExercise("c1v14e7", Skill.GRAMMAR, "Olumlu bulguya rağmen temkini belirten karşıtlık bağlacını seç", "The findings are compelling; ___, caution is warranted.", "", listOf("nevertheless", "therefore", "moreover"), listOf("nevertheless"), "Nevertheless, olumlu bulgu ile temkin gereği arasında taviz ilişkisi kurar. Therefore sonuç, moreover ekleme bildirir; görev bu ilişkileri değil karşıtlığı ister.", null, null),
                LearningExercise("c1v14e8", Skill.SPEAKING, "İfadeyi sesli söyle", "Say: Readers inferred a hidden motive.", "", listOf(), listOf("Readers inferred a hidden motive."), "Türkçesi: Okurlar gizli bir amaç olduğu çıkarımını yaptı.", "Readers inferred a hidden motive.", "Readers inferred a hidden motive."),
                LearningExercise("c1v14e9", Skill.WRITING, "Cümleyi İngilizce yaz", "İngilizcesi: Yol kazalarla adı çıkmış durumda.", "", listOf(), listOf("The road is notorious for accidents."), "Örnek yanıt: The road is notorious for accidents.", null, "The road is notorious for accidents."))))),
        LearningUnit("C1-U15", "Academic Debate", "Argue, concede and rebut in formal discussion.", listOf(
            LearningLesson("C1-U15-L1", "Academic Debate — Words", "Recognize key vocabulary for this topic.", listOf(
                LearningExercise("c1v15e1", Skill.VOCABULARY, "Doğru anlamı seç", "'premise' ne anlama gelir?", "", listOf("öncül", "çürütmek", "sav"), listOf("öncül"), "The argument rests on a weak premise. — Argüman zayıf bir öncüle dayanıyor.", null, null),
                LearningExercise("c1v15e2", Skill.VOCABULARY, "Doğru anlamı seç", "'rebut' ne anlama gelir?", "", listOf("kabullenmek", "karşı örnek", "çürütmek"), listOf("çürütmek"), "She rebutted each objection calmly. — Her itirazı sakince çürüttü.", null, null),
                LearningExercise("c1v15e3", Skill.VOCABULARY, "Doğru anlamı seç", "'concede' ne anlama gelir?", "", listOf("öncül", "kabullenmek", "sav"), listOf("kabullenmek"), "I concede that the sample was small. — Örneklemin küçük olduğunu kabul ediyorum.", null, null))),
            LearningLesson("C1-U15-L2", "Academic Debate — In Use", "Use the new words in real sentences and listening.", listOf(
                LearningExercise("c1v15e4", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "The argument rests on a weak ___.", "", listOf("rebut", "concede", "premise"), listOf("premise"), "Doğru cümle: The argument rests on a weak premise. — Argüman zayıf bir öncüle dayanıyor.", null, null),
                LearningExercise("c1v15e5", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "The ___ lacks empirical support.", "", listOf("premise", "assertion", "counterexample"), listOf("assertion"), "Doğru cümle: The assertion lacks empirical support. — Sav ampirik destekten yoksun.", null, null),
                LearningExercise("c1v15e6", Skill.LISTENING, "Dinle ve anlamı seç", "Cümle ne anlatıyor?", "", listOf("Tek bir karşı örnek teoriyi zayıflattı.", "Argüman zayıf bir öncüle dayanıyor.", "Örneklemin küçük olduğunu kabul ediyorum."), listOf("Tek bir karşı örnek teoriyi zayıflattı."), "Söylenen cümle: One counterexample weakened the theory.", "One counterexample weakened the theory.", null),
                LearningExercise("c1v15e10", Skill.READING, "Cümleyi oku ve doğru anlamı seç", "Okuduğun cümle ne anlatıyor?", "The assertion lacks empirical support.", listOf("Tek bir karşı örnek teoriyi zayıflattı.", "Sav ampirik destekten yoksun.", "Her itirazı sakince çürüttü."), listOf("Sav ampirik destekten yoksun."), "Cümlenin çevirisi: Sav ampirik destekten yoksun.", null, null))),
            LearningLesson("C1-U15-L3", "Academic Debate — Practice", "Apply the grammar focus, speak and write.", listOf(
                LearningExercise("c1v15e7", Skill.GRAMMAR, "Doğru seçeneği işaretle", "___ the premise true, the conclusion would follow.", "", listOf("Were", "Was", "Is"), listOf("Were"), "Resmî koşul devriği: Were X true...", null, null),
                LearningExercise("c1v15e8", Skill.SPEAKING, "İfadeyi sesli söyle", "Say: She rebutted each objection calmly.", "", listOf(), listOf("She rebutted each objection calmly."), "Türkçesi: Her itirazı sakince çürüttü.", "She rebutted each objection calmly.", "She rebutted each objection calmly."),
                LearningExercise("c1v15e9", Skill.WRITING, "Cümleyi İngilizce yaz", "İngilizcesi: Örneklemin küçük olduğunu kabul ediyorum.", "", listOf(), listOf("I concede that the sample was small."), "Örnek yanıt: I concede that the sample was small.", null, "I concede that the sample was small."))))),
        LearningUnit("C1-U16", "Critical Reading", "Evaluate arguments, bias and reliability.", listOf(
            LearningLesson("C1-U16-L1", "Critical Reading — Words", "Recognize key vocabulary for this topic.", listOf(
                LearningExercise("c1v16e1", Skill.VOCABULARY, "Doğru anlamı seç", "'credible' ne anlama gelir?", "", listOf("çarpıtmak", "altta yatan", "güvenilir"), listOf("güvenilir"), "Is the source credible and independent? — Kaynak güvenilir ve bağımsız mı?", null, null),
                LearningExercise("c1v16e2", Skill.VOCABULARY, "Doğru anlamı seç", "'distort' ne anlama gelir?", "", listOf("didik didik incelemek", "çarpıtmak", "abartmak"), listOf("çarpıtmak"), "Headlines sometimes distort the findings. — Manşetler bazen bulguları çarpıtır.", null, null),
                LearningExercise("c1v16e3", Skill.VOCABULARY, "Doğru anlamı seç", "'overstate' ne anlama gelir?", "", listOf("abartmak", "altta yatan", "güvenilir"), listOf("abartmak"), "The report overstates the benefits. — Rapor faydaları abartıyor.", null, null))),
            LearningLesson("C1-U16-L2", "Critical Reading — In Use", "Use the new words in real sentences and listening.", listOf(
                LearningExercise("c1v16e4", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "Is the source ___ and independent?", "", listOf("overstate", "credible", "distort"), listOf("credible"), "Doğru cümle: Is the source credible and independent? — Kaynak güvenilir ve bağımsız mı?", null, null),
                LearningExercise("c1v16e5", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "Look for the ___ assumption.", "", listOf("underlying", "scrutinize", "credible"), listOf("underlying"), "Doğru cümle: Look for the underlying assumption. — Altta yatan varsayımı ara.", null, null),
                LearningExercise("c1v16e6", Skill.LISTENING, "Dinle ve anlamı seç", "Cümle ne anlatıyor?", "", listOf("Kaynak güvenilir ve bağımsız mı?", "Rapor faydaları abartıyor.", "Uzmanlar yöntemi didik didik inceledi."), listOf("Uzmanlar yöntemi didik didik inceledi."), "Söylenen cümle: Experts scrutinized the methodology.", "Experts scrutinized the methodology.", null),
                LearningExercise("c1v16e10", Skill.READING, "Cümleyi oku ve doğru anlamı seç", "Okuduğun cümle ne anlatıyor?", "Look for the underlying assumption.", listOf("Altta yatan varsayımı ara.", "Manşetler bazen bulguları çarpıtır.", "Uzmanlar yöntemi didik didik inceledi."), listOf("Altta yatan varsayımı ara."), "Cümlenin çevirisi: Altta yatan varsayımı ara.", null, null))),
            LearningLesson("C1-U16-L3", "Critical Reading — Practice", "Apply the grammar focus, speak and write.", listOf(
                LearningExercise("c1v16e7", Skill.GRAMMAR, "Doğru seçeneği işaretle", "The claim, ___ repeated often, remains unproven.", "", listOf("though", "despite", "unless"), listOf("though"), "Kısaltılmış zarf cümleciği: though repeated.", null, null),
                LearningExercise("c1v16e8", Skill.SPEAKING, "İfadeyi sesli söyle", "Say: Headlines sometimes distort the findings.", "", listOf(), listOf("Headlines sometimes distort the findings."), "Türkçesi: Manşetler bazen bulguları çarpıtır.", "Headlines sometimes distort the findings.", "Headlines sometimes distort the findings."),
                LearningExercise("c1v16e9", Skill.WRITING, "Cümleyi İngilizce yaz", "İngilizcesi: Rapor faydaları abartıyor.", "", listOf(), listOf("The report overstates the benefits."), "Örnek yanıt: The report overstates the benefits.", null, "The report overstates the benefits."))))),
        LearningUnit("C1-U17", "Diplomatic Language", "Soften messages and manage sensitive topics.", listOf(
            LearningLesson("C1-U17-L1", "Diplomatic Language — Words", "Recognize key vocabulary for this topic.", listOf(
                LearningExercise("c1v17e1", Skill.VOCABULARY, "Doğru anlamı seç", "'tactful' ne anlama gelir?", "", listOf("teslim etmek", "nazik ve ölçülü", "çekince"), listOf("nazik ve ölçülü"), "A tactful reply avoided a conflict. — Ölçülü bir yanıt çatışmayı önledi.", null, null),
                LearningExercise("c1v17e2", Skill.VOCABULARY, "Doğru anlamı seç", "'reservation' ne anlama gelir?", "", listOf("çekince", "yapıcı", "karşılıklı olarak"), listOf("çekince"), "We support the plan with minor reservations. — Planı küçük çekincelerle destekliyoruz.", null, null),
                LearningExercise("c1v17e3", Skill.VOCABULARY, "Doğru anlamı seç", "'constructive' ne anlama gelir?", "", listOf("teslim etmek", "nazik ve ölçülü", "yapıcı"), listOf("yapıcı"), "Keep the feedback constructive. — Geri bildirimi yapıcı tut.", null, null))),
            LearningLesson("C1-U17-L2", "Diplomatic Language — In Use", "Use the new words in real sentences and listening.", listOf(
                LearningExercise("c1v17e4", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "A ___ reply avoided a conflict.", "", listOf("tactful", "reservation", "constructive"), listOf("tactful"), "Doğru cümle: A tactful reply avoided a conflict. — Ölçülü bir yanıt çatışmayı önledi.", null, null),
                LearningExercise("c1v17e5", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "We ___ the effort behind the proposal.", "", listOf("mutually", "tactful", "acknowledge"), listOf("acknowledge"), "Doğru cümle: We acknowledge the effort behind the proposal. — Teklifin ardındaki emeği teslim ediyoruz.", null, null),
                LearningExercise("c1v17e6", Skill.LISTENING, "Dinle ve anlamı seç", "Cümle ne anlatıyor?", "", listOf("Geri bildirimi yapıcı tut.", "Karşılıklı fayda sağlayan bir sonuç arıyoruz.", "Ölçülü bir yanıt çatışmayı önledi."), listOf("Karşılıklı fayda sağlayan bir sonuç arıyoruz."), "Söylenen cümle: We seek a mutually beneficial outcome.", "We seek a mutually beneficial outcome.", null),
                LearningExercise("c1v17e10", Skill.READING, "Cümleyi oku ve doğru anlamı seç", "Okuduğun cümle ne anlatıyor?", "We acknowledge the effort behind the proposal.", listOf("Planı küçük çekincelerle destekliyoruz.", "Karşılıklı fayda sağlayan bir sonuç arıyoruz.", "Teklifin ardındaki emeği teslim ediyoruz."), listOf("Teklifin ardındaki emeği teslim ediyoruz."), "Cümlenin çevirisi: Teklifin ardındaki emeği teslim ediyoruz.", null, null))),
            LearningLesson("C1-U17-L3", "Diplomatic Language — Practice", "Apply the grammar focus, speak and write.", listOf(
                LearningExercise("c1v17e7", Skill.GRAMMAR, "Kibar ricada could + edilgen yapıyı tamamla", "We would appreciate it if the deadline ___.", "", listOf("could be extended", "could extended", "could be extend"), listOf("could be extended"), "Could sonrasında be + past participle kullanılır: could be extended. Edilgende deadline eylemi yapmaz, uzatılan şeydir.", null, null),
                LearningExercise("c1v17e8", Skill.SPEAKING, "İfadeyi sesli söyle", "Say: We support the plan with minor reservations.", "", listOf(), listOf("We support the plan with minor reservations."), "Türkçesi: Planı küçük çekincelerle destekliyoruz.", "We support the plan with minor reservations.", "We support the plan with minor reservations."),
                LearningExercise("c1v17e9", Skill.WRITING, "Cümleyi İngilizce yaz", "İngilizcesi: Geri bildirimi yapıcı tut.", "", listOf(), listOf("Keep the feedback constructive."), "Örnek yanıt: Keep the feedback constructive.", null, "Keep the feedback constructive."))))),
        LearningUnit("C1-U18", "Abstract Concepts", "Discuss ideas like freedom, justice and progress.", listOf(
            LearningLesson("C1-U18-L1", "Abstract Concepts — Words", "Recognize key vocabulary for this topic.", listOf(
                LearningExercise("c1v18e1", Skill.VOCABULARY, "Doğru anlamı seç", "'notion' ne anlama gelir?", "", listOf("kavram", "paradoks", "keyfi"), listOf("kavram"), "The notion of fairness varies across cultures. — Adalet kavramı kültürden kültüre değişir.", null, null),
                LearningExercise("c1v18e2", Skill.VOCABULARY, "Doğru anlamı seç", "'paradox' ne anlama gelir?", "", listOf("doğasında olan", "tutarlı", "paradoks"), listOf("paradoks"), "Choice overload is a modern paradox. — Seçenek bolluğu modern bir paradoks.", null, null),
                LearningExercise("c1v18e3", Skill.VOCABULARY, "Doğru anlamı seç", "'inherent' ne anlama gelir?", "", listOf("kavram", "doğasında olan", "keyfi"), listOf("doğasında olan"), "Risk is inherent in any innovation. — Risk her yeniliğin doğasında vardır.", null, null))),
            LearningLesson("C1-U18-L2", "Abstract Concepts — In Use", "Use the new words in real sentences and listening.", listOf(
                LearningExercise("c1v18e4", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "The ___ of fairness varies across cultures.", "", listOf("paradox", "inherent", "notion"), listOf("notion"), "Doğru cümle: The notion of fairness varies across cultures. — Adalet kavramı kültürden kültüre değişir.", null, null),
                LearningExercise("c1v18e5", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "The rule seemed entirely ___.", "", listOf("notion", "arbitrary", "coherent"), listOf("arbitrary"), "Doğru cümle: The rule seemed entirely arbitrary. — Kural tamamen keyfi görünüyordu.", null, null),
                LearningExercise("c1v18e6", Skill.LISTENING, "Dinle ve anlamı seç", "Cümle ne anlatıyor?", "", listOf("Tutarlı bir reform vizyonu sundu.", "Adalet kavramı kültürden kültüre değişir.", "Risk her yeniliğin doğasında vardır."), listOf("Tutarlı bir reform vizyonu sundu."), "Söylenen cümle: She offered a coherent vision of reform.", "She offered a coherent vision of reform.", null),
                LearningExercise("c1v18e10", Skill.READING, "Cümleyi oku ve doğru anlamı seç", "Okuduğun cümle ne anlatıyor?", "The rule seemed entirely arbitrary.", listOf("Tutarlı bir reform vizyonu sundu.", "Kural tamamen keyfi görünüyordu.", "Seçenek bolluğu modern bir paradoks."), listOf("Kural tamamen keyfi görünüyordu."), "Cümlenin çevirisi: Kural tamamen keyfi görünüyordu.", null, null))),
            LearningLesson("C1-U18-L3", "Abstract Concepts — Practice", "Apply the grammar focus, speak and write.", listOf(
                LearningExercise("c1v18e7", Skill.GRAMMAR, "Bu cümlede tek bir önceliği gösteren fiili seç", "What matters most ___ consistency over time.", "", listOf("is", "are", "being"), listOf("is"), "Bu cümlede consistency tek bir soyut önceliği belirtir, bu nedenle is kullanılır. What ile başlayan bütün yan cümleciklerin her bağlamda tekil fiil alması gerektiği sonucu çıkarılmamalıdır.", null, null),
                LearningExercise("c1v18e8", Skill.SPEAKING, "İfadeyi sesli söyle", "Say: Choice overload is a modern paradox.", "", listOf(), listOf("Choice overload is a modern paradox."), "Türkçesi: Seçenek bolluğu modern bir paradoks.", "Choice overload is a modern paradox.", "Choice overload is a modern paradox."),
                LearningExercise("c1v18e9", Skill.WRITING, "Cümleyi İngilizce yaz", "İngilizcesi: Risk her yeniliğin doğasında vardır.", "", listOf(), listOf("Risk is inherent in any innovation."), "Örnek yanıt: Risk is inherent in any innovation.", null, "Risk is inherent in any innovation."))))),
        LearningUnit("C1-U19", "Figurative Language", "Interpret metaphor, irony and imagery.", listOf(
            LearningLesson("C1-U19-L1", "Figurative Language — Words", "Recognize key vocabulary for this topic.", listOf(
                LearningExercise("c1v19e1", Skill.VOCABULARY, "Doğru anlamı seç", "'metaphor' ne anlama gelir?", "", listOf("ironi", "çağrıştırmak", "metafor"), listOf("metafor"), "Time as money is a common metaphor. — Zamanı para olarak görmek yaygın bir metafordur.", null, null),
                LearningExercise("c1v19e2", Skill.VOCABULARY, "Doğru anlamı seç", "'irony' ne anlama gelir?", "", listOf("simgelemek", "ironi", "canlı"), listOf("ironi"), "The irony of the ending surprised readers. — Sonun ironisi okurları şaşırttı.", null, null),
                LearningExercise("c1v19e3", Skill.VOCABULARY, "Doğru anlamı seç", "'vivid' ne anlama gelir?", "", listOf("canlı", "çağrıştırmak", "metafor"), listOf("canlı"), "The author paints a vivid picture of the city. — Yazar şehrin canlı bir resmini çizer.", null, null))),
            LearningLesson("C1-U19-L2", "Figurative Language — In Use", "Use the new words in real sentences and listening.", listOf(
                LearningExercise("c1v19e4", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "Time as money is a common ___.", "", listOf("vivid", "metaphor", "irony"), listOf("metaphor"), "Doğru cümle: Time as money is a common metaphor. — Zamanı para olarak görmek yaygın bir metafordur.", null, null),
                LearningExercise("c1v19e5", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "The melody ___s childhood memories.", "", listOf("evoke", "symbolize", "metaphor"), listOf("evoke"), "Doğru cümle: The melody evokes childhood memories. — Melodi çocukluk anılarını çağrıştırıyor.", null, null),
                LearningExercise("c1v19e6", Skill.LISTENING, "Dinle ve anlamı seç", "Cümle ne anlatıyor?", "", listOf("Zamanı para olarak görmek yaygın bir metafordur.", "Yazar şehrin canlı bir resmini çizer.", "Nehir zamanın akışını simgeler."), listOf("Nehir zamanın akışını simgeler."), "Söylenen cümle: The river symbolizes the passage of time.", "The river symbolizes the passage of time.", null),
                LearningExercise("c1v19e10", Skill.READING, "Cümleyi oku ve doğru anlamı seç", "Okuduğun cümle ne anlatıyor?", "The melody evokes childhood memories.", listOf("Melodi çocukluk anılarını çağrıştırıyor.", "Sonun ironisi okurları şaşırttı.", "Nehir zamanın akışını simgeler."), listOf("Melodi çocukluk anılarını çağrıştırıyor."), "Cümlenin çevirisi: Melodi çocukluk anılarını çağrıştırıyor.", null, null))),
            LearningLesson("C1-U19-L3", "Figurative Language — Practice", "Apply the grammar focus, speak and write.", listOf(
                LearningExercise("c1v19e7", Skill.GRAMMAR, "Geçmişte hardly ... when devrik yapısını tamamla", "Hardly ___ the novel begun when the tone shifted.", "", listOf("has", "had", "have"), listOf("had"), "Geçmişte iki olayın yakın sırasını anlatırken Hardly had + özne + past participle ... when + past simple kullanılır. Has/have bu geçmiş zaman dizisini karşılamaz.", null, null),
                LearningExercise("c1v19e8", Skill.SPEAKING, "İfadeyi sesli söyle", "Say: The irony of the ending surprised readers.", "", listOf(), listOf("The irony of the ending surprised readers."), "Türkçesi: Sonun ironisi okurları şaşırttı.", "The irony of the ending surprised readers.", "The irony of the ending surprised readers."),
                LearningExercise("c1v19e9", Skill.WRITING, "Cümleyi İngilizce yaz", "İngilizcesi: Yazar şehrin canlı bir resmini çizer.", "", listOf(), listOf("The author paints a vivid picture of the city."), "Örnek yanıt: The author paints a vivid picture of the city.", null, "The author paints a vivid picture of the city."))))),
        LearningUnit("C1-U20", "Persuasion & Rhetoric", "Build persuasive, well-paced arguments.", listOf(
            LearningLesson("C1-U20-L1", "Persuasion & Rhetoric — Words", "Recognize key vocabulary for this topic.", listOf(
                LearningExercise("c1v20e1", Skill.VOCABULARY, "Doğru anlamı seç", "'compelling' ne anlama gelir?", "", listOf("vurgu", "ikna edici", "kısa hikaye"), listOf("ikna edici"), "She made a compelling case for change. — Değişim için ikna edici bir savunma yaptı.", null, null),
                LearningExercise("c1v20e2", Skill.VOCABULARY, "Doğru anlamı seç", "'anecdote' ne anlama gelir?", "", listOf("kısa hikaye", "hitap etmek", "yankı uyandırmak"), listOf("kısa hikaye"), "He opened with a personal anecdote. — Konuşmasına kişisel bir anekdotla başladı.", null, null),
                LearningExercise("c1v20e3", Skill.VOCABULARY, "Doğru anlamı seç", "'appeal' ne anlama gelir?", "", listOf("vurgu", "ikna edici", "hitap etmek"), listOf("hitap etmek"), "The ad appeals to our sense of belonging. — Reklam aidiyet duygumuza hitap ediyor.", null, null))),
            LearningLesson("C1-U20-L2", "Persuasion & Rhetoric — In Use", "Use the new words in real sentences and listening.", listOf(
                LearningExercise("c1v20e4", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "She made a ___ case for change.", "", listOf("compelling", "anecdote", "appeal"), listOf("compelling"), "Doğru cümle: She made a compelling case for change. — Değişim için ikna edici bir savunma yaptı.", null, null),
                LearningExercise("c1v20e5", Skill.VOCABULARY, "Boşluğu doğru ifadeyle tamamla", "Put the ___ on benefits, not features.", "", listOf("resonate", "compelling", "emphasis"), listOf("emphasis"), "Doğru cümle: Put the emphasis on benefits, not features. — Vurguyu özelliklere değil faydalara yap.", null, null),
                LearningExercise("c1v20e6", Skill.LISTENING, "Dinle ve anlamı seç", "Cümle ne anlatıyor?", "", listOf("Reklam aidiyet duygumuza hitap ediyor.", "Mesaj genç seçmenlerde yankı buldu.", "Değişim için ikna edici bir savunma yaptı."), listOf("Mesaj genç seçmenlerde yankı buldu."), "Söylenen cümle: The message resonated with young voters.", "The message resonated with young voters.", null),
                LearningExercise("c1v20e10", Skill.READING, "Cümleyi oku ve doğru anlamı seç", "Okuduğun cümle ne anlatıyor?", "Put the emphasis on benefits, not features.", listOf("Konuşmasına kişisel bir anekdotla başladı.", "Mesaj genç seçmenlerde yankı buldu.", "Vurguyu özelliklere değil faydalara yap."), listOf("Vurguyu özelliklere değil faydalara yap."), "Cümlenin çevirisi: Vurguyu özelliklere değil faydalara yap.", null, null))),
            LearningLesson("C1-U20-L3", "Persuasion & Rhetoric — Practice", "Apply the grammar focus, speak and write.", listOf(
                LearningExercise("c1v20e7", Skill.GRAMMAR, "Doğru seçeneği işaretle", "It was the closing story ___ won the audience over.", "", listOf("that", "what", "who"), listOf("that"), "Vurgu (cleft) cümlesi: It was X that...", null, null),
                LearningExercise("c1v20e8", Skill.SPEAKING, "İfadeyi sesli söyle", "Say: He opened with a personal anecdote.", "", listOf(), listOf("He opened with a personal anecdote."), "Türkçesi: Konuşmasına kişisel bir anekdotla başladı.", "He opened with a personal anecdote.", "He opened with a personal anecdote."),
                LearningExercise("c1v20e9", Skill.WRITING, "Cümleyi İngilizce yaz", "İngilizcesi: Reklam aidiyet duygumuza hitap ediyor.", "", listOf(), listOf("The ad appeals to our sense of belonging."), "Örnek yanıt: The ad appeals to our sense of belonging.", null, "The ad appeals to our sense of belonging."))))))
}
