package com.linguapro.android

object ScenarioBankA1 {
    private fun s(n: Int, text: String, a: ScenarioQuestion, b: ScenarioQuestion, transfer: String, c: ScenarioQuestion) =
        UnitScenario("A1-U$n", text, a, b, transfer, c)
    val items = listOf(
        s(1, "Hello! My name is Nina. I'm from Spain. This is my friend, Omar. He is from Türkiye. We are students. Our English class is on Monday.",
            sq("Nina nereli?", "Spain", "Türkiye", "Canada", "Nina I'm from Spain diyor. Türkiye, Omar'ın ülkesi."),
            sq("İngilizce dersi hangi gün?", "Monday", "Friday", "Sunday", "Our English class is on Monday cümlesi ders gününü verir."),
            "Hi, I'm Emre. My friend is Sara. Sara is from Italy; I'm from Türkiye.",
            sq("İtalya'dan olan kişi kim?", "Sara", "Emre", "Both", "Sara is from Italy ifadesi ülkeyi Sara'ya bağlar.")),
        s(2, "This is my family. My father is a teacher. My mother is a nurse. My brother is ten. I get up at seven and walk to school with him.",
            sq("Anne ne iş yapıyor?", "A nurse", "A teacher", "A student", "My mother is a nurse cümlesi annenin mesleğini verir."),
            sq("Konuşmacı okula kiminle gidiyor?", "The speaker's brother", "His father", "His mother", "With him ifadesindeki him, bir önceki cümledeki brother'a gönderme yapar."),
            "Mia is my sister. She gets up at six. I get up at eight.",
            sq("Kim daha erken kalkıyor?", "Mia", "The speaker", "Both at the same time", "Altı, sekizden erkendir; Mia önce kalkar.")),
        s(3, "Good morning. Can I have a tea and a cheese sandwich, please? Of course. Anything else? No, thank you. The tea is two pounds and the sandwich is four pounds.",
            sq("Müşteri ne içmek istiyor?", "Tea", "Coffee", "Water", "Can I have a tea ... ifadesi içecek siparişidir."),
            sq("Sandviçin fiyatı ne kadar?", "Four pounds", "Two pounds", "Six pounds", "Sandviç dört pound; iki pound çayın fiyatı, altı pound toplamdır."),
            "A coffee is three pounds. A cake is two pounds. I'd like only a cake, please.",
            sq("Müşteri ne kadar öder?", "Two pounds", "Three pounds", "Five pounds", "Only a cake yalnızca kek istendiğini belirtir.")),
        s(4, "My flat is small. There is a kitchen and a bedroom. The bathroom is next to the bedroom. My desk is in the bedroom, and my books are on the desk.",
            sq("Çalışma masası nerede?", "In the bedroom", "In the bathroom", "In the kitchen", "My desk is in the bedroom ifadesi konumu açıklar."),
            sq("Banyo hangi odanın yanında?", "The bedroom", "The kitchen", "The living room", "Next to the bedroom, yatak odasının yanında demektir."),
            "The chair is beside the desk. A bag is under the chair.",
            sq("Çanta nerede?", "Under the chair", "On the desk", "Beside the bag", "Under altında anlamındadır; çantanın yerini belirtir.")),
        s(5, "On Saturdays, I play football with my friends. My sister reads books at home. On Sundays, we visit our grandmother. We don't go to school at the weekend.",
            sq("Cumartesi konuşmacı ne yapıyor?", "Plays football", "Reads at home", "Goes to school", "On Saturdays, I play football diyor; kitap okuyan kız kardeşi."),
            sq("Pazar günü kimi ziyaret ediyorlar?", "Their grandmother", "Their teacher", "Their friends", "On Sundays, we visit our grandmother cümlesi ziyaret edilen kişiyi verir."),
            "Leo swims on Friday. On Saturday, he stays at home and reads.",
            sq("Leo ne zaman yüzüyor?", "Friday", "Saturday", "Sunday", "Swims on Friday ile yüzme günü belirtilir.")),
        s(6, "Excuse me, where is the library? It's next to the bank. Walk straight and turn left at the café. Is it far? No, it's five minutes from here.",
            sq("Kütüphane hangi yerin yanında?", "The bank", "The café", "The school", "Next to the bank kütüphanenin konumudur; café dönüş noktasıdır."),
            sq("Kafede hangi yöne dönülmeli?", "Left", "Right", "Back", "Turn left sola dön demektir."),
            "The museum is opposite the park. The bank is behind the park.",
            sq("Parkın karşısındaki yer hangisi?", "The museum", "The bank", "Both", "Opposite karşısında, behind arkasında demektir.")),
        s(7, "It's cold and rainy today. Ella is wearing a blue coat and boots. Her brother has an umbrella. They walk to the bus stop together. Their gloves are in Ella's bag.",
            sq("Bugün hava nasıl?", "Cold and rainy", "Hot and sunny", "Warm and dry", "İlk cümlede cold and rainy deniyor."),
            sq("Eldivenler nerede?", "In Ella's bag", "At the bus stop", "In her brother's coat", "Their gloves are in Ella's bag cümlesi konumu verir."),
            "It's sunny and hot. I wear a light shirt and take a bottle of water.",
            sq("Bu hava için hangi giysi metinde seçiliyor?", "A light shirt", "A winter coat", "Thick gloves", "Light shirt sıcak güne uygun olarak seçilmiş; diğer giysiler söylenmiyor.")),
        s(8, "The shop opens at nine and closes at six. I work there from ten to four. I have lunch at one. After work, I take the bus home.",
            sq("Konuşmacı işe ne zaman başlıyor?", "At ten", "At nine", "At one", "From ten to four kişinin çalışma saatidir; nine dükkânın açılış saati."),
            sq("İşten sonra nasıl eve gidiyor?", "By bus", "By train", "On foot", "I take the bus home otobüsle dönüşü anlatır."),
            "My lesson starts at two. I arrive at one thirty.",
            sq("Konuşmacı derse göre ne zaman geliyor?", "Before it starts", "After it starts", "At the end", "One thirty, two'dan yarım saat önce gelir.")),
        s(9, "I can swim, but I can't ride a bike. My friend Jo can ride a bike and play the guitar. On Fridays, we listen to music together at Jo's house.",
            sq("Konuşmacı ne yapabiliyor?", "Swim", "Ride a bike", "Play the guitar", "I can swim olumlu yeteneği, can't ride a bike yapılamayan şeyi belirtir."),
            sq("Cuma günü müziği nerede dinliyorlar?", "At Jo's house", "At school", "At the pool", "At Jo's house etkinliğin yeridir."),
            "Ava can cook. She can't sing, but she likes music.",
            sq("Ava'nın yapabildiği şey hangisi?", "Cook", "Sing", "Play the guitar", "Can cook yetenektir; likes music bir beğenidir, çalgı çalabildiğini söylemez.")),
        s(10, "I don't feel well. My head hurts, and I'm tired. I want some water. My friend brings a glass of water and sits beside me. We stay at home today.",
            sq("Konuşmacı nasıl hissediyor?", "Tired and unwell", "Happy and hungry", "Cold and excited", "Don't feel well ve I'm tired, iyi hissetmediğini ve yorgunluğunu bildirir."),
            sq("Arkadaşı ne getiriyor?", "Water", "Coffee", "A sandwich", "A glass of water bir bardak sudur."),
            "Ben is thirsty. He asks for water, not food.",
            sq("Ben neye ihtiyaç duyduğunu söylüyor?", "A drink", "A meal", "A coat", "Thirsty susamış demektir; su istiyor, yiyecek değil.")),
        s(11, "Our classroom has a board, twelve desks and a clock. Please open your book on page ten, says the teacher. Sara doesn't understand. She asks, Can you repeat that, please?",
            sq("Öğretmen hangi sayfayı açmalarını istiyor?", "Ten", "Twelve", "Two", "Page ten sayfa numarası; twelve masa sayısıdır."),
            sq("Sara neden tekrar edilmesini istiyor?", "She doesn't understand.", "She has no book.", "The class is over.", "She doesn't understand ifadesi talebin nedenini açıklar."),
            "Please close the window and sit down. Keep your book open.",
            sq("Hangisi açık kalmalı?", "The book", "The window", "The door", "Keep your book open kitabı açık tut demektir.")),
        s(12, "It's my birthday on Sunday. My party starts at three at my house. Can you come? Yes, I can. Great! Please bring your sister, too. We have cake and music.",
            sq("Parti ne zaman başlıyor?", "At three on Sunday", "At two on Saturday", "At six on Monday", "Sunday günü ve starts at three saati birlikte verir."),
            sq("Davetli yanında kimi getirebilir?", "Their sister", "Their teacher", "Their neighbour", "Please bring your sister, too açık davettir."),
            "The picnic is on Saturday at noon. Sorry, I can't come; I work on Saturdays.",
            sq("Davet neden reddediliyor?", "The person works that day.", "The picnic is on Sunday.", "The person dislikes picnics.", "Work on Saturdays açıklanan nedendir; beğeni hakkında bilgi yok.")),
        s(13, "Where is my phone? It's on the table, beside the lamp. Your keys are in the drawer. The bag is under the table. Thank you! I have my phone and keys now.",
            sq("Telefon nerede?", "On the table", "In the drawer", "Under the table", "On the table telefonun, in the drawer anahtarların konumudur."),
            sq("Masanın altındaki eşya ne?", "The bag", "The lamp", "The keys", "The bag is under the table ifadesi çantayı belirtir."),
            "A cup is on the shelf. A plate is in the cupboard.",
            sq("Dolabın içinde ne var?", "A plate", "A cup", "A lamp", "In the cupboard ile plate eşleşir.")),
        s(14, "For breakfast, I have bread and cheese. My sister has an egg. We drink milk. At lunch, I have rice and vegetables, but my sister has soup. We both like apples.",
            sq("Kız kardeş öğle yemeğinde ne yiyor?", "Soup", "An egg", "Rice", "At lunch ... my sister has soup diyor; egg kahvaltıdadır."),
            sq("İkisi de hangi meyveyi seviyor?", "Apples", "Oranges", "Bananas", "We both like apples ortak beğeniyi bildirir."),
            "I like tea, but I don't like coffee. My friend likes both.",
            sq("Kahveyi seven kim?", "The friend", "The speaker", "Neither", "My friend likes both çay ve kahveyi birlikte kapsar.")),
        s(15, "Welcome to our house. The kitchen is downstairs. The bedrooms are upstairs. There's a table in the kitchen and a sofa in the living room. Our cat sleeps on the sofa.",
            sq("Yatak odaları nerede?", "Upstairs", "Downstairs", "In the garden", "Bedrooms are upstairs, odaların üst katta olduğunu söyler."),
            sq("Kedi nerede uyuyor?", "On the sofa", "Under the table", "In the kitchen", "Our cat sleeps on the sofa cümlesi uyuduğu yeri verir."),
            "The bathroom is upstairs. The living room is downstairs.",
            sq("Alt kattaki oda hangisi?", "The living room", "The bathroom", "Both", "Downstairs alt kat; upstairs üst kat anlamındadır.")),
        s(16, "I live near a park. There is a bakery opposite my house. I buy bread there in the morning. The hospital is far away, but the pharmacy is next to the bakery.",
            sq("Konuşmacı sabah ekmeği nereden alıyor?", "The bakery", "The pharmacy", "The hospital", "There zamiri bakery'ye döner; buy bread orada gerçekleşir."),
            sq("Eczane hangi yerin yanında?", "The bakery", "The hospital", "The park", "Next to the bakery eczanenin konumunu verir."),
            "The bank is near my home. The station is far away.",
            sq("Eve yakın olan hangisi?", "The bank", "The station", "Both", "Near yakın, far away uzak anlamına gelir.")),
        s(17, "Today is Wednesday. Our music lesson is tomorrow at half past four. There is no lesson on Friday. On Saturday, we meet at the park at ten in the morning.",
            sq("Müzik dersi hangi gün?", "Thursday", "Wednesday", "Friday", "Bugün çarşamba ise tomorrow perşembedir."),
            sq("Parkta buluşma saati ne?", "Ten in the morning", "Half past four", "Ten at night", "Park buluşması at ten in the morning olarak belirtilir."),
            "Today is Monday. The shop is closed today and opens tomorrow.",
            sq("Dükkân hangi gün açılıyor?", "Tuesday", "Monday", "Sunday", "Monday'den sonraki gün Tuesday'dir.")),
        s(18, "Which jacket is yours? The green one. My brother's jacket is black. These blue shoes are mine, too. I wear my green jacket and blue shoes when I go to school.",
            sq("Konuşmacının ceketi hangi renk?", "Green", "Black", "Blue", "The green one kendi ceketi, black erkek kardeşinin ceketidir."),
            sq("Mavi ayakkabılar kimin?", "The speaker's", "The brother's", "The teacher's", "These blue shoes are mine konuşmacıya ait olduğunu belirtir."),
            "Ana has a red hat. Leo has a blue hat. The red hat is on the chair.",
            sq("Sandalyedeki şapka kimin?", "Ana's", "Leo's", "Both people's", "Sandalyedeki kırmızı şapka; Ana'nın şapkası kırmızı.")),
        s(19, "I wash my hands before lunch. My little brother brushes his teeth after breakfast. We have a dog with brown eyes. Every afternoon, we walk with our dog in the park.",
            sq("Konuşmacı ellerini ne zaman yıkıyor?", "Before lunch", "After lunch", "Before bed", "Before lunch öğle yemeğinden önce demektir."),
            sq("Köpeğin gözleri hangi renk?", "Brown", "Green", "Blue", "A dog with brown eyes cümlesinde göz rengi brown."),
            "I brush my teeth before bed. My sister washes her hands before dinner.",
            sq("Konuşmacı yatmadan önce ne yapıyor?", "Brushes their teeth", "Washes their hands", "Eats dinner", "I brush my teeth before bed açık bilgidir; el yıkayan kız kardeşidir.")),
        s(20, "It's winter here. The mornings are cold, and it often rains. Today is different: the sun is out. We take our coats and go for a short walk near the river.",
            sq("Hangi mevsim anlatılıyor?", "Winter", "Summer", "Spring", "It's winter here doğrudan mevsimi verir."),
            sq("Bugün alışılmış havadan farklı olan ne?", "It is sunny.", "It is very hot.", "It is raining.", "The sun is out bugün güneşin çıktığını söyler; sıcak olduğu belirtilmez."),
            "It is raining this morning. The forecast says it will be sunny this afternoon.",
            sq("Yağmur şu an ne zaman yağıyor?", "This morning", "This afternoon", "Tomorrow", "This morning mevcut yağış, öğleden sonra ise tahmindir."))
    )
}
