package com.linguapro.android

object ScenarioBankA2 {
    private fun s(n: Int, text: String, a: ScenarioQuestion, b: ScenarioQuestion, transfer: String, c: ScenarioQuestion) =
        UnitScenario("A2-U$n", text, a, b, transfer, c)
    val items = listOf(
        s(1, "I booked a train ticket for Saturday morning, but I missed the train because my bus was late. The next train left an hour later. I bought a sandwich while I waited, then called my friend to say I would arrive late.",
            sq("Yolcu neden ilk treni kaçırdı?", "The bus was late.", "He lost his ticket.", "He bought the wrong ticket.", "Because my bus was late kaçırma nedenidir; biletle ilgili sorun söylenmiyor."),
            sq("Beklerken hangi iki şeyi yaptı?", "Bought food and called a friend", "Booked a hotel and went home", "Changed buses and bought a new phone", "Sandviç aldı ve arkadaşına geç kalacağını bildirdi."),
            "A train leaves at ten, but Mina arrives at the station at ten fifteen. The next train is at eleven.",
            sq("Mina neden beklemek zorunda?", "She arrived after the train left.", "She arrived too early.", "The station is closed.", "Ten fifteen, ten'dan sonradır; ilk treni kaçırmıştır.")),
        s(2, "At the café, I asked for soup without cream because I don't eat dairy products. The waiter checked with the cook and suggested vegetable soup. I also ordered bread and water. Before leaving, I thanked the waiter for checking the ingredients.",
            sq("Müşteri neden kremasız çorba istiyor?", "She doesn't eat dairy products.", "She dislikes vegetables.", "She wants a cold meal.", "Because I don't eat dairy products nedeni verir; bütün sebzeleri sevmediği söylenmiyor."),
            sq("Garson hangi konuda kontrol yaptı?", "The ingredients", "The customer's address", "The price of water", "Cook ile kontrol ederek içeriğe uygun çorba önerdi."),
            "Please check whether this bread contains milk. I don't eat dairy products.",
            sq("Hangi bilgi isteniyor?", "Whether the bread contains milk", "When the café closes", "Whether the bread is expensive", "Contains milk, süt içerip içermediğini sorar.")),
        s(3, "We're going to visit the coast next month. I've been there before, but my brother hasn't. We plan to stay for three nights and travel by bus. If the weather is bad, we can visit the town museum instead of spending the day on the beach.",
            sq("Daha önce sahile gitmiş olan kim?", "The speaker", "The brother", "Neither of them", "I've been there before, konuşmacının deneyimini; my brother hasn't, kardeşinin gitmediğini söyler."),
            sq("Kötü hava durumunda ne yapabilirler?", "Visit the museum", "Cancel every journey", "Stay for a month", "Museum, plaj yerine sunulan alternatif etkinliktir."),
            "I've never visited Rome. I'm going there next week for the first time.",
            sq("Gezi hangi tür deneyim olacak?", "A first visit", "A return visit", "A cancelled visit", "Never ve for the first time ilk ziyaret olduğunu doğrular.")),
        s(4, "I usually start work at nine. Yesterday, the printer stopped working just before a meeting. I asked a colleague for help, and she showed me how to restart it. We printed the papers in time, but I decided to prepare them earlier next week.",
            sq("Toplantıdan önce hangi sorun çıktı?", "The printer stopped working.", "The colleague missed the bus.", "The meeting room was closed.", "Printer stopped working açık sorun ifadesidir."),
            sq("Konuşmacı gelecek hafta neyi değiştirecek?", "Prepare the papers earlier", "Start every meeting at nine", "Stop using paper completely", "Prepare them earlier next week hazırlığı öne alma kararıdır."),
            "The computer isn't working. Could you help me restart it before the call?",
            sq("İstenen yardım hangisi?", "Restarting the computer", "Cancelling the call", "Buying a printer", "Restart it, önceki cümledeki computer'a gönderme yapar.")),
        s(5, "I couldn't go to my friend's dinner because I had a cold. I sent a message in the afternoon and apologised. She said we could meet another day. I'm feeling better now, so I've invited her to lunch next Saturday.",
            sq("İlk davete neden katılamadı?", "He had a cold.", "He forgot the address.", "He didn't like the food.", "Because I had a cold katılamama nedenidir."),
            sq("Yeni buluşma ne zaman önerildi?", "Next Saturday", "Yesterday afternoon", "This evening", "Lunch next Saturday yeni davetin zamanıdır."),
            "I'm sorry I can't come tonight. Could we meet on Sunday instead?",
            sq("Mesaj hangi işlevi yerine getiriyor?", "Declining and suggesting another time", "Accepting tonight's invitation", "Asking for a restaurant bill", "Can't come reddeder; Sunday instead alternatif zaman önerir.")),
        s(6, "We reserved a room with two beds for three nights. When we arrived, the hotel gave us a room with only one bed. I showed the receptionist our booking email. She apologised and found the correct room without charging us extra.",
            sq("Oda ile rezervasyon arasındaki fark neydi?", "The number of beds", "The number of nights", "The name of the hotel", "Two beds istenmiş, only one bed verilmişti."),
            sq("Sorunu çözerken ne gösterildi?", "The booking email", "A train timetable", "A restaurant menu", "Booking email rezervasyon ayrıntılarını kanıtlamak için gösterildi."),
            "Our reservation includes breakfast. Could you check why breakfast appears as an extra charge?",
            sq("Müşteri hangi ücreti sorguluyor?", "Breakfast", "The room key", "The train ticket", "Includes breakfast ile extra charge arasında tutarsızlık var.")),
        s(7, "I needed a raincoat, so I compared two in the shop. The cheaper one was light but had no pockets. The other cost ten pounds more and had a hood. I chose the second coat because I often walk to work in the rain.",
            sq("Müşteri hangi ürünü aldı?", "The more expensive coat", "The coat without pockets", "Neither coat", "Second coat, on pound daha pahalı olan üründür."),
            sq("Seçimde hangi ihtiyaç etkili oldu?", "Walking to work in the rain", "Buying a gift for a child", "Finding a winter hat", "Yağmurda işe yürümesi kapüşonlu seçeneği tercih etmesine gerekçe oluşturur."),
            "This bag is cheaper, but the other is stronger. I need one for carrying heavy books.",
            sq("Belirtilen ihtiyaca hangi özellik daha doğrudan uyar?", "Being stronger", "Having a lower price only", "Being a different colour", "Ağır kitap taşımak dayanıklılık ihtiyacı doğurur; renk söylenmiyor.")),
        s(8, "Last summer, we stayed in a village near the sea. On the first day, we got lost because we followed an old map. A shopkeeper helped us find our guesthouse. After that, we asked local people for directions and enjoyed the rest of the holiday.",
            sq("İlk gün neden kayboldular?", "They used an old map.", "The guesthouse was closed.", "They travelled by boat.", "Because we followed an old map açık neden bilgisidir."),
            sq("Sonrasında hangi yöntemi değiştirdiler?", "They asked local people for directions.", "They stopped leaving the guesthouse.", "They bought a boat.", "After that ile yön sormaya geçiş anlatılır."),
            "The road on our map was closed, so we asked a local driver for another route.",
            sq("Başka rota neden gerekiyor?", "The mapped road is closed.", "The driver is lost.", "The journey is finished.", "So, yolun kapalı olmasıyla rota aramayı bağlar.")),
        s(9, "I want to improve my English listening. Last month, I tried long videos, but I couldn't follow them. Now I listen to short recordings twice and write down useful phrases. My teacher suggested doing this for ten minutes every day rather than only once a week.",
            sq("Öğrenci neden yöntem değiştirdi?", "Long videos were difficult to follow.", "His teacher cancelled the course.", "Short recordings were unavailable.", "Couldn't follow them uzun videoları takip etme güçlüğüdür."),
            sq("Öğretmen nasıl bir çalışma sıklığı önerdi?", "A short session every day", "A long session once a year", "No listening practice", "Ten minutes every day kısa ve günlük çalışma önerisidir."),
            "This recording is difficult. I'll listen again at a slower speed and check the new words.",
            sq("Öğrenci zorluğa nasıl karşılık veriyor?", "By listening again and checking words", "By stopping the course", "By learning only the title", "Tekrar dinleme ve kelime kontrolü açıkça belirtilir.")),
        s(10, "Our school organised a clean-up beside the river. We brought gloves and reusable water bottles. We collected litter for an hour, then separated the cans from the other rubbish. Next time, we want to put up a sign asking visitors to take their rubbish home.",
            sq("Etkinliğin amacı neydi?", "Cleaning the area beside the river", "Building a new bridge", "Selling water bottles", "Clean-up temizlik etkinliğidir; yer beside the river."),
            sq("Bir sonraki etkinlikte ne yapmak istiyorlar?", "Put up a sign", "Stop separating rubbish", "Close the school", "Next time ... put up a sign gelecekteki plandır."),
            "Please bring a reusable cup. We won't provide disposable cups at the event.",
            sq("Katılımcıların ne getirmesi gerekiyor?", "A reusable cup", "A disposable plate", "A plastic bag", "Reusable cup tekrar kullanılabilir bardaktır.")),
        s(11, "The community centre has a new noticeboard. The swimming class has moved from Tuesday to Thursday, but the art class is still on Wednesday. Children must come with an adult. People can register at the desk or send an email before Friday.",
            sq("Hangi dersin günü değişti?", "Swimming", "Art", "Both classes", "Moved from Tuesday to Thursday değişikliktir; art still on Wednesday aynı kalır."),
            sq("Çocuklar nasıl katılabilir?", "With an adult", "Only alone", "Only by email", "Must come with an adult yetişkin eşliği koşuludur."),
            "The library closes early on Friday, but Saturday hours are unchanged.",
            sq("Hangi günün saatleri aynı kaldı?", "Saturday", "Friday", "Both", "Unchanged değişmedi demektir; Friday için erken kapanış var.")),
        s(12, "I emailed a customer yesterday about her order. She replied that the delivery address was wrong. I checked the order number and asked her to confirm the correct address. Before changing it, I sent a short message explaining what would happen next.",
            sq("Siparişte hangi sorun bildirildi?", "The delivery address was wrong.", "The customer ordered twice.", "The payment was late.", "Address was wrong, gönderim adresindeki hatadır."),
            sq("Adres değiştirilmeden önce ne istendi?", "Confirmation of the correct address", "A new order for the same product", "A train ticket", "Confirm the correct address doğrulama talebidir."),
            "Could you confirm the date before I book the room? I don't want to reserve the wrong day.",
            sq("Rezervasyondan önce ne doğrulanmalı?", "The date", "The room colour", "The customer's age", "Confirm the date yanlış güne rezervasyonu önlemeyi amaçlar.")),
        s(13, "I bought a jumper last week, but it was too small. I kept the receipt and returned to the shop on Saturday. They didn't have a larger size in the same colour. I chose a blue one instead, and it fitted well.",
            sq("Ürün neden geri götürüldü?", "It was too small.", "It was broken.", "It cost too much.", "Too small bedenin küçük olduğunu belirtir."),
            sq("Müşteri sonunda ne yaptı?", "Exchanged it for a blue one", "Kept the small jumper", "Bought two identical jumpers", "Blue one instead farklı renkte uygun ürünle değişimi anlatır."),
            "These shoes are too large. Do you have the same model in a smaller size?",
            sq("Müşteri hangi değişikliği istiyor?", "A smaller size", "A different price only", "A larger size", "Too large nedeniyle smaller size istenir.")),
        s(14, "At the restaurant, we ordered two meals and a salad to share. My friend asked whether the sauce was spicy. The waiter offered to serve it separately. When the food arrived, one meal was missing, so we politely asked the waiter to check our order.",
            sq("Sos için hangi çözüm önerildi?", "Serving it separately", "Removing both meals", "Adding extra salt", "Serve it separately sosu ayrı sunmak demektir."),
            sq("Sipariş neden kontrol edilmek zorunda kaldı?", "One meal was missing.", "The salad was too expensive.", "The restaurant was closed.", "One meal was missing eksik yemeği belirtir."),
            "We ordered still water, but this bottle is sparkling. Could you change it, please?",
            sq("Hangi fark bildiriliyor?", "The type of water", "The number of guests", "The meal size", "Still gazsız, sparkling gazlı sudur; istenen tür farklıdır.")),
        s(15, "To get to the sports centre, take the number six bus from the station. Get off after the bridge, not before it. Walk past the supermarket and turn right. The entrance is beside the café. Allow extra time because there are roadworks near the bridge.",
            sq("Yolcu köprüye göre nerede inmeli?", "After the bridge", "Before the bridge", "On the bridge", "After ... not before kritik ayrımı açıklar."),
            sq("Neden ek süre ayırmalı?", "There are roadworks.", "The centre opens only at night.", "The bus is free.", "Because there are roadworks yol çalışmalarını neden olarak verir."),
            "Turn left after the bank. If you reach the school, you've gone too far.",
            sq("Okula ulaşmak ne anlama gelir?", "The turning point was missed.", "The destination is the school.", "The bank is closed.", "Gone too far dönüş noktasının geçildiğini belirtir.")),
        s(16, "I used to spend every evening watching television. Now I attend a pottery class twice a week. At first, I found it difficult, but the other students helped me. I still watch films at the weekend, so I haven't stopped watching television completely.",
            sq("Yeni uğraş hangi sıklıkta yapılıyor?", "Twice a week", "Every evening", "Once a month", "Twice a week haftada iki kezdir; eski televizyon alışkanlığıyla karıştırma."),
            sq("Televizyon alışkanlığı tamamen bitti mi?", "No, films are still watched at weekends.", "Yes, television is never watched.", "The text does not mention television.", "Still watch films ... haven't stopped completely değişimin sınırlı olduğunu açıklar."),
            "I play chess once a week and swim twice a month.",
            sq("Hangi etkinlik daha sık yapılıyor?", "Chess", "Swimming", "They are equally frequent.", "Haftada bir satranç, ayda iki yüzmeden daha sıktır.")),
        s(17, "Our football practice usually happens outside. Yesterday, heavy rain meant we trained in the gym instead. The coach changed the exercises because there wasn't enough space for a full match. We practised passing and worked in small groups for an hour.",
            sq("Antrenman neden içeride yapıldı?", "Because of heavy rain", "Because the coach was absent", "Because the match ended early", "Heavy rain yer değişikliğinin nedenidir."),
            sq("Tam maç neden oynanmadı?", "There wasn't enough space.", "No one brought a ball.", "The group had no coach.", "Enough space for a full match yoktu; alan sınırlaması açıkça söyleniyor."),
            "The pool is closed today. We can walk in the park instead.",
            sq("Hangi seçenek alternatif olarak öneriliyor?", "Walking in the park", "Swimming in the closed pool", "Cancelling all exercise forever", "Instead bu gün için yürüyüş alternatifi sunar.")),
        s(18, "We're planning a camping trip in June. We will borrow a tent from my uncle and take the train to a nearby town. From there, a bus goes to the campsite. We've checked the timetable because the last bus leaves quite early in the afternoon.",
            sq("Çadırı nasıl temin edecekler?", "Borrow it from an uncle", "Buy it at the campsite", "Rent it on the train", "Borrow ... from my uncle ödünç almayı belirtir."),
            sq("Otobüs tarifesi neden kontrol edildi?", "The last bus leaves early.", "The bus has no seats.", "The train is cancelled.", "Son otobüsün erken kalkması bağlantıyı kaçırma riskini doğurur."),
            "The train arrives at two, and our bus leaves at one forty-five.",
            sq("Bu aktarma neden uygun değil?", "The bus leaves before the train arrives.", "The bus leaves after the train arrives.", "Both leave at two.", "One forty-five, two'dan öncedir; bağlantı kaçırılır.")),
        s(19, "When I moved to this town, I didn't know anyone. My neighbour invited me to a local cooking class. I was nervous at first, but everyone was friendly. We made soup together, and I met two people who lived on my street.",
            sq("Konuşmacı insanlarla nerede tanıştı?", "At a cooking class", "At a train station", "At a job interview", "Cooking class, tanışmanın gerçekleştiği etkinliktir."),
            sq("İlk duygusu nasıldı?", "Nervous", "Angry", "Bored", "Nervous at first başlangıçtaki gerginliği belirtir; ortam sonra dostça bulunur."),
            "I was afraid to speak at first, but the group encouraged me and I joined the discussion.",
            sq("Grubun desteği hangi değişime yol açtı?", "The person began participating.", "The person left immediately.", "The discussion was cancelled.", "Joined the discussion katılımın başladığını gösterir.")),
        s(20, "In our flat, we share the housework. I wash the dishes after dinner, and my flatmate takes out the rubbish. On Sundays, we clean the kitchen together. If one of us is away, the other does both jobs, and we swap the following week.",
            sq("Biri evde değilse ne oluyor?", "The other does both jobs.", "Neither job is done.", "A cleaner always comes.", "The other does both jobs istisna durumundaki iş paylaşımıdır."),
            sq("Ortak yapılan iş hangisi?", "Cleaning the kitchen on Sundays", "Taking out rubbish every night", "Washing dishes every morning", "Together sözcüğü pazar mutfak temizliğine bağlanır."),
            "I'll wash the dishes today if you do them tomorrow.",
            sq("Hangi düzenleme öneriliyor?", "Taking turns", "Doing nothing", "Both doing tomorrow's dishes together", "Bugün ve yarın sırayla iş yapma önerilir.")),
        s(21, "My phone stopped connecting to the internet at home. Other devices worked normally, so I checked the phone settings. The Wi-Fi was switched off. After turning it on, I could send messages again. I didn't need to buy a new phone or change the router.",
            sq("Sorunun kaynağı ne çıktı?", "Wi-Fi was off on the phone.", "The router was broken.", "All devices were offline.", "Other devices worked normally ve Wi-Fi switched off telefon ayarını işaret eder."),
            sq("Hangi işlem gerekmedi?", "Buying a new phone", "Checking settings", "Turning Wi-Fi on", "Didn't need to buy a new phone gereksiz kalan işlemdir."),
            "The battery is empty, so I'll charge the phone before trying the app again.",
            sq("İlk yapılması planlanan işlem hangisi?", "Charging the phone", "Deleting every app", "Changing the language", "Before trying the app again öncesinde şarj edileceğini belirtir.")),
        s(22, "My appointment was at ten on Thursday, but I had to attend a meeting at work. I called the office on Wednesday to ask for another time. They offered Friday at eleven. I accepted and wrote the new date in my calendar so I wouldn't forget it.",
            sq("Yeni randevu ne zaman?", "Friday at eleven", "Thursday at ten", "Wednesday at eleven", "Offered Friday at eleven ve I accepted yeni kabul edilen zamanı verir."),
            sq("Neden randevu değiştirildi?", "A work meeting conflicted with it.", "The calendar was lost.", "The office closed permanently.", "Had to attend a meeting at work zaman çakışmasıdır."),
            "Could we move Tuesday's appointment to Wednesday? Tuesday is no longer possible for me.",
            sq("Hangi gün alternatif olarak öneriliyor?", "Wednesday", "Tuesday", "Thursday", "Move ... to Wednesday yeni günü belirtir.")),
        s(23, "After a busy week, I felt tired and didn't want to go out. My friend suggested a quiet walk instead of a noisy party. We walked by the river and talked. I felt more relaxed afterwards, although I still wanted to go to bed early.",
            sq("Parti yerine ne önerildi?", "A quiet walk", "A shopping trip", "A late-night film", "Instead of a noisy party yerine sessiz yürüyüş öneriliyor."),
            sq("Yürüyüşten sonraki durum nasıl?", "More relaxed, but still ready for an early night", "Completely energetic and ready for a party", "More angry than before", "More relaxed olumlu değişim; still wanted to go to bed early yorgunluğun bütünüyle bitmediğini gösterir."),
            "I'm pleased about the result, but worried about the next test.",
            sq("Kişi kaç farklı duyguyu ifade ediyor?", "Two: pleased and worried", "One: angry", "None", "But, memnuniyet ile endişeyi birlikte ifade ediyor.")),
        s(24, "We visited a nature park with our class. The guide asked us not to feed the wild animals or leave the paths. We saw birds near the lake and took photos from a distance. Before leaving, we checked that we had all our bags and had left no litter.",
            sq("Rehber hangi davranışı istemiyor?", "Feeding the wild animals", "Taking photos from a distance", "Staying on the paths", "Not to feed ... or leave the paths yapılmaması istenen iki davranıştır."),
            sq("Ayrılmadan önce ne kontrol edildi?", "Bags and litter", "The animals' names only", "The train engine", "Tüm çantalar ve geride çöp kalmaması kontrol edildi."),
            "Please stay on the marked path. The plants beside it are protected.",
            sq("Patikada kalmak hangi amaçla ilişkilendiriliyor?", "Protecting the plants", "Getting closer to every animal", "Finding a shortcut", "Korunan bitkiler, patikadan ayrılmama talebinin bağlamını oluşturur."))
    )
}
