package com.linguapro.android

internal object WritingModelsB1 {
    val answers = mapOf(
        "B1-U1" to "The customer requested changes just before the website deadline, so the team needed more time. They agreed to show the revised design on Friday and deliver the working site on Monday. Afterwards, an email recorded the agreement so everyone understood the two different delivery dates.",
        "B1-U2" to "A signal failure stopped the train between stations. The passenger called the family waiting at the destination and explained the delay. They could then wait in a café instead of outside. The train arrived forty minutes late, but the call helped everyone arrange where to meet.",
        "B1-U3" to "The neighbours wanted different things from the same room: quiet study and exercise. They noticed that these activities were needed at different times, so they proposed a timetable. They would review it after a month because the compromise seemed useful but had not yet been tested in practice.",
        "B1-U4" to "The applicant lacked the experience requested in design advertisements. Following a tutor's advice, they made three sample projects and sought feedback. One employer still rejected the application, but another invited a discussion. The portfolio improved how the applicant demonstrated ability without guaranteeing a job offer.",
        "B1-U5" to "A headline suggested that the recycling centre would close, but the article described an ongoing discussion. The speaker checked the council's notice and found no final decision. Sharing that detail helped neighbours understand the uncertainty rather than treating a possible closure as something already decided.",
        "B1-U6" to "The speaker requested a file check without saying when it was needed. The colleague thought it could wait, which caused a misunderstanding. After the urgency was explained, the colleague checked the key section first. Future messages included the action and deadline to make requests clearer.",
        "B1-U7" to "Moving to a larger city offered more job opportunities but also higher rent and distance from family. Instead of moving permanently at once, the speaker accepted a short placement and kept a room at home. This allowed a comparison of everyday life before making a longer-term decision.",
        "B1-U8" to "A recently bought washing machine stopped working. The customer contacted the shop with the receipt and explained that the connection had already been checked. The employee arranged an inspection and supplied a reference number. This gave the customer a clear next step and a way to follow up.",
        "B1-U9" to "The club compared two venues and initially considered only rent. Adding travel costs and late-night access made the central venue more suitable for most members, despite its higher advertised price. Two members still disagreed, so the club recorded their concerns rather than presenting the choice as unanimous.",
        "B1-U10" to "Working late had left the speaker tired. They decided to leave on time twice a week, keep a regular bedtime and discuss late requests earlier with the manager. After two weeks, they felt more rested. The change helped, although it did not remove every busy day.",
        "B1-U11" to "Expected rain moved the concert indoors, where fewer seats required people to confirm attendance again. One friend could not attend at the new time. The group kept her informed and arranged a meal on another day, showing that they could maintain their friendship despite the changed event.",
        "B1-U12" to "The manager praised report quality but asked for better timing. An example showed that another team needed figures before noon. The speaker and manager agreed on an earlier draft and a check-in. The feedback identified a process improvement rather than rejecting the value of the reports.",
        "B1-U13" to "In the interview, the applicant described a delivery problem, actions taken and the result. When asked about personal involvement, they separated their own contribution from the team's work. This made the account more specific and avoided suggesting that one person had handled every part of the solution.",
        "B1-U14" to "The speaker could not finish an urgent request and another task that morning. They explained the conflict and offered to check the most important page before lunch. The colleague agreed that the rest could wait until tomorrow. A smaller agreed task kept both requests from becoming late.",
        "B1-U15" to "The reports agreed about the event's time and place but highlighted different concerns. One discussed traffic, while the other explained residents' reasons for organising it. The speaker's summary preserved both shared facts and different emphases, instead of describing the articles as contradictory in every detail.",
        "B1-U16" to "The speaker wanted to cook more but had little evening time. Simple recipes and ingredients bought in advance made the plan easier to follow. One late meeting still led to eating out. The speaker kept the plan because it usually helped, even without perfect daily success.",
        "B1-U17" to "The evening course fitted around daytime work, but recordings could not replace group activities. The speaker checked the dates of those sessions before enrolling. This helped them assess the real attendance requirements rather than assuming that watching recordings would cover every part of the course.",
        "B1-U18" to "A direct bus took longer than driving, but removed the need to find parking and allowed reading during the journey. After trying it for two weeks, the speaker found it useful. Driving remained an option when carrying heavy equipment, so the change was flexible rather than absolute.",
        "B1-U19" to "Recording purchases showed that small unplanned expenses added up. The speaker used this information to set a weekly amount for treats instead of banning all of them. The record helped replace an uncertain impression with a more informed choice about how to manage everyday spending.",
        "B1-U20" to "The viewer first found the film slow, then realised that early scenes explained the main character's behaviour. Those details became important by the ending. A friend still disliked the pace. Both praised the acting, showing that agreement about one feature did not mean identical overall opinions.",
        "B1-U21" to "A prize message looked familiar, but its unusual address made the speaker suspicious. They opened the company's usual site independently and found no prize notice. They deleted the message and explained their concern to a friend without assuming that every promotion was necessarily false or misleading.",
        "B1-U22" to "Unclear labels led neighbours to put waste in the wrong bins. Asking for clearer signs and examples reduced mistakes. The neighbours also checked local collection guidance because materials were collected on different days. The improvement came from clearer information rather than simply blaming people for the original confusion.",
        "B1-U23" to "The speaker explained how late music affected them and asked the neighbour to reduce the volume after ten. The neighbour apologised and welcomed further contact if necessary. They agreed on a practical time limit rather than arguing about musical taste or demanding silence throughout the whole day.",
        "B1-U24" to "The traveller reported a missing suitcase at the baggage desk and supplied identifying details. The record showed it was still at the previous airport. Before leaving, the traveller gave contact details and asked about updates, which made the next step clearer without claiming the suitcase had already arrived.",
        "B1-U25" to "The grandmother's recipe used unclear quantities, so the speaker struggled when cooking alone. Preparing it together again helped them record approximate amounts and the order of steps. The notes remained flexible because vegetables could affect the quantities; they were useful guidance rather than exact rules for every situation.",
        "B1-U26" to "The speaker turned a vague reading goal into two specific bus-journey sessions each week. Keeping a short novel in the bag made starting and finishing more achievable. After a missed session, they continued the next week instead of abandoning the goal, so the plan fitted their routine."
    )
}
