package com.linguapro.android

internal object WritingModelsB2 {
    val answers = mapOf(
        "B2-U1" to "The limited launch is a reasonable compromise because it allows sales to test customer interest while support prepares for common questions. It avoids treating enthusiasm as enough evidence for immediate expansion. However, a small pilot may not reveal every difficulty of a wider rollout. I would support expansion only after reviewing the pilot's results and checking whether support can handle the expected demand.",
        "B2-U2" to "Testing the booking system in a busier branch seems more defensible than assuming it will work everywhere. The initial reduction in waiting times is encouraging, but the two branches had unusually experienced staff. That limits how confidently the results can be generalised. A further trial could show whether the system performs well under different conditions, while preserving the positive evidence already obtained.",
        "B2-U3" to "The revised request is more effective because it combines a polite tone with a deadline and a reason. The original message suggested that the task was not urgent, so blaming the colleague would overlook the sender's unclear wording. However, a clear message cannot guarantee that every deadline will be met. The recipient may still need to explain competing priorities or ask for clarification.",
        "B2-U4" to "The group's cautious conclusion is appropriate because a higher completion rate does not establish that the online format caused it. The learners also differed in age and had selected the format themselves. Those differences could contribute to the outcome. However, the figures remain relevant evidence rather than becoming useless. A stronger comparison would need to address differences between groups before making a causal claim.",
        "B2-U5" to "Offering another occasion is a constructive response because it preserves the relationship without pressuring the visitor to explain herself. Her early start provides a practical reason for declining, so dislike should not be assumed. However, the host cannot know every motive from one indirect reply. A warm alternative allows the invitation to remain open while respecting the boundary actually expressed in the conversation.",
        "B2-U6" to "Requesting absolute figures and a longer comparison is sensible because a large percentage increase may represent only a small number of additional sales. The audience can acknowledge growth while asking whether it is large enough to justify a budget change. However, more context does not automatically settle the decision. Costs, capacity and future demand may still need consideration before a recommendation is made.",
        "B2-U7" to "The shared handover signal is useful because it addresses the teams' different assumptions about readiness. Focusing on the process makes the problem more concrete than blaming personalities. However, the agreement does not show that every departmental conflict has disappeared. I would review whether the signal is consistently understood and used, while treating any remaining disagreement as a separate issue rather than evidence that this clarification failed.",
        "B2-U8" to "Postponing an optional feature is a defensible way to shorten the schedule while preserving required safety checks. The leader makes the trade-offs visible instead of promising that time, scope and resources can all stay unchanged. However, reducing scope may disappoint people who expected the feature. The decision should therefore explain what is postponed and why, rather than presenting the shorter schedule as a cost-free improvement.",
        "B2-U9" to "Organising the review around a research question makes it more useful than listing three separate summaries. It reveals agreement and disagreement while distinguishing source claims from the writer's interpretation. However, synthesis should not erase methodological differences or imply that all findings carry equal weight. The revised structure is stronger because it connects the sources, but its conclusions still need to respect the limits of each article.",
        "B2-U10" to "The trial is a reasonable way to address both pedestrian safety and delivery access. Involving parents and shop owners helps make competing practical needs visible before a permanent decision. However, temporary measures may not predict every effect of a lasting change. The review should therefore consider problems as well as benefits, rather than treating popularity with one group as sufficient evidence of overall success.",
        "B2-U11" to "Stating the recommendation before the supporting reasons gives the audience a clearer argument. Removing an unrelated anecdote also helps the opening story serve a purpose rather than distract from the decision. However, a well-structured talk does not make weak evidence strong. The speaker still needs reasons that support the proposed action and should be ready to answer questions about its limits as well as its appeal.",
        "B2-U12" to "Adding the missing reminder is more constructive than treating all private notes as resistance. The workshop showed that staff were addressing a genuine gap in the new system, so the change responds to their working needs. However, one improvement may not resolve every adoption problem. Managers should still clarify which records must be shared and check whether other practical difficulties remain after the reminder is introduced.",
        "B2-U13" to "The revised report is better for planning because it separates completed work from readiness to deliver. Assigning owners to the two blocking tasks makes the next steps clearer. However, naming those tasks does not establish that they will be finished on time. Reviewing progress before announcing a final date is therefore more defensible than relying on an optimistic percentage that hides dependencies.",
        "B2-U14" to "The narrower packaging claim is stronger because customers can understand what has changed and what has not. Reducing material is a specific benefit, while a broad environmental label leaves the comparison unclear. However, less material alone does not demonstrate an improvement on every environmental measure. The company should preserve that distinction rather than allowing a precise statement to become another unsupported claim of overall superiority.",
        "B2-U15" to "The shorter initial contract balances the supplier's interest in commitment with the customer's need for flexibility. A slightly higher price and an option to extend allow both sides to protect an important priority. However, the compromise does not remove uncertainty about future demand. The review date matters because it provides a point to reconsider the arrangement rather than pretending that the original risk has disappeared.",
        "B2-U16" to "Comparing the commentary with the article is valuable because it exposes an explanation reduced to a single cause. The source describes several changes and different effects on households. However, identifying that simplification does not determine the best policy response. A fair discussion should first preserve the broader explanation, then consider which response follows from the evidence instead of assuming that criticism of a summary settles the policy debate.",
        "B2-U17" to "A further field trial is justified because the laboratory demonstration did not reveal problems with dust and maintenance. Changing the casing and clarifying upkeep responds to evidence from ordinary use rather than dismissing the prototype completely. However, those changes are not proof of readiness. The next trial should test whether they solve the identified problems and whether other practical limits appear outside the controlled setting.",
        "B2-U18" to "Specifying response times is a useful improvement because the organisations attached different meanings to urgent. Clear timing and weekend exceptions make expectations easier to discuss before signing. However, precise wording cannot anticipate every unusual event or prevent every disagreement. The clause is stronger because it reduces one important ambiguity, rather than because it guarantees that the service relationship will always work without further clarification.",
        "B2-U19" to "Examining the procedure before blaming participants is appropriate because the changed instructions conflicted with the original ones. A slower result alone cannot distinguish poor attention from confusion caused by the task. However, unclear instructions do not prove that attention played no role. The facilitator's question keeps both explanations open and asks for evidence that could separate them, making the judgement more proportionate to what was observed.",
        "B2-U20" to "The revised presentation is clearer because it begins with a question and selects evidence relevant to the conclusion. Keeping full tables in an appendix allows later inspection without interrupting the main argument. However, selection can still mislead if important contrary evidence is omitted. The presenter should explain the reasoning and remain prepared to discuss the detailed data, rather than treating a clear structure as sufficient proof.",
        "B2-U21" to "Adding response counts and distributions improves the dashboard because similar averages can hide very different experiences. It also makes small samples visible, limiting the confidence of comparisons. However, a fuller display does not identify every reason for variation between teams. I would use it to guide further questions rather than as an automatic ranking, especially where a few responses could have a large effect on the average.",
        "B2-U22" to "Requesting a private correction is proportionate because the missing acknowledgement is visible, while the presenter's intention is uncertain. Correcting the slides addresses the colleague's contribution before the external meeting. However, the presenter's explanation does not establish with certainty why the omission occurred. The employee can recognise the practical correction without claiming either deliberate misconduct or complete proof that the original mistake was accidental.",
        "B2-U23" to "Stating the boundary makes the comparison fairer because regional emissions and suppliers' transport distances measure different effects. The proposal may improve one while worsening another. However, choosing a boundary does not by itself show that it is the most appropriate one. The discussion should explain whose costs and benefits are counted, then assess the trade-off rather than treating the two positions as necessarily contradictory.",
        "B2-U24" to "The revision is more defensible because its wording matches the study's limited claim and explains the evidence's relevance. Replacing proved avoids suggesting certainty that the source does not provide. However, careful phrasing cannot make one study support conclusions outside the conditions examined. The paragraph should retain those conditions and distinguish the study's findings from the student's broader argument, allowing readers to judge the connection for themselves."
    )
}
